#config_version=5

mode:
   start_events: playfield_double_start
   stop_events: end_double_bonus, ball_ending
   priority: 2500

event_player:
   mode_playfieldDouble_started:
     invoke_notify_by_event:
       new_text: "PLAYFIELD\nMULTIPLIER"
       new_value: "DOUBLE"
   timer_doublepf_complete:
     - end_double_bonus

show_player:
   mode_playfieldDouble_started:
      pfDouble:
        loops: -1
   timer_doublepf_complete:
      pfDouble:
        action: stop

timers:
   doublepf:
     start_value: 31
     end_value: 0
     direction: down
     start_running: true
     control_events:
        - event: global_timer_pause
          action: pause
        - event: global_timer_unpause
          action: start

variable_player:
   mode_playfieldDouble_started:
     temp_playfield_x:
       action: set
       int: current_player.temp_playfield_x * 2
   timer_doublepf_stopped:
     temp_playfield_x:
       action: set
       int: current_player.temp_playfield_x / 2

widget_player:
   mode_playfieldDouble_started:
       doubleTimer:
          slide: scoring_slide
   timer_doublepf_complete:
       doubleTimer:
          slide: scoring_slide
          action: remove

widgets:
  doubleTimer:
    - type: ellipse
      width: 70
      height: 70
      color: 008C1B
      x: 15.5%
      y: 18%
      anchor_x: center
      anchor_y: center
      z: 10
    - type: ellipse
      width: 70
      height: 70
      color: black
      x: 15.5%
      y: 18%
      anchor_x: center
      anchor_y: center
      z: 20
      angle_start: 0
      angle_end: 12
      animations:
         timer_doublepf_tick:
            property: angle_end
            value: 12
            relative: true
            duration: 1s
    - type: ellipse
      width: 60
      height: 60
      color: black
      x: 15.5%
      y: 18%
      anchor_x: center
      anchor_y: center
      z: 30
    - type: text
      text: 2X
      font_name: lucon
      x: 15.5%
      y: 18%
      anchor_x: center
      anchor_y: center
      z: 40
      color: BBD8F0
      font_size: 32


