#config_version=5

event_player:
   story_is_about_to_begin:
     - mode_01_setintro_01
     - mode_01_setintro_02
     - mode_01_setintro_03
     - story_intro_complete|4s
   mode_01_setintro_01:
     set_infoboard_line_text:
        linenbr: 1
        text: "LOCATE THE CYGNUS"
        pts: none
        secs: none
        cycle: "star"
        delayms: 25
   mode_01_setintro_02:
     set_infoboard_line_text:
        linenbr: 2
        text: "LOCK COORDINATES AT TOP LANES"
        pts: none
        secs: none
        cycle: "star"
        delayms: 25
   mode_01_setintro_03:
     set_infoboard_line_text:
        linenbr: 3
        text: "DOCK WITH CYGNUS AT THE SCOOP"
        pts: none
        secs: none
        cycle: "star"
        delayms: 25

   story_intro_complete:
     - mode_01_setinfo_01
     - mode_01_setinfo_02
     - mode_01_setinfo_03

   mode_01_setinfo_01:
     set_infoboard_line_text:
        linenbr: 1
        text: "LOCATE THE CYGNUS"
        pts: none
        secs: none
        cycle: "instant"
        delayms: 0
   player_modestat_1_scoring:
     set_infoboard_line_text:
        linenbr: 1
        text: "LOCATE THE CYGNUS"
        pts: modestat_1_scoring
        secs: none
        cycle: "instant"
        delayms: 0
   mode_01_setinfo_02:
     set_infoboard_line_text:
        linenbr: 2
        text: "TOP LANES LOCK COORDINATES"
        pts: none
        secs: none
        cycle: "instant"
        delayms: 0
   mode_01_setinfo_03:
     set_infoboard_line_text:
        linenbr: 3
        text: "Docking Value:"
        pts: cygnus_completing_scoring_base
        secs: none
        cycle: "instant"
        delayms: 0
   player_cygnus_completing_scoring_base:
     set_infoboard_line_text:
        linenbr: 3
        text: "Docking Value:"
        pts: cygnus_completing_scoring_base
        secs: none
        cycle: "instant"
        delayms: 0
   cygnus_lane_0_event:
     set_infoboard_line_text:
        linenbr: 2
        text: "ALPHA COORDINATES LOCKED"
        pts: none
        secs: none
        cycle: "scroll"
        delayms: 25
   cygnus_lane_1_event:
     set_infoboard_line_text:
        linenbr: 2
        text: "BETA COORDINATES LOCKED"
        pts: none
        secs: none
        cycle: "scroll"
        delayms: 25
   cygnus_lane_2_event:
     set_infoboard_line_text:
        linenbr: 2
        text: "GAMMA COORDINATES LOCKED"
        pts: none
        secs: none
        cycle: "scroll"
        delayms: 25
   cygnus_lane_3_event:
     set_infoboard_line_text:
        linenbr: 2
        text: "DELTA COORDINATES LOCKED"
        pts: none
        secs: none
        cycle: "scroll"
        delayms: 25
   cygnus_lane_4_event:
     set_infoboard_line_text:
        linenbr: 2
        text: "EPSILON COORDINATES LOCKED"
        pts: none
        secs: none
        cycle: "scroll"
        delayms: 25
# added 25ms * 30 delay below to insure lane notifications occur first
   cygnus_located:
     - cygnus_dock_prompt|750ms
   cygnus_dock_prompt:
     set_infoboard_line_text:
        linenbr: 2
        text: "CYGNUS DOCKING ENABLED"
        pts: none
        secs: none
        cycle: "star"
        delayms: 25
     cygnus_scoop_prompt|3s:
        dmy: 0
   cygnus_scoop_prompt:
     set_infoboard_line_text:
        linenbr: 2
        text: "DOCK WITH CYGNUS AT THE SCOOP"
        pts: none
        secs: none
        cycle: "star"
        delayms: 25
     cygnus_dock_prompt|3s:
        dmy: 0
