#config_version=5

# Locate the Cygnus (s01) -
# Lock in coordinates with the lanes and scoop out.

config:
  - story01-scoring.yaml
  - ballsave.yaml
  - notification.yaml

mode:
   start_events: selector_untitled_mode_1_selected
   stop_events: story_is_completed
   priority: 900
   file_log: full

# All Story Modes --
#     Issue a scoop_eject after any introduction activities
# Modes that end with a Scoop Hit --
#     Issue a scoop eject after any outro-activities
# TEMP UNTIL REAL MODE PUT INTO PLACE

# Success/Failure
# By default, success = not losing ball, failure = losing ball
# If your mode has a different ruleset, change when the events
# story_is_completed_successful / acheivement_story##_successful
# story_is_completed_unsuccessful / acheivement_story##_unsuccessful
# are issued.

queue_relay_player:
  ball_ending:
    post: story_is_about_to_fail
    wait_for: story_outro_fail_complete

event_player:
   mode_story01_started:
     - story_is_about_to_begin
   story_intro_complete:
     - scoop_eject
   cygnus_found:
     - story_is_about_to_end
   in_mode_ball_save:
     - story_is_about_to_fail
   story_outro_complete:
     - story_is_completed_successful
     - acheivement_story01_successful
   story_outro_complete_failed:
     - story_is_completed_unsuccessful
     - acheivement_story01_unsuccessful
   story_is_completed_successful:
     - scoop_eject
     - story_is_completed
   story_is_completed_unsuccessful:
     - story_is_completed
# Mode Specific Event Handlers
   shotGroupToplanesStory01_lit_complete:
     - cygnus_located
   shotScoopStory01_ShotProfileScoopStory01_scoopActive_hit:
     - cygnus_found
#   shotScoopStory01_ShotProfileScoopStory01_scoopInactive_hit:
#     - scoop_eject

# Do we want to do something for each lane found?
   shotLane0Story01_unlit_hit:
     - cygnus_lane_0_event
   shotLane1Story01_unlit_hit:
     - cygnus_lane_1_event
   shotLane2Story01_unlit_hit:
     - cygnus_lane_2_event
   shotLane3Story01_unlit_hit:
     - cygnus_lane_3_event
   shotLane4Story01_unlit_hit:
     - cygnus_lane_4_event


#  Base intro / outro shows
show_player:
   story_is_about_to_begin:
      story_01_intro:
         events_when_completed: story_intro_complete
         loops: 0
   story_is_about_to_fail:
      story_01_outro_failed:
         events_when_completed: story_outro_complete_failed
         loops: 0
   story_is_about_to_end:
      story_01_outro:
         events_when_completed: story_outro_complete
         loops: 0
   shotScoopStory01_ShotProfileScoopStory01_scoopInactive_hit:
      pinwheel:
        speed: 40
        loops: 1
        events_when_completed: scoop_eject

shows:
   story_01_intro:
     - time: 0
       slides: story_01_intro_slide
       duration: 3
   story_01_outro:
     - time: 0
       slides: story_01_outro_slide
       duration: 3
   story_01_outro_failed:
     - time: 0
       slides: story_01_outro_failed_slide
       duration: 3

slides:
   story_01_intro_slide:
    widgets:
      - type: text
        text: LOCATE THE CYGNUS
        color: red
        font_size: 100
        font_name: ocr-a-tribute-bold
      - type: text
        text: Lock in coordinates by lighting all top lanes then scoop out
        y: 40%
        color: red
        font_size: 50
   story_01_outro_slide:
    widgets:
      - type: text
        text: "CYGNUS LOCATED"
        color: red
        font_size: 100
        font_name: ocr-a-tribute-bold
      - type: text
        text: "Time Taken: (cygnus_seconds) seconds"
        y: 40%
        color: red
        font_size: 50
   story_01_outro_failed_slide:
    widgets:
      - type: text
        text: "CYGNUS NOT LOCATED"
        color: red
        font_size: 100
        font_name: ocr-a-tribute-bold
      - type: text
        text: "MISSION FAILURE"
        y: 40%
        color: red
        font_size: 50
      - type: text
        text: " ** BALL SAVED ** "
        y: 30%
        color: red
        font_size: 50

# The below is mode specific data

# SHOT PROFILES --
# 1.  Complete all of the lanes to activate the scoop
# 2.  Hit the scoop to complete the mode

shot_profiles:
  shotProfileToplanesStory01:
    block: true
    states:
      - name: unlit
        show: off
      - name: lit
        show: popred
    loop: false
  shotProfileScoopStory01:
    block: true
    advance_on_hit: false
    states:
      - name: scoopInactive
        show: off
      - name: scoopActive
        show: popgreen
shots:
  shotScoopStory01:
    switch: s_ir_scoop_detect
    advance_events: cygnus_located
    show_tokens:
      light: l_scoop
    profile: shotProfileScoopStory01
  shotLane0Story01:
    switch: s_lane0, s_dTargetCL
    show_tokens:
      light: l_lane0
    profile: shotProfileToplanesStory01
  shotLane1Story01:
    switch: s_lane1, s_roInLaneLeft
    show_tokens:
      light: l_lane1
    profile: shotProfileToplanesStory01
  shotLane2Story01:
    switch: s_lane2, s_sTargetYellowL, s_sTargetYellowR
    show_tokens:
      light: l_lane2
    profile: shotProfileToplanesStory01
  shotLane3Story01:
    switch: s_lane3, s_roInLaneRight
    show_tokens:
      light: l_lane3
    profile: shotProfileToplanesStory01
  shotLane4Story01:
    switch: s_lane4, s_dTargetCR
    show_tokens:
      light: l_lane4
    profile: shotProfileToplanesStory01

shot_groups:
   shotGroupToplanesStory01:
       shots: shotLane0Story01, shotLane1Story01, shotLane2Story01, shotLane3Story01, shotLane4Story01
       reset_events: story_is_completed_unsuccessful
       enable_events: story_is_about_to_begin
#       rotate_left_events: s_flipper_left_active
#       rotate_right_events: s_flipper_right_active
#       disable_events: ball_ending



variable_player:
   story_intro_complete:
     cygnus_timer_ticks:
       action: set
       int: 0
   timer_cygnusTimer_tick:
     cygnus_timer_ticks: 1
   cygnus_found:
     cygnus_seconds:
       float: current_player.cygnus_timer_ticks / 10
       action: set
   story_is_about_to_end:
     modestat_1_final_timing:
       action: set
       float: current_player.cygnus_seconds

timers:
   cygnusTimer:
     start_value: 0
     tick_interval: .1s
     direction: up
     start_running: no
     control_events:
     - event: story_intro_complete
       action: start
     - event: cygnus_found
       action: stop

widget_player:
   story_intro_complete:
      cygnus_searching:
         slide: scoring_slide
   cygnus_located:
      cygnus_searching:
         action: remove
      cygnus_found:
         slide: scoring_slide
   story_is_about_to_end:
      cygnus_searching:
         action: remove
      cygnus_found:
         action: remove

widgets:
   cygnus_searching:
     - type: text
       text: "Locate The Cygnus by Lighting Top Lanes"
       y: 80%
   cygnus_found:
     - type: text
       text: "Dock with the Cygnus by Scooping Out"
       y: 80%

sound_player:
    mode_story01_started:
      thatsit:
          action: play
          loops: -1
          fade_out: 2s
          mode_end_action: stop
          volume: 0.5