#config_version=5

# Locate the Cygnus (s01) -
# Lock in coordinates with the lanes and scoop out.

# CHARACTER COLLECTION CRITERIA
# Mode completion criteria -- 75s

config:
  - story01-scoring.yaml
  - infoboard.yaml

mode:
   start_events: ready_to_start_mode_1
   stop_events: story_is_completed
   priority: 900
   file_log: full

# All Story Modes --
#     Issue a scoop_eject after any introduction activities
# Modes that end with a Scoop Hit --
#     Issue a scoop eject after any outro-activities
# TEMP UNTIL REAL MODE PUT INTO PLACE

# Success/Failure
# By default, success = not losing ball, failure = losing ball
# If your mode has a different ruleset, change when the events
# story_is_completed_successful / acheivement_story##_successful
# story_is_completed_unsuccessful / acheivement_story##_unsuccessful
# are issued.

queue_relay_player:
  ball_ending:
    post: story_is_about_to_fail
    wait_for: story_outro_fail_complete

event_player:
   mode_story01_started:
     - story_is_about_to_begin
     - information_board_start
   story_intro_complete:
     - scoop_eject
     - start_cygnus_timer
     - global_timer_unpause
   cygnus_found:
     - story_is_about_to_end
     - story_01_is_about_to_end
   story_outro_complete:
     - global_timer_unpause
     - story_is_completed_successful
     - acheivement_story01_successful
   story_outro_complete_failed:
     - story_is_completed_unsuccessful
     - acheivement_story01_unsuccessful
   story_is_completed_successful:
     - scoop_eject
     - story_is_completed
   story_is_completed_unsuccessful:
     - story_is_completed
# Mode Specific Event Handlers
   shotGroupToplanesStory01_lit_complete:
     - cygnus_located
   shotScoopStory01_shotProfileScoopStory01_scoopActive_hit:
     - cygnus_found
     - global_timer_pause
     - information_board_end
#   shotScoopStory01_ShotProfileScoopStory01_scoopInactive_hit:
#     - scoop_eject
# Character Collect
   player_modestat_1_final_timing{value<75.0}:
     - random_character_collect|3s
# Do we want to do something for each lane found?
   shotLane0Story01_unlit_hit:
     - cygnus_lane_0_event
     - cygnus_lane_score
   shotLane1Story01_unlit_hit:
     - cygnus_lane_1_event
     - cygnus_lane_score
   shotLane2Story01_unlit_hit:
     - cygnus_lane_2_event
     - cygnus_lane_score
   shotLane3Story01_unlit_hit:
     - cygnus_lane_3_event
     - cygnus_lane_score
   shotLane4Story01_unlit_hit:
     - cygnus_lane_4_event
     - cygnus_lane_score
   shotGroupToplanesStory01_lit_hit:
     - cygnus_lane_repeat_score


#  Base intro / outro shows
show_player:
   story_is_about_to_fail:
      story_01_outro_failed:
         events_when_completed: story_outro_complete_failed
         loops: 0
   story_is_about_to_end:
      story_01_outro:
         events_when_completed: story_outro_complete
         loops: 0
   shotScoopStory01_shotProfileScoopStory01_scoopInactive_hit:
      pinwheel:
        speed: 40
        loops: 1
        events_when_completed: scoop_eject
   cygnus_lane_0_event:
      lane_hit:
        loops: 5
        priority: 10000
        show_tokens:
          gi_1: l_GILane0
          gi_2: l_GILane1
          curr_lane: l_lane0
   cygnus_lane_1_event:
      lane_hit:
        loops: 5
        priority: 10000
        show_tokens:
          gi_1: l_GILane1
          gi_2: l_GILane2
          curr_lane: l_lane1
   cygnus_lane_2_event:
      lane_hit:
        loops: 5
        priority: 10000
        show_tokens:
          gi_1: l_GILane2
          gi_2: l_GILane3
          curr_lane: l_lane2
   cygnus_lane_3_event:
      lane_hit:
        loops: 5
        priority: 10000
        show_tokens:
          gi_1: l_GILane3
          gi_2: l_GILane4
          curr_lane: l_lane3
   cygnus_lane_4_event:
      lane_hit:
        loops: 5
        priority: 10000
        show_tokens:
          gi_1: l_GILane4
          gi_2: l_GILane5
          curr_lane: l_lane4

# The below is mode specific data

# SHOT PROFILES --
# 1.  Complete all of the lanes to activate the scoop
# 2.  Hit the scoop to complete the mode

shot_profiles:
  shotProfileToplanesStory01:
    block: true
    states:
      - name: unlit
        show: off
      - name: lit
        show: popred
    loop: false
  shotProfileScoopStory01:
    block: true
    advance_on_hit: false
    states:
      - name: scoopInactive
        show: off
      - name: scoopActive
        show: scoopReadyShow

shots:
  shotScoopStory01:
    switch: s_ir_scoop_detect
    advance_events: cygnus_located
    reset_events: story_outro_complete
    show_tokens:
      light: l_scoop
    profile: shotProfileScoopStory01
  shotLane0Story01:
    switch: s_lane0, s_dtargetcl
    show_tokens:
      light: l_lane0
    profile: shotProfileToplanesStory01
  shotLane1Story01:
    switch: s_lane1, s_roInLaneLeft
    show_tokens:
      light: l_lane1
    profile: shotProfileToplanesStory01
  shotLane2Story01:
    switch: s_lane2, s_sTargetYellowL, s_sTargetYellowR
    show_tokens:
      light: l_lane2
    profile: shotProfileToplanesStory01
  shotLane3Story01:
    switch: s_lane3, s_roInLaneRight
    show_tokens:
      light: l_lane3
    profile: shotProfileToplanesStory01
  shotLane4Story01:
    switch: s_lane4, s_dtargetcr
    show_tokens:
      light: l_lane4
    profile: shotProfileToplanesStory01

shot_groups:
   shotGroupToplanesStory01:
       shots: shotLane0Story01, shotLane1Story01, shotLane2Story01, shotLane3Story01, shotLane4Story01
       reset_events: story_is_about_to_begin, story_is_completed_unsuccessful
       enable_events: story_outro_complete

variable_player:
   story_intro_complete:
     cygnus_timer_ticks:
       action: set
       int: 0
   timer_cygnusTimer_tick:
     cygnus_timer_ticks: 1
   timer_cygnusTimer_tick{current_player.cygnus_timer_ticks < 760 and current_player.cygnus_timer_ticks > 10}:
     cygnus_completing_scoring_base: -30667
   timer_cygnusTimer_tick{current_player.cygnus_timer_ticks == 760}:
     cygnus_completing_scoring_base: -30417
   player_cygnus_completing_scoring_base:
     cygnus_completing_scoring_actual:
       int: current_player.cygnus_completing_scoring_base * current_player.temp_playfield_x * current_player.perm_playfield_x
       action: set
   cygnus_found:
     cygnus_seconds:
       float: current_player.cygnus_timer_ticks / 10
       action: set
   story_is_about_to_end:
     modestat_1_final_timing:
       action: set
       float: current_player.cygnus_seconds


timers:
   cygnusTimer:
     start_value: 0
     tick_interval: .1s
     direction: up
     start_running: no
     control_events:
     - event: start_cygnus_timer
       action: start
     - event: cygnus_found
       action: stop
     - event: global_timer_pause
       action: pause
     - event: global_timer_unpause
       action: start

sound_player:
    mode_story01_started:
      overture:
          action: stop
          fade_out: 0
    mode_01_end_video:
      cygnusfloating:
          action: play
          loops: -1
          mode_end_action: stop





