#config_version=5
variable_player:
  story_is_about_to_begin:
    cygnus_lane_count: 0
    cygnus_lane_scoring_base: 200000
    cygnus_completing_scoring_base: 25000000
  cygnus_lane_score:
    cygnus_lane_count: 1
    bonuscount: 3
  player_cygnus_lane_count:
    score:
      int: current_player.cygnus_lane_scoring_base * current_player.cygnus_lane_count * current_player.temp_playfield_x * current_player.perm_playfield_x
      action: add
  cygnus_lane_repeat_score:
    score: 10000 * current_player.temp_playfield_x * current_player.perm_playfield_x
    bonuscount: 1
  cygnus_located:
    score: 2000000 * current_player.temp_playfield_x * current_player.perm_playfield_x
    bonuscount: 3
  cygnus_found:
    score: current_player.cygnus_completing_scoring_base * current_player.temp_playfield_x * current_player.perm_playfield_x
    bonuscount: 3
