#config_version=5
variable_player:
  story_intro_complete:
    cygnus_lane_count:
      action: set
      int: 0
    cygnus_lane_scoring_base:
      action: set
      int: 200000
    cygnus_completing_scoring_base:
      action: set
      int: 25000000
    modestat_1_base_scoring:
      action: set
      int: 0
    modestat_1_scoring:
      action: set
      int: 0
  cygnus_lane_score:
    cygnus_lane_count: 1
    bonuscount: 3
  player_cygnus_lane_count:
    score:
      int: current_player.cygnus_lane_scoring_base * current_player.cygnus_lane_count * current_player.temp_playfield_x * current_player.perm_playfield_x
      action: add
    modestat_1_scoring:
      int: current_player.cygnus_lane_scoring_base * current_player.cygnus_lane_count * current_player.temp_playfield_x * current_player.perm_playfield_x
      action: add
    modestat_1_base_scoring:
      int: current_player.cygnus_lane_scoring_base * current_player.cygnus_lane_count
      action: add
  cygnus_lane_repeat_score:
    score: 10000 * current_player.temp_playfield_x * current_player.perm_playfield_x
    bonuscount: 1
    modestat_1_scoring: 10000 * current_player.temp_playfield_x * current_player.perm_playfield_x
    modestat_1_base_scoring: 10000
  cygnus_located:
    score: 2000000 * current_player.temp_playfield_x * current_player.perm_playfield_x
    bonuscount: 3
    modestat_1_scoring: 2000000 * current_player.temp_playfield_x * current_player.perm_playfield_x
    modestat_1_base_scoring: 2000000
  cygnus_found:
    score: current_player.cygnus_completing_scoring_base * current_player.temp_playfield_x * current_player.perm_playfield_x
    bonuscount: 3
    modestat_1_scoring: current_player.cygnus_completing_scoring_base * current_player.temp_playfield_x * current_player.perm_playfield_x
    modestat_1_base_scoring: current_player.cygnus_completing_scoring_base
