#config_version=5

mode:
   start_events: playfield_triple_start
   stop_events: end_triple_bonus
   priority: 2500

event_player:
   mode_playfieldTriple_started:
     invoke_notify_by_event:
       new_text: "PLAYFIELD\nMULTIPLIER"
       new_value: "TRIPLE"
   timer_triplepf_complete:
     - end_triple_bonus

timers:
   triplepf:
     start_value: 30
     end_value: 0
     direction: down
     start_running: true

variable_player:
   mode_playfieldTriple_started:
     temp_playfield_x:
       action: set
       int: current_player.temp_playfield_x * 3
   timer_triplepf_stopped:
     temp_playfield_x:
       action: set
       int: current_player.temp_playfield_x / 3

