#config_version=5

mode:
   start_events: playfield_triple_start
   stop_events: end_triple_bonus
   priority: 2500

event_player:
   mode_playfieldTriple_started:
     invoke_notify_by_event:
       new_text: "PLAYFIELD\nMULTIPLIER"
       new_value: "TRIPLE"
   timer_triplepf_complete:
     - end_triple_bonus

timers:
   triplepf:
     start_value: 30
     end_value: 0
     direction: down
     start_running: true

variable_player:
   mode_playfieldTriple_started:
     temp_playfield_x:
       action: set
       int: current_player.temp_playfield_x * 3
   timer_triplepf_stopped:
     temp_playfield_x:
       action: set
       int: current_player.temp_playfield_x / 3

widget_player:
   mode_playfieldTriple_started:
       tripleTimer:
          slide: scoring_slide
   timer_triplepf_complete:
       tripleTimer:
          slide: scoring_slide
          action: remove

widgets:
  tripleTimer:
    - type: ellipse
      width: 80
      height: 80
      color: 012077
      y: 52%
      z: 10
    - type: ellipse
      width: 80
      height: 80
      color: black
      y: 52%
      z: 20
      angle_start: 0
      angle_end: 12
      animations:
         timer_triplepf_tick:
            property: angle_end
            value: 12
            relative: true
            duration: 1s
    - type: ellipse
      width: 70
      height: 70
      color: black
      y: 52%
      z: 30
    - type: text
      text: 3X
      font_name: lucon
      y: 52%
      z: 40
      color: BBD8F0
      font_size: 36


