#config_version=5

mode:
   start_events: trigger_super_jets
   stop_events: end_super_jets
   priority: 2500

event_player:
   mode_superJets_started:
     invoke_notify_by_event:
       new_text: "SUPER\nJETS"
       new_value: "ACTIVE"
   timer_superjets_complete:
     - end_super_jets

timers:
   superjets:
     start_value: 30
     end_value: 0
     direction: down
     start_running: true

variable_player:
  s_jet_upper_left_active:
    score: 1000 * current_player.temp_playfield_x * current_player.perm_playfield_x|block
  s_jet_upper_right_active:
    score: 1000 * current_player.temp_playfield_x * current_player.perm_playfield_x|block
  s_jet_lower_center_active:
    score: 1000 * current_player.temp_playfield_x * current_player.perm_playfield_x|block

widget_player:
   mode_superJets_started:
       superJetsTimer:
          slide: scoring_slide
   timer_superjets_complete:
       superJetsTimer:
          slide: scoring_slide
          action: remove

widgets:
  superJetsTimer:
    - type: ellipse
      width: 80
      height: 80
      color: 012077
      y: 76%
      z: 10
    - type: ellipse
      width: 80
      height: 80
      color: black
      y: 76%
      z: 20
      angle_start: 0
      angle_end: 12
      animations:
         timer_superspins_tick:
            property: angle_end
            value: 12
            relative: true
            duration: 1s
    - type: ellipse
      width: 70
      height: 70
      color: black
      y: 76%
      z: 30
    - type: text
      text: "SUPER\nJETS"
      font_name: lucon
      y: 76%
      z: 40
      color: BBD8F0
      font_size: 18
