#config_version=5

mode:
   start_events: trigger_super_jets
   stop_events: end_super_jets, ball_ending
   priority: 2500

event_player:
   mode_superJets_started:
     invoke_notify_by_event:
       new_text: "SUPER\nJETS"
       new_value: "ACTIVE"
   timer_superjets_complete:
     - end_super_jets

show_player:
   mode_superJets_started:
      superJet:
        loops: -1
   timer_superjets_complete:
      superJet:
        action: stop

timers:
   superjets:
     start_value: 30
     end_value: 0
     direction: down
     start_running: true
     control_events:
        - event: global_timer_pause
          action: pause
        - event: global_timer_unpause
          action: start

variable_player:
  s_jet_upper_left_active:
    score: 1000 * current_player.spins * current_player.temp_playfield_x * current_player.perm_playfield_x|block
  s_jet_upper_right_active:
    score: 1000 * current_player.spins *  current_player.temp_playfield_x * current_player.perm_playfield_x|block
  s_jet_lower_center_active:
    score: 1000 * current_player.spins *  current_player.temp_playfield_x * current_player.perm_playfield_x|block

widget_player:
   mode_superJets_started:
       superJetsTimer:
          slide: scoring_slide
   timer_superjets_complete:
       superJetsTimer:
          slide: scoring_slide
          action: remove

widgets:
  superJetsTimer:
    - type: ellipse
      width: 70
      height: 70
      color: 012077
      x: 84.5%
      y: 18%
      anchor_x: center
      anchor_y: center
      z: 10
    - type: ellipse
      width: 70
      height: 70
      color: black
      x: 84.5%
      y: 18%
      anchor_x: center
      anchor_y: center
      z: 20
      angle_start: 0
      angle_end: 12
      animations:
         timer_superjets_tick:
            property: angle_end
            value: 12
            relative: true
            duration: 1s
    - type: ellipse
      width: 60
      height: 60
      color: black
      x: 84.5%
      y: 18%
      anchor_x: center
      anchor_y: center
      z: 30
    - type: text
      text: "SUPER\nJETS"
      font_name: lucon
      x: 84.5%
      y: 18%
      anchor_x: center
      anchor_y: center
      z: 40
      color: BBD8F0
      font_size: 16
