#config_version=5

#This will be the mode that handles the RESCUE and SACRIFICE outlanes


# s_rooutlaneleft - RESCUE
# s_rooutlaneright - SACRIFICE

# --- SCORING VALUES -- SET AT GAME START IN /base/config/scoring.yaml
# outlane_rescue_value:
# outlane_sacrifice_value:

mode:
   start_events: ball_starting
   stop_events: ball_ending
   priority: 3000



# This is where we will respond to events that can enable the outlanes
event_player:
   mode_outlaneBots_started:
     - enable_outlane_rescue
     - set_sacrifice_off
   reenable_outlane_rescue:
     increase_rescue_value{current_player.rescue_is_active==1}:
       dmy: 0  # Did not work without this, seems to be because the other event has parms required
     invoke_notify_by_event{current_player.rescue_is_active==1}:
       new_text: "RESCUE\nINCREASED"
       new_value: ""
     enable_outlane_rescue{current_player.rescue_is_active==0}:
       dmy: 0  # Did not work without this, seems to be because the other event has parms required
     invoke_notify_by_event{current_player.rescue_is_active==0}:
       new_text: "RESCUE\nENABLED"
       new_value: ""
     display_rescue_increase{current_player.rescue_is_active==1}:
       dmy: 0
     display_rescue_enable{current_player.rescue_is_active==0}:
       dmy: 0
   reenable_outlane_sacrifice:
     increase_sacrifice_value{current_player.sacrifice_is_active==1}:
       dmy: 0  # Did not work without this, seems to be because the other event has parms required
     invoke_notify_by_event{current_player.sacrifice_is_active==1}:
       new_text: "SACRIFICE\nINCREASED"
       new_value: ""
     enable_outlane_sacrifice{current_player.sacrifice_is_active==0}:
       dmy: 0  # Did not work without this, seems to be because the other event has parms required
     invoke_notify_by_event{current_player.sacrifice_is_active==0}:
       new_text: "SACRIFICE\nENABLED"
       new_value: ""
     display_sac_increase{current_player.sacrifice_is_active==1}:
       dmy: 0
     display_sac_enable{current_player.sacrifice_is_active==0}:
       dmy: 0
   shotoutlanerescue_lit_hit{device.ball_saves.initial.state=="disabled"}:
     - rescue_lane_activated
   shotoutlanesacrifice_lit_hit:
     - sacrifice_lane_activated
   ball_save_rescuesave_saving_ball:
     invoke_notify_by_event:
       new_text: "RESCUE"
       new_value: "X"


#   shotoutlanesacrifice_lit_hit:

# ** enable and/or increment rescue value on some event
# ** enable sacrifice on some event
# ** trigger ballsave on lit rescue
# ** trigger scoring, display, and increase value on lit sacrifice shot

# EVENTS NOT YET IMPLEMENTED (nothing triggers them)
# enable_outlane_rescue
# enable_outlane_sacrifice


variable_player:
   rescue_lane_activated:
     score: current_player.outlane_rescue_value * current_player.temp_playfield_x * current_player.perm_playfield_x
     bonuscount: 1
     rescue_is_active:
        action: set
        int: 0
     last_rescue_score:
        action: set
        int: current_player.outlane_rescue_value * current_player.temp_playfield_x * current_player.perm_playfield_x
   increase_rescue_value:
     outlane_rescue_value:
        action: add
        int: 75000
   enable_outlane_rescue:
     rescue_is_active:
        action: set
        int: 1
     outlane_rescue_value:
        action: add
        int: 75000
   sacrifice_lane_activated:
     score: current_player.outlane_sacrifice_value * current_player.temp_playfield_x * current_player.perm_playfield_x
     bonuscount: 1
   sacrifice_complete:
     outlane_sacrifice_value:
        action: set
        int: current_player.outlane_sacrifice_value * 10
     sacrifice_is_active:
        action: set
        int: 0
   increase_sacrifice_value:
     outlane_sacrifice_value:
        action: add
        int: current_player.outlane_sacrifice_value
   set_sacrifice_off:
     sacrifice_is_active:
        action: set
        int: 0
   enable_outlane_sacrifice:
     sacrifice_is_active:
        action: set
        int: 1

shot_profiles:
   outlanebotrescue:
     advance_on_hit: false
     states:
        - name: unlit
          show: outlanerescueoff
          manual_advance: true
        - name: lit
          show: outlanerescueon
          manual_advance: true
   outlanebotsacrifice:
     advance_on_hit: false
     states:
        - name: unlit
          show: outlanesacrificeoff
          manual_advance: true
        - name: lit
          show: outlanesacrificeon
          manual_advance: true

shots:
  shotoutlanerescue:
    switch: s_rooutlaneleft
    profile: outlanebotrescue
    advance_events: enable_outlane_rescue
    reset_events: rescue_lane_activated
  shotoutlanesacrifice:
    switch: s_rooutlaneright
    profile: outlanebotsacrifice
    advance_events: enable_outlane_sacrifice
    reset_events: sacrifice_lane_activated

# this is a ball save that gets triggered when rescue lit is hit
ball_saves:
   rescueSave:
     enable_events: rescue_lane_activated

show_player:
   rescue_lane_activated:
     report_rescue_event:
        loops: 0
     report_sacrifice_event:
        action: stop
     report_rescue_increased:
        action: stop
     report_rescue_activated:
        action: stop
     report_sacrifice_increased:
        action: stop
     report_sacrifice_activated:
        action: stop
   sacrifice_lane_activated:
     report_sacrifice_event:
        loops: 0
        events_when_completed: sacrifice_complete
     report_rescue_event:
        action: stop
     report_rescue_increased:
        action: stop
     report_rescue_activated:
        action: stop
     report_sacrifice_increased:
        action: stop
     report_sacrifice_activated:
        action: stop
   display_rescue_increase:
     report_rescue_increased:
        loops: 0
     report_rescue_event:
        action: stop
     report_sacrifice_event:
        action: stop
     report_rescue_activated:
        action: stop
     report_sacrifice_increased:
        action: stop
     report_sacrifice_activated:
        action: stop
   display_rescue_enable:
     report_rescue_activated:
        loops: 0
     report_rescue_event:
        action: stop
     report_sacrifice_event:
        action: stop
     report_rescue_increased:
        action: stop
     report_sacrifice_increased:
        action: stop
     report_sacrifice_activated:
        action: stop
   display_sac_increase:
     report_sacrifice_increased:
        loops: 0
     report_rescue_event:
        action: stop
     report_sacrifice_event:
        action: stop
     report_rescue_increased:
        action: stop
     report_rescue_activated:
        action: stop
     report_sacrifice_activated:
        action: stop
   display_sac_enable:
     report_sacrifice_activated:
        loops: 0
     report_rescue_event:
        action: stop
     report_sacrifice_event:
        action: stop
     report_rescue_increased:
        action: stop
     report_rescue_activated:
        action: stop
     report_sacrifice_increased:
        action: stop

shows:
   report_rescue_event:
     - time: 0
       widgets: rescue_used
       duration: 3
   report_rescue_increased:
     - time: 0
       widgets: rescue_increased
       duration: 3
   report_rescue_activated:
     - time: 0
       widgets: rescue_enabled
       duration: 3
   report_sacrifice_event:
     - time: 0
       widgets: sacrifice_used
       duration: 3
   report_sacrifice_increased:
     - time: 0
       widgets: sacrifice_increased
       duration: 3
   report_sacrifice_activated:
     - time: 0
       widgets: sacrifice_enabled
       duration: 3

# RESCUE LIGHT -- l_specialLeft
# SACRIFICE LIGHT -- l_specialRight
   outlanerescueoff:
     - time: 0
       lights:
         l_specialLeft : off
       duration: -1
   outlanerescueon:
     - time: 0
       lights:
         l_specialLeft : blue
       duration: -1
   outlanesacrificeoff:
     - time: 0
       lights:
         l_specialRight : off
       duration: -1
   outlanesacrificeon:
     - time: 0
       lights:
         l_specialRight : red
       duration: -1

slides:
   report_rescue_slide:
    widgets:
      - type: text
        text: RESCUE
        color: red
        font_size: 100
        font_name: ocr-a-tribute-bold
   report_sacrifice_slide:
    widgets:
      - type: text
        text: SACRIFICE
        color: red
        font_size: 100
        font_name: ocr-a-tribute-bold


widgets:
   rescue_enabled:
      - type: text
        text: "RESCUE ENABLED\n(outlane_rescue_value)"
        style:
          - char_collect_style
        number_grouping: true
   rescue_increased:
      - type: text
        text: "RESCUE VALUE\n(outlane_rescue_value)"
        style:
          - char_collect_style
        number_grouping: true
   rescue_used:
      - type: text
        text: "BALL RESCUED\nKEEP SHOOTING\n(outlane_rescue_value)"
        style:
          - char_collect_style
        number_grouping: true
   sacrifice_enabled:
      - type: text
        text: "SACRIFICE ENABLED\n(outlane_sacrifice_value)"
        style:
          - char_collect_style
        number_grouping: true
   sacrifice_increased:
      - type: text
        text: "SACRIFICE VALUE\n(outlane_sacrifice_value)"
        style:
          - char_collect_style
        number_grouping: true
   sacrifice_used:
      - type: text
        text: "SACRIFICE\n(outlane_rescue_value)"
        style:
          - char_collect_style
        number_grouping: true
