#config_version=5

# *************** METEOR STRIKE ******************
# A red light show of doooooooom will slowly descend upon the player.
# Hit the scoop to escape the meteor before the light show gets to the end
# Award score, restart show.  Mode ends on loss of ball or meteor strike on player (end of show)

config:
   - infoboard.yaml

mode:
   start_events: ready_to_start_mode_4
   stop_events: story_is_completed
   priority: 900
   file_log: full
   code: random_explosions.RandomExplosions

# All Story Modes --
#     Issue a scoop_eject after any introduction activities
# Modes that end with a Scoop Hit --
#     Issue a scoop eject after any outro-activities

# Success/Failure
# By default, success = not losing ball, failure = losing ball
# If your mode has a different ruleset, change when the events
# story_is_completed_successful / acheivement_story##_successful
# story_is_completed_unsuccessful / acheivement_story##_unsuccessful
# are issued.

queue_relay_player:
  ball_ending:
    post: ball_has_been_lost
    wait_for: story_is_completed

event_player:
   mode_story04_started:
     - story_is_about_to_begin
     - information_board_start
     - start_explosions|3s
#   --- scoop_eject_sequence now timed from infoboard to 3s before story_intro_complete
#   story_intro_complete:
#     - scoop_eject
#     - global_timer_unpause
#     - scoop_eject_sequence
   story_has_passed:
     - story_is_about_to_end
     - information_board_end
   story_has_failed:
     - story_is_about_to_fail
     - information_board_end
   story_outro_complete:
     - story_is_completed_successful
     - acheivement_story04_successful
   story_outro_fail_complete:
     - story_is_completed_unsuccessful
     - acheivement_story04_unsuccessful
   ball_ending{current_player.meteor_hits==0}:
     - story_is_completed_unsuccessful
     - acheivement_story04_unsuccessful
   ball_ending{current_player.meteor_hits>0}:
     - story_is_completed_successful
     - acheivement_story04_successful
   story_is_completed_successful:
    - story_is_completed
   story_is_completed_unsuccessful:
    - story_is_completed
# Character Collect
   player_meteor_hits{value==3}:
    - random_character_collect
   s_ir_scoop_detect_active{current_player.story04_meteortimer_tick==0}:
    - scoop_eject

#  Base intro / outro shows

# *** BASE show_player items have been moved into previously existing mode-specific items
#show_player:
#   story_is_about_to_begin:
#      story_04_intro:
#         events_when_advanced: story_intro_complete
#         events_when_completed: story_intro_complete
#         events_when_stopped: story_intro_complete
#         loops: 0
#   story_is_about_to_end:
#      story_04_outro:
#         events_when_advanced: story_outro_complete
#         events_when_completed: story_outro_complete
#         events_when_stopped: story_outro_complete
#         loops: 0


# The below is mode specific data

# EVENTS starting on mode_story04_started have been moved to story_intro_complete

# We will use a STATE MACHINE to drive whether or not the timer at the end of the mode
# triggers a SUCCESS or FAILURE response for the mode.
state_machines:
  end_result:
    states:
      start:
        label: willFail
      has_failed:
        label: hasFailed
        events_when_started: story_has_failed
      will_pass:
        label: willPass
        events_when_started: debug_event_will_pass_set
      has_passed:
        label: hasPassed
        events_when_started: story_has_passed
    transitions:
      - source: start
        target: will_pass
        events: shotScoopMeteor_hit
      - source: start
        target: has_failed
        events: timer_meteortimer_complete, ball_has_been_lost
      - source: will_pass
        target: has_passed
        events: timer_meteortimer_complete, ball_has_been_lost


variable_player:
  story_intro_complete:
    meteor_accum:
       int: 0
       action: set
    meteor_hits:
       int: 0
       action: set
    timeRemain:
       int: 30
       action: set
    modestat_4_base_scoring:
       action: set
       int: 0
    modestat_4_scoring:
       action: set
       int: 0
  timer_meteortimer_started:
    timeRemain:
       int: (ticks_remaining)
       action: set
  shotScoopMeteor_hit{current_player.story04_meteortimer_tick>0}:
    meteor_hits: 1
    bonuscount: 3
  player_meteor_hits{value>0}:
    score: (((current_player.meteor_hits) * 500000) + (50000 * current_player.timeRemain)) * current_player.temp_playfield_x * current_player.perm_playfield_x
    meteor_accum: (((current_player.meteor_hits) * 500000) + (50000 * current_player.timeRemain)) * current_player.temp_playfield_x * current_player.perm_playfield_x
    modestat_4_last_meteor:
       action: set
       int: (((current_player.meteor_hits) * 500000) + (50000 * current_player.timeRemain)) * current_player.temp_playfield_x * current_player.perm_playfield_x
    modestat_4_scoring: (((current_player.meteor_hits) * 500000) + (50000 * current_player.timeRemain)) * current_player.temp_playfield_x * current_player.perm_playfield_x
    modestat_4_base_scoring: ((current_player.meteor_hits) * 500000) + (50000 * current_player.timeRemain)
  timer_meteortimer_tick:
    timeRemain:
       int: (ticks_remaining)
       action: set
  story_is_about_to_end:
    modestat_4_final_hits:
       int: (current_player.meteor_hits)
       action: set

shots:
  shotScoopMeteor:
    switch: s_ir_scoop_detect
    profile: shotScoopMeteorProfile

shot_profiles:
  shotScoopMeteorProfile:
    show_when_disabled: true
    advance_on_hit: false
    block: true
    states:
      - name: scoopActive
        show: popgreen

show_player:
  scoop_eject_sequence:
     scoop_eject_sound_show:
       priority: 950
       loops: 0
       events_when_completed: scoop_eject, global_timer_unpause
     scoop_eject_light_show:
       priority: 950
       loops: 0
  shotScoopMeteor_hit:
     pinwheel:
       speed: 40
       loops: 1
       events_when_completed: scoop_eject
  timer_meteortimer_started:
     meteor:
       manual_advance: true
       priority: 901
     scoopEscapeShow:
       speed: 1
       priority: 950
  timer_meteortimer_tick:
     meteor:
       action: advance
  timer_meteortimer_tick{ticks_remaining > 24}:
     meteor_scoop:
       speed: 1
       loops: -1
       priority: 950
  timer_meteortimer_tick{ticks_remaining > 18 and ticks_remaining <= 24}:
     meteor_scoop:
       speed: 2
       loops: -1
       priority: 950
  timer_meteortimer_tick{ticks_remaining > 12 and ticks_remaining <= 18}:
     meteor_scoop:
       speed: 4
       loops: -1
       priority: 950
  timer_meteortimer_tick{ticks_remaining > 6 and ticks_remaining <= 12}:
     meteor_scoop:
       speed: 8
       loops: -1
       priority: 950
  timer_meteortimer_tick{ticks_remaining <= 6}:
     meteor_scoop:
       speed: 16
       loops: -1
       priority: 950

# BELOW are the "base" show player entries
#  story_is_about_to_begin:
#     story_04_intro:
#       events_when_completed: story_intro_complete
#       loops: 0
  story_is_about_to_fail:
     story_04_outro_fail:
       events_when_completed: story_outro_fail_complete
       loops: 0
  story_is_about_to_end:
     story_04_outro:
       events_when_completed: story_outro_complete
       loops: 0

timers:
   meteortimer:
     max_value: 30
     start_value: 30
     end_value: 0
     tick_interval: 1s
     direction: down
     start_running: no
     control_events:
      - event: shotScoopMeteor_hit
        action: add
        value: 30
      - event: shotScoopMeteor_hit
        action: pause
        value: 2
      - event: shotScoopMeteor_hit
        action: change_tick_interval
        value: 0.9
      - event: story_intro_complete
        action: start
      - event: global_timer_pause
        action: pause
      - event: global_timer_unpause
        action: start

sound_player:
    mode_story04_started:
      overture:
          action: stop
          fade_out: 0
    mode_04_end_video:
      hotandheavy:
          action: play
          loops: -1
          mode_end_action: stop
    play_explosion: explosions

