#config_version=5

# *************** METEOR STRIKE ******************
# A red light show of doooooooom will slowly descend upon the player.
# Hit the scoop to escape the meteor before the light show gets to the end
# Award score, restart show.  Mode ends on loss of ball or meteor strike on player (end of show)

mode:
   start_events: selector_untitled_mode_4_selected
   stop_events: story_is_completed
   priority: 400
   file_log: full

# All Story Modes --
#     Issue a scoop_eject after any introduction activities
# Modes that end with a Scoop Hit --
#     Issue a scoop eject after any outro-activities

# Success/Failure
# By default, success = not losing ball, failure = losing ball
# If your mode has a different ruleset, change when the events
# story_is_completed_successful / acheivement_story##_successful
# story_is_completed_unsuccessful / acheivement_story##_unsuccessful
# are issued.

event_player:
   mode_story04_started:
     - story_is_about_to_begin
   story_intro_complete:
     - scoop_eject
   timer_meteorTimer_complete:
     - story_is_about_to_end
   story_outro_complete:
     - story_is_completed_successful
     - acheivement_story04_successful
#    Only used when scoop hits end the mode
#    - scoop_eject
   ball_ending:
     - story_is_completed_unsuccessful
     - acheivement_story04_unsuccessful
   story_is_completed_successful:
    - story_is_completed
   story_is_completed_unsuccessful:
    - story_is_completed

#  Base intro / outro shows

# *** BASE show_player items have been moved into previously existing mode-specific items
#show_player:
#   story_is_about_to_begin:
#      story_04_intro:
#         events_when_advanced: story_intro_complete
#         events_when_completed: story_intro_complete
#         events_when_stopped: story_intro_complete
#         loops: 0
#   story_is_about_to_end:
#      story_04_outro:
#         events_when_advanced: story_outro_complete
#         events_when_completed: story_outro_complete
#         events_when_stopped: story_outro_complete
#         loops: 0

# These shows/slides are just placeholders.
# Put any intro/outro shows you want here, just make sure
# they start on events story_04_intro and story_04_outro

shows:
   story_04_intro:
     - time: 0
       slides: story_04_intro_slide
       duration: 3
   story_04_outro:
     - time: 0
       slides: story_04_outro_slide
       duration: 3

slides:
   story_04_intro_slide:
    widgets:
      - type: text
        text: STORY 04 BEGIN SHOW
        color: red
        font_size: 100
        font_name: ocr-a-tribute-bold
   story_04_outro_slide:
    widgets:
      - type: text
        text: STORY 04 END SHOW
        color: red
        font_size: 100
        font_name: ocr-a-tribute-bold

# The below is mode specific data

# EVENTS starting on mode_story04_started have been moved to story_intro_complete

variable_player:
  story_intro_complete:
    meteor_accum:
       int: 0
       action: set
    meteor_hits:
       int: 0
       action: set
    timeRemain:
       int: 30
       action: set
  timer_meteorTimer_started:
    timeRemain:
       int: (ticks_remaining)
       action: set
  shotScoopMeteor_hit:
    meteor_hits: 1
    score: 1000 * current_player.timeRemain
    meteor_accum: 1000 * current_player.timeRemain
    bonuscount: 3
  timer_meteorTimer_tick:
     timeRemain:
       int: (ticks_remaining)
       action: set

shots:
  shotScoopMeteor:
    switch: s_ir_scoop_detect
    profile: shotScoopMeteorProfile

shot_profiles:
  shotScoopMeteorProfile:
    show_when_disabled: true
    advance_on_hit: false
    block: true
    states:
      - name: scoopActive
        show: popgreen

show_player:
  shotScoopMeteor_hit:
     pinwheel:
       speed: 40
       loops: 1
       events_when_completed: scoop_eject
  timer_meteortimer_started:
     meteor:
       manual_advance: true
       priority: 401
     scoopEscapeShow:
       speed: 1
       priority: 450
  timer_meteortimer_tick:
     meteor:
       action: advance
  timer_meteortimer_tick{ticks_remaining > 24}:
     meteor_scoop:
       speed: 4
       loops: -1
       priority: 450
#       show_tokens:
#         rate: 250
  timer_meteortimer_tick{ticks_remaining > 18 and ticks_remaining <= 24}:
     meteor_scoop:
       speed: 8
       loops: -1
       priority: 450
#       show_tokens:
#         rate: 125
  timer_meteortimer_tick{ticks_remaining > 12 and ticks_remaining <= 18}:
     meteor_scoop:
       speed: 16
       loops: -1
       priority: 450
#       show_tokens:
#         rate: 62
  timer_meteortimer_tick{ticks_remaining > 6 and ticks_remaining <= 12}:
     meteor_scoop:
       speed: 32
       loops: -1
       priority: 450
#       show_tokens:
#         rate: 31
  timer_meteortimer_tick{ticks_remaining <= 6}:
     meteor_scoop:
       speed: 64
       loops: -1
       priority: 450
#       show_tokens:
#         rate: 15

# BELOW are the "base" show player entries
  story_is_about_to_begin:
     story_04_intro:
       events_when_advanced: story_intro_complete
       events_when_completed: story_intro_complete
       events_when_stopped: story_intro_complete
       loops: 0
  story_is_about_to_end:
     story_04_outro:
       events_when_advanced: story_outro_complete
       events_when_completed: story_outro_complete
       events_when_stopped: story_outro_complete
       loops: 0

timers:
   meteorTimer:
     max_value: 30
     start_value: 30
     end_value: 0
     tick_interval: 1s
     direction: down
     start_running: no
     control_events:
      - event: shotScoopMeteor_hit
        action: add
        value: 30
      - event: shotScoopMeteor_hit
        action: pause
        value: 2
      - event: shotScoopMeteor_hit
        action: change_tick_interval
        value: 0.1
      - event: story_intro_complete
        action: start

widget_player:
   story_intro_complete:
      yt_remain_widget_04:
         slide: scoring_slide
   story04_ended:
      yt_remain_widget_04:
         action: remove

widgets:
   yt_remain_widget_04:
     - type: text
       text: "Meteor Time: (timeRemain)s  Meteor Score: (meteor_accum)"
       y: 80%

