#config_version=5

high_score:
  enter_initials_timeout: 60s
  award_slide_display_time: 7s
  _overwrite: True
  categories: !!omap
  - score:
      - GRAND CHAMPION
      - 1ST
      - 2ND
      - 3RD
      - 4TH
      - 5TH
  - modestat_1_highest_scoring:
      - Locate The Cygnus Champion
      - Locate The Cygnus 2nd Best
      - Locate The Cygnus 3rd Best
      - Locate The Cygnus 4th Best
      - Locate The Cygnus 5th Best
  - modestat_2_highest_scoring:
      - Escape The Black Hole Champion
      - Escape The Black Hole 2nd Best
      - Escape The Black Hole 3rd Best
      - Escape The Black Hole 4th Best
      - Escape The Black Hole 5th Best
  - modestat_3_highest_scoring:
      - Shooting Gallery Champion
      - Shooting Gallery 2nd Best
      - Shooting Gallery 3rd Best
      - Shooting Gallery 4th Best
      - Shooting Gallery 5th Best
  - modestat_4_highest_scoring:
      - Meteor Strike Champion
      - Meteor Strike 2nd Best
      - Meteor Strike 3rd Best
      - Meteor Strike 4th Best
      - Meteor Strike 5th Best
  - modestat_5_highest_scoring:
      - Corridor Battle Champion
      - Corridor Battle 2nd Best
      - Corridor Battle 3rd Best
      - Corridor Battle 4th Best
      - Corridor Battle 5th Best
  - modestat_6_highest_scoring:
      - David Vs. Golliath Champion
      - David Vs. Golliath 2nd Best
      - David Vs. Golliath 3rd Best
      - David Vs. Golliath 4th Best
      - David Vs. Golliath 5th Best
  - modestat_7_highest_scoring:
      - In, Through, and Beyond! Champion
      - In, Through, and Beyond! 2nd Best
      - In, Through, and Beyond! 3rd Best
      - In, Through, and Beyond! 4th Best
      - In, Through, and Beyond! 5th Best
  defaults:
     score:
       - OLH: 100000000
       - BOB: 80000000
       - KAH: 60000000
       - ECH: 40000000
       - TLL: 20000000
       - ANT: 10000000
     modestat_1_highest_scoring:
       - OLH: 2000000
       - BOB: 1000000
       - KAH: 500000
       - ECH: 250000
       - ANT: 100000
     modestat_2_highest_scoring:
       - OLH: 2000000
       - BOB: 1000000
       - KAH: 500000
       - ECH: 250000
       - ANT: 100000
     modestat_3_highest_scoring:
       - OLH: 2000000
       - BOB: 1000000
       - KAH: 500000
       - ECH: 250000
       - ANT: 100000
     modestat_4_highest_scoring:
       - OLH: 2000000
       - BOB: 1000000
       - KAH: 500000
       - ECH: 250000
       - ANT: 100000
     modestat_5_highest_scoring:
       - OLH: 2000000
       - BOB: 1000000
       - KAH: 500000
       - ECH: 250000
       - ANT: 100000
     modestat_6_highest_scoring:
       - OLH: 2000000
       - BOB: 1000000
       - KAH: 500000
       - ECH: 250000
       - ANT: 100000
     modestat_7_highest_scoring:
       - TLL: 10000000
       - TLL: 8000000
       - TLL: 6000000
       - TLL: 4000000
       - TLL: 2000000


widgets:
   name_reg:
    - type: text
      text: CONGRATULATIONS!
      style: text_default
      anchor_y: bottom
      y: bottom+150
      font_size: 90
      font_name: ocr-a-tribute-bold
      color: ff330f
      z: 1


#widget_player:
#  high_score_award_display:
#    name_reg:
#      action: add
#      slide: high_score_enter_initials_ov

slide_player:
  _overwrite: true
  high_score_enter_initials: high_score_enter_initials_ov
  high_score_award_display: high_score_congrats
#  high_score_award_display:
#    high_score_award_display_ov:
#        action: play
#    high_score_enter_initials_ov:
#        action: remove

slides:
  high_score_congrats:
  - type: image
    image: starfield
    z: 0
    opacity: 0.7
  - type: text
    text: (award)
    style: text_default
    anchor_x: center
    anchor_y: center
    y: 70%
    font_size: 70
    font_name: ocr-a-tribute-bold
    z: 1
  - type: text
    text: (value)
    style: text_default
    anchor_x: center
    anchor_y: center
    y: 55%
    font_size: 70
    font_name: ocr-a-tribute-bold
    z: 1
    number_grouping: true
  - type: text
    text: PLAYER (player_name)
    style: text_default
    anchor_x: center
    anchor_y: center
    y: 85%
    font_size: 70
    font_name: ocr-a-tribute-bold
    color: ff330f
    z: 1
  - type: text
    text: CONGRATULATIONS!
    style: text_default
    anchor_y: bottom
    y: bottom+150
    font_size: 90
    font_name: ocr-a-tribute-bold
    color: ff330f
    z: 1

  high_score_enter_initials_ov:
  - type: image
    image: starfield
    z: 0
    opacity: 0.7
  - type: text
    text: PLAYER (player_num)
    style: text_default
    anchor_x: center
    anchor_y: center
    y: 85%
    font_size: 70
    font_name: ocr-a-tribute-bold
    color: ff330f
    z: 1
  - type: text
    text: (award)
    style: text_default
    anchor_x: center
    anchor_y: center
    y: 70%
    font_size: 70
    font_name: ocr-a-tribute-bold
    z: 1
  - type: text
    text: (value)
    style: text_default
    anchor_x: center
    anchor_y: center
    y: 55%
    font_size: 70
    font_name: ocr-a-tribute-bold
    z: 1
    number_grouping: true
  - type: text_input
    initial_char: A
    dynamic_x: false
    key: high_score
    style: text_default
    anchor_y: bottom
    max_chars: 3
    y: bottom+300
    font_size: 70
    font_name: ocr-a-tribute-bold
    color: ff330f
    shift_right_event: s_flipper_right_active
    shift_left_event: s_flipper_left_active
    select_event: s_start_active
    z: 1
    animations:
      show_slide:
      - property: opacity
        value: 1
        duration: 0.3s
        easing: in_out_quint
      - property: opacity
        value: 0
        duration: 0.3s
        repeat: true
        easing: in_out_quint
      high_score_award_display:
      - property: opacity
        value: 0
        duration: 0ms
  - type: text
    text: ""
    key: high_score
    style: text_default
    anchor_y: bottom
    y: bottom+200
    font_size: 70
    font_name: ocr-a-tribute-bold
    color: ff330f
    z: 1
