#config_version=5

high_score:
  enter_initials_timeout: 60s
  award_slide_display_time: 10s
  _overwrite: True
  categories: !!omap
  - score:
      - GRAND CHAMPION
      - 1ST
      - 2ND
      - 3RD
      - 4TH
      - 5TH
  - meteors:
      - METEOR CHAMP
  - beyond:
      - EXPLORER OF THE BEYOND
  defaults:
     score:
       - KAYDEN: 600
       - KAT: 500
       - JOE: 400
       - BOB: 300
       - ATP: 200
       - MAX: 10
     meteors:
       - OLH: 75
     beyond:
       - KAH: 152

slide_player:
  _overwrite: true
  high_score_enter_initials: high_score_enter_initials_ov
  high_score_award_display:
    high_score_award_display_ov:
        action: play
    high_score_enter_initials_ov:
        action: remove

slides:
  high_score_enter_initials_ov:
  - type: text
    text: PLAYER (player_num)
    style: text_default
    anchor_y: bottom
    x: center-27
    y: bottom+610
    font_size: 110
    font_name: ocr-a-tribute-bold
    color: ff330f
  - type: text
    text: (award)
    style: text_default
    anchor_y: bottom
    x: center-27
    y: bottom+500
    font_size: 110
    font_name: ocr-a-tribute-bold
  - type: text_input
    key: high_score
    style: text_default
    anchor_y: bottom
    max_chars: 3
    y: bottom+400
    font_size: 90
    font_name: ocr-a-tribute-bold
    color: ff330f
    animations:
      show_slide:
      - property: opacity
        value: 1
        duration: 0.3s
        easing: in_out_quint
      - property: opacity
        value: 0
        duration: 0.3s
        repeat: true
        easing: in_out_quint

  - type: text
    text: ""
    key: high_score
    anchor_x: left
    x: left+90
    style: text_default
  grand champion_award_display:
  - type: text
    text: YOU TOTALLY DO NOT SUCK
    color: red
    y: top-55
    anchor_y: top
    font_size: 50
  high_score_award_display_ov:
  - type: text
    text: YOUR NAME IS REGISTERED
    color: red
    y: top-5
    anchor_y: top
    font_size: 50

