#config_version=5

widgets:
   mode_title_display_box:
     - type: image
       image: mode_title_display_box
       anchor_x: left
       anchor_y: top
       x: 171
       y: 769
       z: 60
     - type: text
       text: 888888888888888888888888888888888888
       style:
          - infoboard_line_1_background
     - type: text
       text: KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
       style:
          - infoboard_line_1_background
     - type: text
       text: NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
       style:
          - infoboard_line_1_background
     - type: text
       text: VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
       style:
          - infoboard_line_1_background
     - type: text
       text: (infoboard_line_1_text)
       style:
          - infoboard_line_1_data
     - type: text
       text: 888888888888888888888888888888888888
       style:
          - infoboard_line_2_background
     - type: text
       text: KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
       style:
          - infoboard_line_2_background
     - type: text
       text: NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
       style:
          - infoboard_line_2_background
     - type: text
       text: VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
       style:
          - infoboard_line_2_background
     - type: text
       text: (infoboard_line_2_text)
       style:
          - infoboard_line_2_data
     - type: text
       text: 888888888888888888888888888888888888
       style:
          - infoboard_line_3_background
     - type: text
       text: KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
       style:
          - infoboard_line_3_background
     - type: text
       text: NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
       style:
          - infoboard_line_3_background
     - type: text
       text: VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
       style:
          - infoboard_line_3_background
     - type: text
       text: (infoboard_line_3_text)
       style:
          - infoboard_line_3_data

   mode_high_score_display_add:
     - type: Text
       text: "8888888888"
       style:
           - high_score_mode_style_bak
           - hs_pos_6_score
     - type: Text
       text: " ,   ,   ,   "
       style:
           - high_score_mode_style_bak
           - hs_pos_6_score
     - type: Text
       text: "888"
       style:
           - high_score_mode_style_bak
           - hs_pos_6
     - type: Text
       text: "KKK"
       style:
           - high_score_mode_style_bak
           - hs_pos_6
     - type: Text
       text: "NNN"
       style:
           - high_score_mode_style_bak
           - hs_pos_6
     - type: Text
       text: "VVV"
       style:
           - high_score_mode_style_bak
           - hs_pos_6

   mode_high_score_display:
     - type: image
       image: tbh-slide-template
       z: 0
     - type: Text
       text: "8888888888"
       style:
           - high_score_mode_style_bak
           - hs_pos_1_score
     - type: Text
       text: "8888888888"
       style:
           - high_score_mode_style_bak
           - hs_pos_2_score
     - type: Text
       text: "8888888888"
       style:
           - high_score_mode_style_bak
           - hs_pos_3_score
     - type: Text
       text: "8888888888"
       style:
           - high_score_mode_style_bak
           - hs_pos_4_score
     - type: Text
       text: "8888888888"
       style:
           - high_score_mode_style_bak
           - hs_pos_5_score
     - type: Text
       text: " ,   ,   ,   "
       style:
           - high_score_mode_style_bak
           - hs_pos_1_score
     - type: Text
       text: " ,   ,   ,   "
       style:
           - high_score_mode_style_bak
           - hs_pos_2_score
     - type: Text
       text: " ,   ,   ,   "
       style:
           - high_score_mode_style_bak
           - hs_pos_3_score
     - type: Text
       text: " ,   ,   ,   "
       style:
           - high_score_mode_style_bak
           - hs_pos_4_score
     - type: Text
       text: " ,   ,   ,   "
       style:
           - high_score_mode_style_bak
           - hs_pos_5_score

     - type: Text
       text: "888"
       style:
           - high_score_mode_style_bak
           - hs_pos_1
     - type: Text
       text: "888"
       style:
           - high_score_mode_style_bak
           - hs_pos_2
     - type: Text
       text: "888"
       style:
           - high_score_mode_style_bak
           - hs_pos_3
     - type: Text
       text: "888"
       style:
           - high_score_mode_style_bak
           - hs_pos_4
     - type: Text
       text: "888"
       style:
           - high_score_mode_style_bak
           - hs_pos_5
     - type: Text
       text: "KKK"
       style:
           - high_score_mode_style_bak
           - hs_pos_1
     - type: Text
       text: "KKK"
       style:
           - high_score_mode_style_bak
           - hs_pos_2
     - type: Text
       text: "KKK"
       style:
           - high_score_mode_style_bak
           - hs_pos_3
     - type: Text
       text: "KKK"
       style:
           - high_score_mode_style_bak
           - hs_pos_4
     - type: Text
       text: "KKK"
       style:
           - high_score_mode_style_bak
           - hs_pos_5
     - type: Text
       text: "NNN"
       style:
           - high_score_mode_style_bak
           - hs_pos_1
     - type: Text
       text: "NNN"
       style:
           - high_score_mode_style_bak
           - hs_pos_2
     - type: Text
       text: "NNN"
       style:
           - high_score_mode_style_bak
           - hs_pos_3
     - type: Text
       text: "NNN"
       style:
           - high_score_mode_style_bak
           - hs_pos_4
     - type: Text
       text: "NNN"
       style:
           - high_score_mode_style_bak
           - hs_pos_5
     - type: Text
       text: "VVV"
       style:
           - high_score_mode_style_bak
           - hs_pos_1
     - type: Text
       text: "VVV"
       style:
           - high_score_mode_style_bak
           - hs_pos_2
     - type: Text
       text: "VVV"
       style:
           - high_score_mode_style_bak
           - hs_pos_3
     - type: Text
       text: "VVV"
       style:
           - high_score_mode_style_bak
           - hs_pos_4
     - type: Text
       text: "VVV"
       style:
           - high_score_mode_style_bak
           - hs_pos_5
