#config_version=5

widgets:
   mode_title_display_box:
     - type: image
       image: mode_title_display_box
       anchor_x: left
       anchor_y: top
       x: 169
       y: 769
       z: 60
     - type: text
       text: 888888888888888888888888888888
       style:
          - infoboard_line_1_background
     - type: text
       text: KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
       style:
          - infoboard_line_1_background
     - type: text
       text: NNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
       style:
          - infoboard_line_1_background
     - type: text
       text: VVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
       style:
          - infoboard_line_1_background
     - type: text
       text: (infoboard_line_1_text)
       style:
          - infoboard_line_1_data
     - type: text
       text: 888888888888888888888888888888
       style:
          - infoboard_line_2_background
     - type: text
       text: KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
       style:
          - infoboard_line_2_background
     - type: text
       text: NNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
       style:
          - infoboard_line_2_background
     - type: text
       text: VVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
       style:
          - infoboard_line_2_background
     - type: text
       text: (infoboard_line_2_text)
       style:
          - infoboard_line_2_data
     - type: text
       text: 888888888888888888888888888888
       style:
          - infoboard_line_3_background
     - type: text
       text: KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
       style:
          - infoboard_line_3_background
     - type: text
       text: NNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
       style:
          - infoboard_line_3_background
     - type: text
       text: VVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
       style:
          - infoboard_line_3_background
     - type: text
       text: (infoboard_line_3_text)
       style:
          - infoboard_line_3_data