#config_version=5

show_player:
  mode_attract_started:
    giWhite: #Sets basic GI white lighting as the default
      priority: 5
      loops: -1
    dummy_show: #just to get us past the initial mode start and into our event loop
      loops: 0
      events_when_completed: attract_01
  attract_01:
    field_off:
      priority: 6
    mode_cycle:
      loops: -1
      speed: 1
      priority: 7
    bonus_cycle:
      loops: -1
      speed: 1
      priority: 7
    big_bonus_cycle:
      loops: -1
      speed: 1
      priority: 7
    pop_cycle:
      loops: -1
      speed: 1
      priority: 7
    lane_cycle:
      loops: -1
      speed: 1
      priority: 7
    drop_cycle:
      loops: -1
      speed: 1
      priority: 7
    mult_cycle:
      loops: -1
      speed: 1
      priority: 7
    special_cycle:
      loops: -1
      speed: 1
      priority: 7
    scoop_ready_show:
      loops: -1
      speed: 1
      priority: 7
    extra_ball_cycle:
      loops: -1
      speed: 1
      priority: 7
    text_loop:
      loops: 0
      events_when_completed: attract_02
  attract_02:
    purple_swirl:
       speed: 1
       loops: 6
       priority: 8
    big_title:
      loops: 0
      events_when_completed: attract_03
  attract_03:
    giDim:
      priority: 9
      loops: 89
    field_off:
      priority: 9
      loops: 89
    video_play:
      loops: 0
      events_when_completed: attract_01
  green_ttb:
    green_stripes_ttb:
      speed: 30
      loops: 11
      priority: 10
  green_btt:
    green_stripes_btt:
      speed: 30
      loops: 8
      priority: 10
  green_rtl:
    green_stripes_rtl:
      speed: 30
      loops: 8
      priority: 10
  green_ttb_2:
    green_stripes_ttb:
      speed: 30
      loops: 8
      priority: 10
  green_x_rtl:
    green_xs_rtl:
      speed: 30
      loops: 24
      priority: 10
  green_circ:
    green_cir_ito:
      speed: 30
      loops: 3
      priority: 10

event_player:
  attract_03: #All events have had +5s added to account for the title slide
    - green_ttb|22s
    - green_btt|34s
    - green_rtl|43s
    - green_ttb_2|51s
    - green_x_rtl|60s
    - green_circ|85s

widget_player:
  lastgame_player2:
    player_2_score_widget:
      slide: lastgame
  lastgame_player3:
    player_3_score_widget:
      slide: lastgame
  lastgame_player4:
    player_4_score_widget:
      slide: lastgame

widgets:
  player_2_score_widget:
    - type: Text
      text: Player 2 - (score)
      font_name: ocr-a-tribute-bold
      font_size: 50
      number_grouping: true
      color: FF2C1F
      y: 480
      x: 700
      z: 1
      anchor_y: top
      anchor_x: center
  player_3_score_widget:
    - type: Text
      text: Player 3 - (score)
      font_name: ocr-a-tribute-bold
      font_size: 50
      number_grouping: true
      color: FF2C1F
      y: 420
      x: 700
      z: 1
      anchor_y: top
      anchor_x: center
  player_4_score_widget:
    - type: Text
      text: Player 4 - (score)
      font_name: ocr-a-tribute-bold
      font_size: 50
      number_grouping: true
      color: FF2C1F
      y: 360
      x: 700
      z: 1
      anchor_y: top
      anchor_x: center

#  mode_attract_started: attract_display_loop
#
#  mode_attract_started.1:
#     pinwheel:
#       speed: 20
#       loops: 3
#       events_when_completed: attract_next_01
##    attract_light_show:
##      speed: 10
##    giWhite:
##      speed: 1
##    attractDrops:
##      speed: 10
##    attractBonusX:
##      speed: 5
#  attract_next_01:
#     sample_wired_loop:
#       speed: 5
#       loops: 3
#       events_when_completed: attract_next_02
#  attract_next_02:
#     swirl:
#       speed: 15
#       loops: 1
#       events_when_completed: attract_next_03
#  attract_next_03:
#    swirl2:
#       speed: 10
#       loops: 3
#       events_when_completed: attract_next_04
#  attract_next_04:
#     pinwheel:
#       speed: 20
#       loops: 3
#       events_when_completed: attract_next_01
