#config_version=5

show_player:
  mode_attract_started: attract_display_loop
  mode_attract_started.1:
     sample_wired_loop:
       speed: 1
#    attract_light_show:
#      speed: 10
#    giWhite:
#      speed: 1
#    attractDrops:
#      speed: 10
#    attractBonusX:
#      speed: 5