#config_version=5

show_player:
  mode_attract_started:
    giWhite: #Sets basic GI white lighting as the default, plays forever
      priority: 5
      loops: -1
    dummy_show: #just to get us past the initial mode start and into our event loop
      loops: 0
      events_when_completed: attract_01
  attract_01:
    field_off:
      priority: 6
    mode_cycle:
      loops: -1
      speed: 1
      priority: 7
    bonus_cycle:
      loops: -1
      speed: 1
      priority: 7
    big_bonus_cycle:
      loops: -1
      speed: 1
      priority: 7
    pop_cycle:
      loops: -1
      speed: 1
      priority: 7
    lane_cycle:
      loops: -1
      speed: 1
      priority: 7
    drop_cycle:
      loops: -1
      speed: 1
      priority: 7
    mult_cycle:
      loops: -1
      speed: 1
      priority: 7
    special_cycle:
      loops: -1
      speed: 1
      priority: 7
    scoop_cycle:
      loops: -1
      speed: 1
      priority: 7
    extra_ball_cycle:
      loops: -1
      speed: 1
      priority: 7
    text_loop:
      loops: 0
#      events_when_completed: attract_02
      events_when_completed: text_loop_finished
  attract_02:
    purple_swirl:
       speed: 1
       loops: 6
       priority: 8
    big_title:
      loops: 0
      events_when_completed: attract_03
  attract_03:
    giDim:
      priority: 9
      loops: 22
    field_off:
      priority: 9
      loops: 89
    video_play:
      loops: 0
      events_when_played: trigger_text
      events_when_completed: attract_01
  green_ttb:
    green_stripes_ttb:
      speed: 30
      loops: 11
      priority: 10
    gi_off:
      speed: 1
      loops: 68
      priority: 9
  green_btt:
    green_stripes_btt:
      speed: 30
      loops: 8
      priority: 10
  green_rtl:
    green_stripes_rtl:
      speed: 30
      loops: 8
      priority: 10
  green_ttb_2:
    green_stripes_ttb:
      speed: 30
      loops: 8
      priority: 10
  green_x_rtl:
    green_xs_rtl:
      speed: 30
      loops: 24
      priority: 10
  green_circ:
    green_cir_ito:
      speed: 30
      loops: 3
      priority: 10
  hs_mode_1:
    hs_1:
      loops: 0
      events_when_completed: attract_02
  hs_mode_2:
    hs_2:
      loops: 0
      events_when_completed: attract_02
  hs_mode_3:
    hs_3:
      loops: 0
      events_when_completed: attract_02
  hs_mode_4:
    hs_4:
      loops: 0
      events_when_completed: attract_02
  hs_mode_5:
    hs_5:
      loops: 0
      events_when_completed: attract_02
  hs_mode_6:
    hs_6:
      loops: 0
      events_when_completed: attract_02
  hs_mode_7:
    hs_7:
      loops: 0
      events_when_completed: attract_02

random_event_player:
  text_loop_finished:
   scope: machine
   force_all: true
   events:
    - hs_mode_1
    - hs_mode_2
    - hs_mode_3
    - hs_mode_4
    - hs_mode_5
    - hs_mode_6
    - hs_mode_7

event_player:
  attract_03: #All events have had +5s added to account for the title slide
    - green_ttb|22s
    - green_btt|34s
    - green_rtl|43s
    - green_ttb_2|51s
    - green_x_rtl|60s
    - green_circ|85s
#  trigger_text:
  slide_video_active:
     set_text_to_cycle|17.15s:
       text: "THE PINBALL EXPERIENCE"
       delay: 45
       varname: "thePinExp"
       intermed: "*"
     set_text_to_cycle|23.27s:
       text: "s6"
       delay: 45
       varname: "s6"
       intermed: "*"
     set_text_to_cycle|27.29s:
       text: "s5"
       delay: 45
       varname: "s5"
       intermed: "*"
     set_text_to_cycle|30.96s:
       text: "s4"
       delay: 45
       varname: "s4"
       intermed: "*"
     set_text_to_cycle|34.40s:
       text: "s3"
       delay: 45
       varname: "s3"
       intermed: "*"
     set_text_to_cycle|38.67s:
       text: "s2"
       delay: 45
       varname: "s2"
       intermed: "*"
     set_text_to_cycle|43.46s:
       text: "s1"
       delay: 45
       varname: "s1"
       intermed: "*"

widget_player:
  #Add "press start" and "freeplay" widgets to slides as they load
  slide_ok_productions_created:
    freeplay_start_widget:
      slide: ok_productions
  slide_title_created:
    freeplay_start_widget:
      slide: title
  slide_lastgame_created:
    freeplay_start_widget:
      slide: lastgame
  slide_praise1_created:
    freeplay_start_widget:
      slide: praise1
  slide_praise2_created:
    freeplay_start_widget:
      slide: praise2
  slide_high_scores_created:
    freeplay_start_widget:
      slide: high_scores
  slide_video_created:
    freeplay_start_widget:
      slide: video


  #Add player scores to last game slide, as relevant
  lastgame_player2:
    player_2_score_widget:
      slide: lastgame
  lastgame_player3:
    player_3_score_widget:
      slide: lastgame
  lastgame_player4:
    player_4_score_widget:
      slide: lastgame

widgets:
  player_2_score_widget:
    - type: text
      font_size: 80
      y: 43.4%
      x: 10%
      z: 10
      anchor_x: left
      anchor_y: bottom
      color: BBD8F0
      font_name: ocr-a-tribute-bold
      text: PLAYER 2
    - type: text
      font_size: 80
      y: 43.4%
      x: 90%
      z: 10
      anchor_x: right
      anchor_y: bottom
      color: FF2C1F
      font_name: ocr-a-tribute-bold
      text: (score)
      number_grouping: true
      min_digits: 2
  player_3_score_widget:
    - type: text
      font_size: 80
      y: 26.7%
      x: 10%
      z: 10
      anchor_x: left
      anchor_y: bottom
      color: BBD8F0
      font_name: ocr-a-tribute-bold
      text: PLAYER 3
    - type: text
      font_size: 80
      y: 26.7%
      x: 90%
      z: 10
      anchor_x: right
      anchor_y: bottom
      color: FF2C1F
      font_name: ocr-a-tribute-bold
      text: (score)
      number_grouping: true
      min_digits: 2
  player_4_score_widget:
    - type: text
      font_size: 80
      y: 10%
      x: 10%
      z: 10
      anchor_x: left
      anchor_y: bottom
      color: BBD8F0
      font_name: ocr-a-tribute-bold
      text: PLAYER 4
    - type: text
      font_size: 80
      y: 10%
      x: 90%
      z: 10
      anchor_x: right
      anchor_y: bottom
      color: FF2C1F
      font_name: ocr-a-tribute-bold
      text: (score)
      number_grouping: true
      min_digits: 2
  freeplay_start_widget:
    - type: Text
      text: PRESS START
      font_name: ocr-a-tribute-bold
      y: 10
      x: 10
      z: 1
      anchor_y: bottom
      anchor_x: left
      animations:
        add_to_slide:
          - property: opacity
            value: 0
            duration: .5s
          - property: opacity
            value: 1
            duration: .5s
            repeat: true
    - type: Text
      text: FREE PLAY
      font_name: ocr-a-tribute-bold
      color: green
      y: 10
      x: 1355
      z: 1
      anchor_y: bottom
      anchor_x: right
      animations:
        add_to_slide:
          - property: opacity
            value: 0
            duration: .5s
          - property: opacity
            value: 1
            duration: .5s
            repeat: true

slides:
  lastgame:
    transition:
      type: fade
      duration: 1s
    widgets:
    - type: image
      image: starfield
      opacity: .7
      z: 0
    - type: text
      font_size: 100
      y: 90%
      z: 10
      anchor_y: top
      color: FF2C1F
      font_name: ocr-a-tribute-bold
      text: LAST GAME
    - type: text
      font_size: 80
      y: 60.1%
      x: 10%
      z: 10
      anchor_x: left
      anchor_y: bottom
      color: BBD8F0
      font_name: ocr-a-tribute-bold
      text: PLAYER 1
    - type: text
      font_size: 80
      y: 60.1%
      x: 90%
      z: 10
      anchor_x: right
      anchor_y: bottom
      color: FF2C1F
      font_name: ocr-a-tribute-bold
      text: (machine|player1_score)
      number_grouping: true
      min_digits: 2
  ok_productions:
    transition:
      type: fade
      duration: 1s
    widgets:
    - type: image
      image: starfield
      opacity: .7
      z: 0
    - type: Text
      text: "OUTPOST KODELIA STUDIOS\n\nPRESENTS"
      z: 1
      font_name: ocr-a-tribute-bold
      font_size: 50
      color: FF2C1F
      opacity: 0
      animations:
        show_slide:
          - property: opacity
            value: 1
            duration: 1s
          - property: opacity
            value: 1
            duration: 3s
          - property: opacity
            value: 0
            duration: 1s
  title:
    transition:
      type: fade
      duration: 1s
    widgets:
    - type: image
      image: starfield
      opacity: .7
      z: 0
    - type: Text
      text: THE BLACK HOLE
      font_name: ocr-a-tribute-bold
      font_size: 72
      color: FF2C1F
      opacity: 0
      y: center + 40
      z: 1
      anchor_y: center
      anchor_x: center
      animations:
        show_slide:
          - property: opacity
            value: 1
            duration: 1s
          - property: opacity
            value: 1
            duration: 5s
          - property: opacity
            value: 0
            duration: 1s
    - type: Text
      text: THE PINBALL EXPERIENCE
      font_name: ocr-a-tribute-bold
      font_size: 36
      color: FF2C1F
      opacity: 0
      y: center - 40
      z: 1
      anchor_y: center
      anchor_x: center
      animations:
        show_slide:
          - property: opacity
            value: 0
            duration: 2s
          - property: opacity
            value: 1
            duration: 1s
          - property: opacity
            value: 1
            duration: 3s
          - property: opacity
            value: 0
            duration: 1s