#config_version=5

event_player:
   story_is_about_to_begin:
     - mode_05_setintro_01|2s
     - mode_05_setintro_02|2s
     - mode_05_setintro_03|2s
     - mode_05_start_video
     # 14.792s
     - mode_05_end_video|15.5s
     - scoop_eject_sequence|9.5s
     - story_intro_complete|12.5s
   mode_05_setintro_01:
     set_infoboard_line_text:
        linenbr: 1
        text: "CORRIDOR BATTLE"
        pts: none
        secs: none
        cycle: "star"
        delayms: 25
   mode_05_setintro_02:
     set_infoboard_line_text:
        linenbr: 2
        text: "DESTROY LIT ROBOTS IN 30 SECONDS"
        pts: none
        secs: none
        cycle: "star"
        delayms: 25
   mode_05_setintro_03:
     set_infoboard_line_text:
        linenbr: 3
        text: "ROBOT HITS AWARD ADDITIONAL TIME"
        pts: none
        secs: none
        cycle: "star"
        delayms: 25
   story_intro_complete:
     - mode_05_setinfo_01
     - mode_05_setinfo_02
     - mode_05_setinfo_03
   mode_05_setinfo_01:
     set_infoboard_line_text:
        linenbr: 1
        text: "CORRIDOR BATTLE"
        pts: modestat_5_scoring
        secs: none
        cycle: "instant"
        delayms: 0
   mode_05_setinfo_02:
     set_infoboard_line_text:
        linenbr: 2
        text: "ROBOTS DESTROYED"
        pts: corridor_targets_hit
        secs: none
        cycle: "instant"
        delayms: 0
   mode_05_setinfo_03:
     set_infoboard_line_text:
        linenbr: 3
        text: "TIME REMAINING"
        pts: none
        secs: corridor_seconds
        cycle: "instant"
        delayms: 0
   player_modestat_5_scoring:
     set_infoboard_line_text:
        linenbr: 1
        text: "CORRIDOR BATTLE"
        pts: modestat_5_scoring
        secs: none
        cycle: "instant"
        delayms: 0
   player_corridor_targets_hit:
     set_infoboard_line_text:
        linenbr: 2
        text: "ROBOTS DESTORYED"
        pts: corridor_targets_hit
        secs: none
        cycle: "instant"
        delayms: 0
   player_corridor_seconds:
     set_infoboard_line_text:
        linenbr: 3
        text: "TIME REMAINING"
        pts: none
        secs: corridor_seconds
        cycle: "instant"
        delayms: 0