#config_version=5

mode:
   start_events: selector_untitled_mode_5_selected
   stop_events: story_is_completed
   priority: 400

# All Story Modes --
#     Issue a scoop_eject after any introduction activities
# Modes that end with a Scoop Hit --
#     Issue a scoop eject after any outro-activities
# TEMP UNTIL REAL MODE PUT INTO PLACE

# Success/Failure
# By default, success = not losing ball, failure = losing ball
# If your mode has a different ruleset, change when the events
# story_is_completed_successful / acheivement_story##_successful
# story_is_completed_unsuccessful / acheivement_story##_unsuccessful
# are issued.

event_player:
   mode_story05_started:
     - story_is_about_to_begin
   story_intro_complete:
     - scoop_eject
   timer_yttimer05_complete:
     - story_is_about_to_end
   story_outro_complete:
     - story_is_completed_successful
     - acheivement_story05_successful
#    Only used when scoop hits end the mode
#    - scoop_eject
   ball_ending:
     - story_is_completed_unsuccessful
     - acheivement_story05_unsuccessful
   story_is_completed_successful:
    - story_is_completed
   story_is_completed_unsuccessful:
    - story_is_completed

#  Base intro / outro shows
show_player:
   story_is_about_to_begin:
      story_05_intro:
         events_when_advanced: story_intro_complete
         events_when_completed: story_intro_complete
         events_when_stopped: story_intro_complete
         loops: 0
   story_is_about_to_end:
      story_05_outro:
         events_when_advanced: story_outro_complete
         events_when_completed: story_outro_complete
         events_when_stopped: story_outro_complete
         loops: 0

shows:
   story_05_intro:
     - time: 0
       slides: story_05_intro_slide
       duration: 3
   story_05_outro:
     - time: 0
       slides: story_05_outro_slide
       duration: 3

slides:
   story_05_intro_slide:
    widgets:
      - type: text
        text: STORY 05 BEGIN SHOW
        color: red
        font_size: 100
        font_name: ocr-a-tribute-bold
   story_05_outro_slide:
    widgets:
      - type: text
        text: STORY 05 END SHOW
        color: red
        font_size: 100
        font_name: ocr-a-tribute-bold

# The below is mode specific data

# ALL STORY MODES ARE RESPONSIBLE FOR ISSUING THE scoop_eject EVENT TO START THE MODE
# TEMP UNTIL REAL MODE PUT INTO PLACE

variable_player:
   mode_story05_started:
     temp_ythurryup_value:
       action: set
       int: 100000
   timer_yttimer05_tick:
     temp_ythurryup_value: -300
   s_sTargetYellowL_active:
     score: current_player.temp_ythurryup_value|block
   s_sTargetYellowR_active:
     score: current_player.temp_ythurryup_value|block

timers:
   yttimer05:
     start_value: 100
     end_value: 0
     tick_interval: .1s
     direction: down
     start_running: yes

widget_player:
   mode_story05_started:
      yt_remain_widget_05:
         slide: scoring_slide
   story05_ended:
      yt_remain_widget_05:
         action: remove

widgets:
   yt_remain_widget_05:
     - type: text
       text: "Story 05 Hurry Up: (temp_ythurryup_value)"
       y: 80%

