#config_version=5

#TODO -- Change the shows
#TODO    See if we can go back to "started" after "selected" if it was previously started
#TODO    Probably need to change up the "disable" events.

achievements:
 untitled_mode_1:
   show_tokens:
     light: l_mode0
   enable_events: selector_untitled_mode_1_highlighted
   select_events: selector_untitled_mode_1_highlighted
   disable_events: selector_untitled_mode_2_highlighted, selector_untitled_mode_3_highlighted, selector_untitled_mode_4_highlighted, selector_untitled_mode_5_highlighted, selector_untitled_mode_6_highlighted, selector_untitled_mode_7_highlighted
   start_events: mode_story01_started
   complete_events: acheivement_story01_successful
   reset_events: acheivement_story01_unsuccessful, full_mode_and_char_reset
   show_when_selected: popred
   show_when_started: popgreen
   show_when_completed: ach1
   show_when_disabled: off
 untitled_mode_2:
   show_tokens:
     light: l_mode1
   enable_events: selector_untitled_mode_2_highlighted
   select_events: selector_untitled_mode_2_highlighted
   start_events: mode_story02_started
   disable_events: selector_untitled_mode_1_highlighted, selector_untitled_mode_3_highlighted, selector_untitled_mode_4_highlighted, selector_untitled_mode_5_highlighted, selector_untitled_mode_6_highlighted, selector_untitled_mode_7_highlighted
   complete_events: acheivement_story02_successful
   reset_events: acheivement_story02_unsuccessful, full_mode_and_char_reset
   show_when_selected: popred
   show_when_started: popgreen
   show_when_completed: ach2
   show_when_stopped: off
 untitled_mode_3:
   show_tokens:
     light: l_mode2
   enable_events: selector_untitled_mode_3_highlighted
   select_events: selector_untitled_mode_3_highlighted
   start_events: mode_story03_started
   disable_events: selector_untitled_mode_1_highlighted, selector_untitled_mode_2_highlighted, selector_untitled_mode_4_highlighted, selector_untitled_mode_5_highlighted, selector_untitled_mode_6_highlighted, selector_untitled_mode_7_highlighted
   complete_events: acheivement_story03_successful
   reset_events: acheivement_story03_unsuccessful, full_mode_and_char_reset
   show_when_selected: popred
   show_when_started: popgreen
   show_when_completed: ach3
   show_when_stopped: off
 untitled_mode_4:
   show_tokens:
     light: l_mode3
   enable_events: selector_untitled_mode_4_highlighted
   select_events: selector_untitled_mode_4_highlighted
   start_events: mode_story04_started
   disable_events: selector_untitled_mode_1_highlighted, selector_untitled_mode_2_highlighted, selector_untitled_mode_3_highlighted, selector_untitled_mode_5_highlighted, selector_untitled_mode_6_highlighted, selector_untitled_mode_7_highlighted
   complete_events: acheivement_story04_successful
   reset_events: acheivement_story04_unsuccessful, full_mode_and_char_reset
   show_when_selected: popred
   show_when_started: popgreen
   show_when_completed: ach4
   show_when_stopped: off
 untitled_mode_5:
   show_tokens:
     light: l_mode4
   enable_events: selector_untitled_mode_5_highlighted
   select_events: selector_untitled_mode_5_highlighted
   start_events: mode_story05_started
   disable_events: selector_untitled_mode_1_highlighted, selector_untitled_mode_2_highlighted, selector_untitled_mode_3_highlighted, selector_untitled_mode_4_highlighted, selector_untitled_mode_6_highlighted, selector_untitled_mode_7_highlighted
   complete_events: acheivement_story05_successful
   reset_events: acheivement_story05_unsuccessful, full_mode_and_char_reset
   show_when_selected: popred
   show_when_started: popgreen
   show_when_completed: ach5
   show_when_stopped: off
 untitled_mode_6:
   show_tokens:
     light: l_mode5
   enable_events: selector_untitled_mode_6_highlighted
   select_events: selector_untitled_mode_6_highlighted
   start_events: mode_story06_started
   disable_events: selector_untitled_mode_1_highlighted, selector_untitled_mode_2_highlighted, selector_untitled_mode_3_highlighted, selector_untitled_mode_4_highlighted, selector_untitled_mode_5_highlighted, selector_untitled_mode_7_highlighted
   complete_events: acheivement_story06_successful
   reset_events: acheivement_story06_unsuccessful, full_mode_and_char_reset
   show_when_selected: popred
   show_when_started: popgreen
   show_when_completed: ach6
   show_when_stopped: off
 untitled_mode_7:
   show_tokens:
     light: l_mode6
   enable_events: selector_untitled_mode_7_highlighted
   select_events: selector_untitled_mode_7_highlighted
   start_events: mode_story06_started
   disable_events: selector_untitled_mode_1_highlighted, selector_untitled_mode_2_highlighted, selector_untitled_mode_3_highlighted, selector_untitled_mode_4_highlighted, selector_untitled_mode_5_highlighted, selector_untitled_mode_6_highlighted
   complete_events: acheivement_story07_successful
   reset_events: acheivement_story07_unsuccessful, full_mode_and_char_reset
   show_when_selected: popred
   show_when_started: popgreen
   show_when_completed: ach7
   show_when_stopped: off

# This will be for character collection for the wizard mode bonus
 char_vincent:
   start_events: char_collect_start
   complete_events: char_vincent_complete
   reset_events: full_mode_and_char_reset
   show_when_completed: char_vincent
   restart_on_next_ball_when_started: true
   restart_after_stop_possible: true
 char_bob:
   start_events: char_collect_start
   complete_events: char_bob_complete
   reset_events: full_mode_and_char_reset
   show_when_completed: char_bob
   restart_on_next_ball_when_started: true
   restart_after_stop_possible: true
 char_dan:
   start_events: char_collect_start
   complete_events: char_dan_complete
   reset_events: full_mode_and_char_reset
   show_when_completed: char_dan
   restart_on_next_ball_when_started: true
   restart_after_stop_possible: true
 char_charlie:
   start_events: char_collect_start
   complete_events: char_charlie_complete
   reset_events: full_mode_and_char_reset
   show_when_completed: char_charlie
   restart_on_next_ball_when_started: true
   restart_after_stop_possible: true
 char_harry:
   start_events: char_collect_start
   complete_events: char_harry_complete
   reset_events: full_mode_and_char_reset
   show_when_completed: char_harry
   restart_on_next_ball_when_started: true
   restart_after_stop_possible: true
 char_kate:
   start_events: char_collect_start
   complete_events: char_kate_complete
   reset_events: full_mode_and_char_reset
   show_when_completed: char_kate
   restart_on_next_ball_when_started: true
   restart_after_stop_possible: true
 char_alex:
   start_events: char_collect_start
   complete_events: char_alex_complete
   reset_events: full_mode_and_char_reset
   show_when_completed: char_alex
   restart_on_next_ball_when_started: true
   restart_after_stop_possible: true
 char_hans:
   start_events: char_collect_start
   complete_events: char_hans_complete
   reset_events: full_mode_and_char_reset
   show_when_completed: char_hans
   restart_on_next_ball_when_started: true
   restart_after_stop_possible: true

event_player:
   full_mode_and_char_reset:
     - char_collect_start
   first_ball_for_current_player:
     - char_collect_start

random_event_player:
   random_character_collect:
      events:
        - char_dan_complete
        - char_charlie_complete
        - char_harry_complete
        - char_kate_complete
        - char_alex_complete
        - char_hans_complete
      force_all: true
      scope: player

show_player:
  char_dan_complete:
     char_dan_collect:
       loops: 0
     collectDanShow:
       loops: 0
       speed: 45
       priority: 2000
  char_charlie_complete:
     char_charlie_collect:
       loops: 0
     collectCharlieShow:
       loops: 0
       speed: 45
       priority: 2000
  char_harry_complete:
     char_harry_collect:
       loops: 0
     collectHarryShow:
       loops: 0
       speed: 45
       priority: 2000
  char_kate_complete:
     char_kate_collect:
       loops: 0
     collectKateShow:
       loops: 0
       speed: 45
       priority: 2000
  char_alex_complete:
     char_alex_collect:
       loops: 0
     collectAlexShow:
       loops: 0
       speed: 45
       priority: 2000
  char_hans_complete:
     char_hans_collect:
       loops: 0
     collectHansShow:
       loops: 0
       speed: 45
       priority: 2000
  char_vincent_complete:
     char_vincent_collect:
       loops: 0
     collectVincentShow:
       loops: 0
       speed: 45
       priority: 2000
  char_bob_complete:
     char_bob_collect:
       loops: 0
     collectBobShow:
       loops: 0
       speed: 45
       priority: 2000

sound_player:
  char_dan_complete: character_collect_sound
  char_charlie_complete: character_collect_sound
  char_harry_complete: character_collect_sound
  char_kate_complete: character_collect_sound
  char_alex_complete: character_collect_sound
  char_hans_complete: character_collect_sound
  char_vincent_complete: character_collect_sound
  char_bob_complete: character_collect_sound

shows:
  char_dan_collect:
     - time: 0
       widgets:
        char_dan:
         slide: scoring_slide
         action: add
       duration: 2
  char_charlie_collect:
     - time: 0
       widgets:
        char_charlie:
         slide: scoring_slide
         action: add
       duration: 2
  char_harry_collect:
     - time: 0
       widgets:
        char_harry:
         slide: scoring_slide
         action: add
       duration: 2
  char_kate_collect:
     - time: 0
       widgets:
        char_kate:
         slide: scoring_slide
         action: add
       duration: 2
  char_alex_collect:
     - time: 0
       widgets:
        char_alex:
         slide: scoring_slide
         action: add
       duration: 2
  char_hans_collect:
     - time: 0
       widgets:
        char_hans:
         slide: scoring_slide
         action: add
       duration: 2
  char_vincent_collect:
     - time: 0
       widgets:
        char_vincent:
         slide: scoring_slide
         action: add
         priority: 3000
       duration: 2
  char_bob_collect:
     - time: 0
       widgets:
        char_bob:
         slide: scoring_slide
         action: add
       duration: 2

widgets:
   char_dan:
      - type: text
        text: DAN COLLECTED
        style:
          - char_collect_style_bottom
      - type: image
        image: dan
        anchor_x: center
        anchor_y: center
        scale: 4
        opacity: .99
        z: 14
        animations:
          add_to_slide:
            - property: x
              value: 17%
              duration: 1.5s
            - property: y
              value: 84%
              duration: 1.5s
              timing: with_previous
            - property: scale
              value: 1
              timing: with_previous
              duration: 1.5s
   char_charlie:
      - type: text
        text: CHARLIE COLLECTED
        style:
          - char_collect_style_bottom
      - type: image
        image: charlie
        anchor_x: center
        anchor_y: center
        scale: 4
        opacity: .99
        z: 14
        animations:
          add_to_slide:
            - property: x
              value: 25%
              duration: 1.5s
            - property: y
              value: 84%
              duration: 1.5s
              timing: with_previous
            - property: scale
              value: 1
              timing: with_previous
              duration: 1.5s
   char_harry:
      - type: text
        text: HARRY COLLECTED
        style:
          - char_collect_style_bottom
      - type: image
        image: harry
        anchor_x: center
        anchor_y: center
        scale: 4
        opacity: .99
        z: 14
        animations:
          add_to_slide:
            - property: x
              value: 33%
              duration: 1.5s
            - property: y
              value: 84%
              duration: 1.5s
              timing: with_previous
            - property: scale
              value: 1
              timing: with_previous
              duration: 1.5s
   char_kate:
      - type: text
        text: KATE COLLECTED
        style:
          - char_collect_style_bottom
      - type: image
        image: kate
        anchor_x: center
        anchor_y: center
        scale: 4
        opacity: .99
        z: 14
        animations:
          add_to_slide:
            - property: x
              value: 41%
              duration: 1.5s
            - property: y
              value: 84%
              duration: 1.5s
              timing: with_previous
            - property: scale
              value: 1
              timing: with_previous
              duration: 1.5s
   char_alex:
      - type: text
        text: ALEX COLLECTED
        style:
          - char_collect_style_bottom
      - type: image
        image: alex
        anchor_x: center
        anchor_y: center
        scale: 4
        opacity: .99
        z: 14
        animations:
          add_to_slide:
            - property: x
              value: 49%
              duration: 1.5s
            - property: y
              value: 84%
              duration: 1.5s
              timing: with_previous
            - property: scale
              value: 1
              timing: with_previous
              duration: 1.5s
   char_hans:
      - type: text
        text: HANS COLLECTED
        style:
          - char_collect_style_bottom
      - type: image
        image: hanz
        anchor_x: center
        anchor_y: center
        scale: 4
        opacity: .99
        z: 14
        animations:
          add_to_slide:
            - property: x
              value: 57%
              duration: 1.5s
            - property: y
              value: 84%
              duration: 1.5s
              timing: with_previous
            - property: scale
              value: 1
              timing: with_previous
              duration: 1.5s
   char_vincent:
      - type: text
        text: VINCENT COLLECTED
        style:
          - char_collect_style_bottom
      - type: image
        image: vincent
        anchor_x: center
        anchor_y: center
        scale: 4
        opacity: .99
        z: 14
        animations:
          add_to_slide:
            - property: x
              value: 65%
              duration: 1.5s
            - property: y
              value: 84%
              duration: 1.5s
              timing: with_previous
            - property: scale
              value: 1
              timing: with_previous
              duration: 1.5s
   char_bob:
      - type: text
        text: BOB COLLECTED
        style:
          - char_collect_style_bottom
      - type: image
        image: bob
        anchor_x: center
        anchor_y: center
        scale: 4
        opacity: .99
        z: 14
        animations:
          add_to_slide:
            - property: x
              value: 73%
              duration: 1.5s
            - property: y
              value: 84%
              duration: 1.5s
              timing: with_previous
            - property: scale
              value: 1
              timing: with_previous
              duration: 1.5s

