#config_version=5
config:
  - achievements.yaml
  - scoring.yaml

mode:
  start_events: ball_starting
  priority: 100

slide_player:
  mode_base_started: scoring_slide
#  scoop_slide: s_ir_scoop_detect_active

widget_player:
   s_jet_upper_left_active:
      sample_quick_vid:
         slide: scoring_slide
         widget_settings:
           expire: 2s

slides:
   scoring_slide:
    widgets:
      - type: image
        image: logo
        x: 150
        y: 650
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
        font_name: ocr-a-tribute-bold
        y: 40%
      - type: text
        text: PLAYER (number)
        y: 10
        x: 10
        font_size: 50
        font_name: ocr-a-tribute-bold
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 10
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_size: 50
        font_name: ocr-a-tribute-bold
      - type: text
        text: "POPS: (pops)"
        y: 30%
      - type: text
        text: "DROPS: (drops)"
        y: 25%
      - type: text
        text: "SPINS: (spins)"
        y: 20%
      - type: text
        text: "BONUS: (bonuscount)"
        y: 15%
      - type: text
        text: "BONUS X: (bonus_multiplier)"
   scoop_slide:
    widgets:
      - type: text
        text: SCOOP MADNESS
        color: red
        font_size: 100
        font_name: ocr-a-tribute-bold
    expire: 3s



counters:
  ctDropL0:
      count_events: shotTargetL0_flashing_hit
      starting_count: 0

timers:
  targetRotator:
    start_running: true
    tick_interval: 5s
  targetRotatorB:
    start_running: true
    tick_interval: 5s

state_machines:
  lt0:
     states:
       start:
         label: start state
         events_when_started: lt0_flash_start
       lightsflash:
         label: flashing
         events_when_started: lt0_off_start
       lighton:
         label: lit
         events_when_started: lt0_lit_start
     transitions:
       - source: start
         target: lightsflash
         events: timer_targetRotator_tick
       - source: lightsflash
         target: start
         events: timer_targetRotator_tick
       - source: start
         target: lighton
         events: shotTargetL0_flashing_hit
       - source: lighton
         target: start
         events: shotGroupLeftTargets_lit_complete
  lt1:
     states:
       start:
         label: start state
         events_when_started: lt1_off_start
       lightsflash:
         label: flashing
         events_when_started: lt1_flash_start
       lighton:
         label: lit
         events_when_started: lt1_lit_start
     transitions:
       - source: start
         target: lightsflash
         events: timer_targetRotator_tick
       - source: lightsflash
         target: start
         events: timer_targetRotator_tick
       - source: lightsflash
         target: lighton
         events: shotTargetL1_flashing_hit
       - source: lighton
         target: start
         events: shotGroupLeftTargets_lit_complete

  lt2:
     states:
       start:
         label: start state
         events_when_started: lt2_flash_start
       lightsflash:
         label: flashing
         events_when_started: lt2_off_start
       lighton:
         label: lit
         events_when_started: lt2_lit_start
     transitions:
       - source: start
         target: lightsflash
         events: timer_targetRotator_tick
       - source: lightsflash
         target: start
         events: timer_targetRotator_tick
       - source: start
         target: lighton
         events: shotTargetL2_flashing_hit
       - source: lighton
         target: start
         events: shotGroupLeftTargets_lit_complete

  lt3:
     states:
       start:
         label: start state
         events_when_started: lt3_off_start
       lightsflash:
         label: flashing
         events_when_started: lt3_flash_start
       lighton:
         label: lit
         events_when_started: lt3_lit_start
     transitions:
       - source: start
         target: lightsflash
         events: timer_targetRotator_tick
       - source: lightsflash
         target: start
         events: timer_targetRotator_tick
       - source: lightsflash
         target: lighton
         events: shotTargetL3_flashing_hit
       - source: lighton
         target: start
         events: shotGroupLeftTargets_lit_complete

shots:
  shotCenterPop:
    switch: s_jet_lower_center
    show_tokens:
      light: l_jetLowerCenter
    profile: shotProfilePops
  shotUpperLeftPop:
    switch: s_jet_upper_left
    show_tokens:
      light: l_jetUpperLeft
    profile: shotProfilePops
  shotUpperRightPop:
    switch: s_jet_upper_right
    show_tokens:
      light: l_jetUpperRight
    profile: shotProfilePops
  shotLane0:
    switch: s_lane0
    show_tokens:
      light: l_lane0
    profile: shotProfileToplanes
  shotLane1:
    switch: s_lane1
    show_tokens:
      light: l_lane1
    profile: shotProfileToplanes
  shotLane2:
    switch: s_lane2
    show_tokens:
      light: l_lane2
    profile: shotProfileToplanes
  shotLane3:
    switch: s_lane3
    show_tokens:
      light: l_lane3
    profile: shotProfileToplanes
  shotLane4:
    switch: s_lane4
    show_tokens:
      light: l_lane4
    profile: shotProfileToplanes
  shotTargetL0:
    switch: s_dTargetL0
    show_tokens:
      light: l_dropLeft0
    profile: shotProfileToplanes
    advance_events: lt0_flash_start
    reset_events: lt0_off_start, shotTargetL0_unlit_hit
  shotTargetL1:
    switch: s_dTargetL1
    show_tokens:
      light: l_dropLeft1
    profile: shotProfileToplanes
    advance_events: lt1_flash_start
    reset_events: lt1_off_start, shotTargetL1_unlit_hit
  shotTargetL2:
    switch: s_dTargetL2
    show_tokens:
      light: l_dropLeft2
    profile: shotProfileToplanes
    advance_events: lt2_flash_start
    reset_events: lt2_off_start, shotTargetL2_unlit_hit
  shotTargetL3:
    switch: s_dTargetL3
    show_tokens:
      light: l_dropLeft3
    profile: shotProfileToplanes
    advance_events: lt3_flash_start
    reset_events: lt3_off_start, shotTargetL3_unlit_hit


shot_profiles:
  shotProfileToplanes:
    states:
      - name: unlit
        show: off
      - name: lit
        show: dk_blu_on
    loop: false
  shotProfilePops:
    states:
      - name: popBumpRed
        show: popred
      - name: popBumpBlue
        show: popblue
      - name: popBumpGreen
        show: popgreen
    loop: true

shot_groups:
   shotGroupToplanes:
       shots: shotLane0, shotLane1, shotLane2, shotLane3, shotLane4
       rotate_left_events: s_flipper_left_active
       rotate_right_events: s_flipper_right_active
       reset_events: shotGroupToplanes_lit_complete
       enable_events: ball_started
       disable_events: ball_ending
   shotGroupLeftTargets:
       shots: shotTargetL0, shotTargetL1, shotTargetL2, shotTargetL3
       reset_events: shotGroupLeftTargets_lit_complete
       enable_events: ball_started
       disable_events: ball_ending

sound_player:
    s_slingshot_left_active: testFX1
    s_slingshot_right_active: testFX1
    s_jet_lower_center_active: testFX3
    s_jet_upper_right_active: testFX3
    s_jet_upper_left_active: testFX3
    mode_base_started:
      overture:
          action: play
          loops: -1
          mode_end_action: stop

queue_relay_player:
  balldevice_bd_scoop_ball_eject_attempt:
      post: select_mode_start
      wait_for: selector_item_selected

show_player:
  start_mode_scoop_show:
      scoop_show:
          loops: 0
          events_when_completed: mode_scoop_show_ended, select_mode_start #yt_hurry_up_started

shows:
  scoop_show:
     - time: 0
       slides: scoop_slide
       lights:
         l_2x: red
         l_3x: red
         l_4x: red
         l_5x: red
     - time: +1
       lights:
         l_2x: blue
         l_3x: blue
         l_4x: blue
         l_5x: blue
     - time: +1
       lights:
         l_2x: green
         l_3x: green
         l_4x: green
         l_5x: green
