#config_version=5
config:
  - achievements.yaml
  - scoring.yaml
  - statemachines.yaml

mode:
  start_events: ball_starting
  priority: 100

slide_player:
  mode_base_started: scoring_slide
#  scoop_slide: s_ir_scoop_detect_active

widget_player:
   s_jet_upper_left_active:
      sample_quick_vid:
         slide: scoring_slide
         widget_settings:
           expire: 2s

slides:
   scoring_slide:
    widgets:
      - type: image
        image: logo
        x: 150
        y: 650
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
        font_name: ocr-a-tribute-bold
        y: 40%
      - type: text
        text: PLAYER (number)
        y: 10
        x: 10
        font_size: 50
        font_name: ocr-a-tribute-bold
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 10
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_size: 50
        font_name: ocr-a-tribute-bold
      - type: text
        text: "POPS: (pops)"
        y: 30%
      - type: text
        text: "DROPS: (drops)"
        y: 25%
      - type: text
        text: "SPINS: (spins)"
        y: 20%
      - type: text
        text: "BONUS: (bonuscount)"
        y: 15%
      - type: text
        text: "BONUS X: (bonus_multiplier)"
      - type: text
        text: (machine.device_manager.collections["shots"]["shotTargetL0"].state) machine.device_manager.collections["shots"]["shotTargetL0"].state
        y: 10%
   scoop_slide:
    widgets:
      - type: text
        text: SCOOP MADNESS
        color: red
        font_size: 100
        font_name: ocr-a-tribute-bold
    expire: 3s

timers:
  targetRotator:
   start_value: 0
   tick_interval: 2s
   control_events:
     - event: mode_base_started
       action: start

  dropTimerA:
   start_value: 0
   end_value: 1
   tick_interval: 2s
   control_events:
     - event: mode_base_started
       action: start
     - event: timer_dropTimerB_stopped
       action: restart
  dropTimerB:
   start_value: 0
   end_value: 1
   tick_interval: 2s
   control_events:
     - event: timer_dropTimerA_Stopped
       action: restart

shots:
  shotCenterPop:
    switch: s_jet_lower_center
    show_tokens:
      light: l_jetLowerCenter
    profile: shotProfilePops
  shotUpperLeftPop:
    switch: s_jet_upper_left
    show_tokens:
      light: l_jetUpperLeft
    profile: shotProfilePops
  shotUpperRightPop:
    switch: s_jet_upper_right
    show_tokens:
      light: l_jetUpperRight
    profile: shotProfilePops
  shotLane0:
    switch: s_lane0
    show_tokens:
      light: l_lane0
    profile: shotProfileToplanes
  shotLane1:
    switch: s_lane1
    show_tokens:
      light: l_lane1
    profile: shotProfileToplanes
  shotLane2:
    switch: s_lane2
    show_tokens:
      light: l_lane2
    profile: shotProfileToplanes
  shotLane3:
    switch: s_lane3
    show_tokens:
      light: l_lane3
    profile: shotProfileToplanes
  shotLane4:
    switch: s_lane4
    show_tokens:
      light: l_lane4
    profile: shotProfileToplanes
  shotTargetL0:
    switch: s_dTargetL0
    show_tokens:
      light: l_dropLeft0
    profile: shotProfileLeftTargets
    advance_events: lt0_flash_start, lt0_lit_start
    reset_events: lt0_off_start, shotTargetL0_unlit_hit
  shotTargetL1:
    switch: s_dTargetL1
    show_tokens:
      light: l_dropLeft1
    profile: shotProfileLeftTargets
    advance_events: lt1_flash_start, lt1_lit_start
    reset_events: lt1_off_start, shotTargetL1_unlit_hit
  shotTargetL2:
    switch: s_dTargetL2
    show_tokens:
      light: l_dropLeft2
    profile: shotProfileLeftTargets
    advance_events: lt2_flash_start, lt2_lit_start
    reset_events: lt2_off_start, shotTargetL2_unlit_hit
  shotTargetL3:
    switch: s_dTargetL3
    show_tokens:
      light: l_dropLeft3
    profile: shotProfileLeftTargets
    advance_events: lt3_flash_start, lt3_lit_start
    reset_events: lt3_off_start, shotTargetL3_unlit_hit
  shotTargetR0:
    switch: s_dTargetR0
    show_tokens:
      light: l_dropRight0
    profile: shotProfileRightTargets
    advance_events: rt0_flash_start, rt0_lit_start
    reset_events: rt0_off_start, shotTargetR0_unlit_hit
  shotTargetR1:
    switch: s_dTargetR1
    show_tokens:
      light: l_dropRight1
    profile: shotProfileRightTargets
    advance_events: rt1_flash_start, rt1_lit_start
    reset_events: rt1_off_start, shotTargetR1_unlit_hit
  shotTargetR2:
    switch: s_dTargetR2
    show_tokens:
      light: l_dropRight2
    profile: shotProfileRightTargets
    advance_events: rt2_flash_start, rt2_lit_start
    reset_events: rt2_off_start, shotTargetR2_unlit_hit
  shotTargetR3:
    switch: s_dTargetR3
    show_tokens:
      light: l_dropRight3
    profile: shotProfileRightTargets
    advance_events: rt3_flash_start, rt3_lit_start
    reset_events: rt3_off_start, shotTargetR3_unlit_hit
  shotScoop:
    switch: s_ir_scoop_detect
    show_tokens:
      light: l_scoop
    profile: shotProfileScoop
    advance_events: selector_item_selected, mode_story01_stopped, mode_story02_stopped, mode_story03_stopped, mode_story04_stopped, mode_story05_stopped, mode_story06_stopped, mode_story07_stopped,
    reset_events: shotGroupToplanes_lit_complete, drop_target_bank_leftfull_down, drop_target_bank_rightfull_down, gravityAssistBonus

shot_profiles:
  shotProfileLeftTargets:
    show_when_disabled: true
    states:
      - name: unlit
        show: off
      - name: flashing
        show: dk_blu_flash
      - name: lit
        show: dk_blu_on
  shotProfileRightTargets:
    show_when_disabled: true
    states:
      - name: unlit
        show: off
      - name: flashing
        show: dk_blu_flash
      - name: lit
        show: dk_blu_on
  shotProfileToplanes:
    states:
      - name: unlit
        show: off
      - name: lit
        show: dk_blu_on
    loop: false
  shotProfilePops:
    states:
      - name: popBumpRed
        show: popred
      - name: popBumpBlue
        show: popblue
      - name: popBumpGreen
        show: popgreen
    loop: true
  shotProfileScoop:
    advance_on_hit: false
    states:
      - name: scoopReady
        show: popred
      - name: scoopActive
        show: popgreen
      - name: scoopNotReady
        show: off

shot_groups:
   shotGroupToplanes:
       shots: shotLane0, shotLane1, shotLane2, shotLane3, shotLane4
       rotate_left_events: s_flipper_left_active
       rotate_right_events: s_flipper_right_active
       reset_events: shotGroupToplanes_lit_complete
       enable_events: ball_started
       disable_events: ball_ending
   shotGroupLeftTargets:
       shots: shotTargetL0, shotTargetL1, shotTargetL2, shotTargetL3
       reset_events: reset_both_lane_lit_groups
       enable_events: ball_started
       disable_events: ball_ending
   shotGroupRightTargets:
       shots: shotTargetR0, shotTargetR1, shotTargetR2, shotTargetR3
       reset_events: reset_both_lane_lit_groups
       enable_events: ball_started
       disable_events: ball_ending

sound_player:
    s_slingshot_left_active: testFX1
    s_slingshot_right_active: testFX1
    s_jet_lower_center_active: testFX3
    s_jet_upper_right_active: testFX3
    s_jet_upper_left_active: testFX3
    mode_base_started:
      overture:
          action: play
          loops: -1
          mode_end_action: stop

show_player:
  shotScoop_scoopReady_hit:
      scoop_show:
          loops: 0
          events_when_completed: select_mode_start #, select_mode_start #yt_hurry_up_started
  shotScoop_scoopActive_hit:
      scoop_show_ip:
          loops: 0
          events_when_completed: scoop_eject
  shotScoop_scoopNotReady_hit:
      scoop_show_nr:
          loops: 0
          events_when_completed: scoop_eject
  extra_ball_is_lit:
      extra_lit:
          loops: -1
  extra_ball_is_earned:
      extra_lit:
          action: stop
      extra_earned:
          loops: -1

shows:
  scoop_show:
     - time: 0
       slides: scoop_slide
       lights:
         l_2x: red
         l_3x: red
         l_4x: red
         l_5x: red
     - time: +1
       lights:
         l_2x: blue
         l_3x: blue
         l_4x: blue
         l_5x: blue
     - time: +1
       lights:
         l_2x: green
         l_3x: green
         l_4x: green
         l_5x: green
  scoop_show_ip:
     - time: 0
       lights:
         l_2x: green
         l_3x: green
         l_4x: green
         l_5x: green
  scoop_show_nr:
     - time: 0
       lights:
         l_2x: red
         l_3x: red
         l_4x: red
         l_5x: red
  extra_lit:
     - time: 0
       lights:
         l_shootAgain: red
     - time: +1
       lights:
         l_shootAgain: off
  extra_earned:
     - time: 0
       lights:
         l_shootAgain: green