#config_version=5
config:
  - achievements.yaml
  - scoring.yaml
  - statemachines.yaml
  - baseBallSave.yaml
  - widgets.yaml
  - centerdrops.yaml
  - mode_exit_widgets.yaml
  - mode_exit_shows.yaml
  - mode_start_video_widgets.yaml
  - bot_lighting_effects.yaml

#  - junkytest.yaml        # can remove this after

# ---------------------------------------------------
# Ideas for improvement
# ---------------------------------------------------
# THINGS THAT CAN BE THEIR OWN MODE
#   bonus multiplier
#   rotating target/extra ball mechanic

# Can we prevent the selector mode from starting when
#   only one regular (1 to 6) mode remains?
#   mode 7 will automatically start?
# ...or maybe just keep its slide from appearing in this case

#TODO -- add ways to collect the bots (VinCENT and Old Bob)
#TODO -- implement the character bonuses for the final mode
#TODO -- make something happen after the final mode

mode:
  start_events: ball_starting
  priority: 100
  file_log: full

slides:
   scoop_slide:
    widgets:
      - type: text
        text: SELECT A SCENE
        color: red
        font_size: 100
        font_name: ocr-a-tribute-bold
    expire: 3s


timers:
  targetRotator:
   start_value: 0
   tick_interval: 2s
   control_events:
     - event: mode_base_started
       action: start
     - event: mode_using_targets_started
       action: stop
     - event: mode_using_targets_ended
       action: restart

shots:
  shotCenterPop:
    switch: s_jet_lower_center
    show_tokens:
      light: l_jetLowerCenter
    profile: shotProfilePops
  shotUpperLeftPop:
    switch: s_jet_upper_left
    show_tokens:
      light: l_jetUpperLeft
    profile: shotProfilePops
  shotUpperRightPop:
    switch: s_jet_upper_right
    show_tokens:
      light: l_jetUpperRight
    profile: shotProfilePops
  shotLane0:
    switch: s_lane0
    show_tokens:
      light: l_lane0
    profile: shotProfileToplanes
  shotLane1:
    switch: s_lane1
    show_tokens:
      light: l_lane1
    profile: shotProfileToplanes
  shotLane2:
    switch: s_lane2
    show_tokens:
      light: l_lane2
    profile: shotProfileToplanes
  shotLane3:
    switch: s_lane3
    show_tokens:
      light: l_lane3
    profile: shotProfileToplanes
  shotLane4:
    switch: s_lane4
    show_tokens:
      light: l_lane4
    profile: shotProfileToplanes
  shotTargetL0:
    switch: s_dTargetL0
    show_tokens:
      light: l_dropLeft0
    profile: shotProfileLeftTargets
    advance_events: lt0_flash_start, lt0_lit_start
    reset_events: lt0_off_start, shotTargetL0_unlit_hit
  shotTargetL1:
    switch: s_dTargetL1
    show_tokens:
      light: l_dropLeft1
    profile: shotProfileLeftTargets
    advance_events: lt1_flash_start, lt1_lit_start
    reset_events: lt1_off_start, shotTargetL1_unlit_hit
  shotTargetL2:
    switch: s_dTargetL2
    show_tokens:
      light: l_dropLeft2
    profile: shotProfileLeftTargets
    advance_events: lt2_flash_start, lt2_lit_start
    reset_events: lt2_off_start, shotTargetL2_unlit_hit
  shotTargetL3:
    switch: s_dTargetL3
    show_tokens:
      light: l_dropLeft3
    profile: shotProfileLeftTargets
    advance_events: lt3_flash_start, lt3_lit_start
    reset_events: lt3_off_start, shotTargetL3_unlit_hit
  shotTargetR0:
    switch: s_dTargetR0
    show_tokens:
      light: l_dropRight0
    profile: shotProfileRightTargets
    advance_events: rt0_flash_start, rt0_lit_start
    reset_events: rt0_off_start, shotTargetR0_unlit_hit
  shotTargetR1:
    switch: s_dTargetR1
    show_tokens:
      light: l_dropRight1
    profile: shotProfileRightTargets
    advance_events: rt1_flash_start, rt1_lit_start
    reset_events: rt1_off_start, shotTargetR1_unlit_hit
  shotTargetR2:
    switch: s_dTargetR2
    show_tokens:
      light: l_dropRight2
    profile: shotProfileRightTargets
    advance_events: rt2_flash_start, rt2_lit_start
    reset_events: rt2_off_start, shotTargetR2_unlit_hit
  shotTargetR3:
    switch: s_dTargetR3
    show_tokens:
      light: l_dropRight3
    profile: shotProfileRightTargets
    advance_events: rt3_flash_start, rt3_lit_start
    reset_events: rt3_off_start, shotTargetR3_unlit_hit
  shotScoop:
    switch: s_ir_scoop_detect
    show_tokens:
      light: l_scoop
    profile: shotProfileScoop
    reset_events: do_scoop_notify

event_player:
    mode_base_started{ball==1 and is_extra_ball==0}:
      - scoop_reset
    shotGroupToplanes_lit_complete:
      - scoop_reset
    drop_target_bank_leftfull_down:
      - scoop_reset
    drop_target_bank_rightfull_down:
      - scoop_reset
    gravityAssistBonus:
      - scoop_reset
    story_is_completed_unsuccessful:
      - ach_completed
    achievement_untitled_mode_1_state_completed:
      - ach_completed
    achievement_untitled_mode_2_state_completed:
      - ach_completed
    achievement_untitled_mode_3_state_completed:
      - ach_completed
    achievement_untitled_mode_4_state_completed:
      - ach_completed
    achievement_untitled_mode_5_state_completed:
      - ach_completed
    achievement_untitled_mode_6_state_completed:
      - ach_completed
    achievement_untitled_mode_7_state_completed:
      - ach_completed
    story_is_completed:
      - start_base_music
    mode_base_started:
      - start_base_music
    the_one_event_to_reset_them_all:
      - drops_left_reset
      - drops_right_reset
      - drop_left_center_reset
      - drop_right_center_reset
#    ball_save_inmodesave1_saving_ball:
#      - in_mode_ball_save
#    ball_save_inmodesave2_saving_ball:
#      - in_mode_ball_save
#    ball_save_inmodesave3_saving_ball:
#      - in_mode_ball_save
#    ball_save_inmodesave4_saving_ball:
#      - in_mode_ball_save
#    ball_save_inmodesave5_saving_ball:
#      - in_mode_ball_save
#    ball_save_inmodesave6_saving_ball:
#      - in_mode_ball_save
#    ball_save_inmodesave7_saving_ball:
#      - in_mode_ball_save
###########################
# Moved to BASE from story04 to prevent this getting missed
###########################
# move below to base
    shotScoopMeteor_hit{current_player.story04_meteortimer_tick==0}:
#      - scoop_eject
      - generic_scoop_eject_trigger

# shotgrouppopbumpers_popBumpBlue_complete
# shotgrouppopbumpers_popBumpGreen_complete
# shotgrouppopbumpers_popBumpRed_complete

shot_profiles:
  shotProfileLeftTargets:
    show_when_disabled: true
    states:
      - name: unlit
        show: off
      - name: flashing
        show: dk_blu_flash
        speed: 4
      - name: lit
        show: dk_blu_on
  shotProfileRightTargets:
    show_when_disabled: true
    states:
      - name: unlit
        show: off
      - name: flashing
        show: dk_blu_flash
        speed: 4
      - name: lit
        show: dk_blu_on
  shotProfileToplanes:
    states:
      - name: unlit
        show: off
      - name: lit
        show: dk_blu_on
    loop: false
  shotProfilePops:
    states:
      - name: popBumpRed
        show: popred
      - name: popBumpBlue
        show: popblue
      - name: popBumpGreen
        show: popgreen
    loop: true
  shotProfileScoop:
    advance_on_hit: true
    show_when_disabled: false
    states:
      - name: scoopReady
        show: scoopReadyShow
        speed: 2
        priority: 101
#      - name: scoopActive
#        show: popgreen
      - name: scoopNotReady
        show: off

shot_groups:
   shotgrouppopbumpers:
       shots: shotCenterPop, shotUpperLeftPop, shotUpperRightPop
   shotGroupToplanes:
       shots: shotLane0, shotLane1, shotLane2, shotLane3, shotLane4
       rotate_left_events: s_flipper_left_active
       rotate_right_events: s_flipper_right_active
       reset_events: shotGroupToplanes_lit_complete
       enable_events: ball_started
       disable_events: ball_ending
   shotGroupLeftTargets:
       shots: shotTargetL0, shotTargetL1, shotTargetL2, shotTargetL3
       reset_events: reset_both_lane_lit_groups
       enable_events: ball_started, mode_using_targets_ended
       disable_events: ball_ending, mode_using_targets_started
   shotGroupRightTargets:
       shots: shotTargetR0, shotTargetR1, shotTargetR2, shotTargetR3
       reset_events: reset_both_lane_lit_groups
       enable_events: ball_started, mode_using_targets_ended
       disable_events: ball_ending, mode_using_targets_started

sound_player:
    s_slingshot_left_active: laser_blast
    s_slingshot_right_active: laser_blast
    s_sTargetDropL_active: laser_blast
    s_sTargetDropR_active: laser_blast
    s_sTargetLowL_active: laser_blast
    s_sTargetLowR_active: laser_blast
    s_sTargetUpperL_active: laser_blast
    s_sTargetUpperR_active: laser_blast
    s_sTargetYellowL_active: soft_laser
    s_sTargetYellowR_active: soft_laser
    s_jet_lower_center_active: blaster
    s_jet_upper_right_active: blaster
    s_jet_upper_left_active: blaster
    s_dTargetL0_active: drop
    s_dTargetL1_active: drop
    s_dTargetL2_active: drop
    s_dTargetL3_active: drop
    s_dTargetR0_active: drop
    s_dTargetR1_active: drop
    s_dTargetR2_active: drop
    s_dTargetR3_active: drop
    s_dtargetcl_active: drop
    s_dtargetcr_active: drop
    start_base_music:
      overture:
          action: play
          loops: -1
          mode_end_action: stop
    mode_selector_stopped:
      overture:
          action: stop
    bonus_start:
      overture:
          action: stop
    do_scoop_notify{current_player.score>25000}: scene_ready
    s_spinner_active: laser_pistol
    s_roInLaneRight_active: swoosh
    s_roInLaneLeft_active: swoosh
    s_rooutlaneleft_active: drainout
    s_rooutlaneright_active: drainout
    s_lane0_active: swoosh
    s_lane1_active: swoosh
    s_lane2_active: swoosh
    s_lane3_active: swoosh
    s_lane4_active: swoosh
    ball_will_end: ball_end_clips
    mode_base_started{player==1}: player_one_up
    mode_base_started{player==2}: player_two_up
    mode_base_started{player==3}: player_three_up
    mode_base_started{player==4}: player_four_up

show_player:
  mode_base_started:
      giWhite:
          loops: -1
      title_on:
          loops: -1
      bh_on:
          priority: 5
          loops: -1
      stars_on:
          priority: 5
          loops: -1
      cygnus_on:
          priority: 200
          loops: -1
#      robots_on:
#          priority: 200
#          loops: -1
  mode_base_started{player==1 and ball==1 and is_extra_ball==0}:
      start_button:
          loops: -1
          priority: 5
  s_slingshot_left_active:
      redHitShow:
          priority: 101
          loops: 0
          speed: 10
          show_tokens:
            light0: l_GISlingLeft0
            light1: l_GISlingLeft1
  s_slingshot_right_active:
      redHitShow:
          priority: 101
          loops: 0
          speed: 10
          show_tokens:
            light0: l_GISlingRight0
            light1: l_GISlingRight1
  shotgrouplefttargets_hit:
      redHitShow:
          priority: 101
          loops: 0
          speed: 10
          show_tokens:
            light0: l_GIDropLeft0
            light1: l_GIDropLeft1
  shotgrouprighttargets_hit:
      redHitShow:
          priority: 101
          loops: 0
          speed: 10
          show_tokens:
            light0: l_GIDropRight0
            light1: l_GIDropRight1
  s_dtargetcr_active:
      redHitShow:
          priority: 101
          loops: 0
          speed: 10
          show_tokens:
            light0: l_GIDropCenterRight
  s_dtargetcl_active:
      redHitShow:
          priority: 101
          loops: 0
          speed: 10
          show_tokens:
            light0: l_GIDropCenterLeft
  s_sTargetDropR_active:
      redHitShow:
          priority: 101
          loops: 0
          speed: 10
          show_tokens:
            light0: l_GIDropRight0
            light1: l_GIDropRight1
  s_sTargetDropL_active:
      redHitShow:
          priority: 101
          loops: 0
          speed: 10
          show_tokens:
            light0: l_GIDropLeft0
            light1: l_GIDropLeft1
  s_sTargetLowR_active:
      redHitShow:
          priority: 101
          loops: 0
          speed: 10
          show_tokens:
            light0: l_GILowRight
  s_sTargetLowL_active:
      redHitShow:
          priority: 101
          loops: 0
          speed: 10
          show_tokens:
            light0: l_GILowLeft
  s_sTargetUpperR_active:
      redHitShow:
          priority: 101
          loops: 0
          speed: 10
          show_tokens:
            light0: l_GIAboveSpinnerUpper
  s_sTargetUpperL_active:
      redHitShow:
          priority: 102
          loops: 0
          speed: 10
          show_tokens:
            light0: l_GIScoopMR
            light1: l_GIScoopLR
  shotScoop_scoopReady_hit:
      scoop_show:
          priority: 275
          loops: 0
          events_when_completed: select_mode_start
  shotScoop_scoopNotReady_hit:
      scoop_eject_sound_show:
          priority: 275
          loops: 0
          events_when_completed: scoop_eject, global_timer_unpause
      scoop_eject_light_show:
          priority: 275
          loops: 0
##########################
# Moved to BASE mode to avoid other mode exiting before handling
##########################
  shotScoopOverride_hit:
      scoop_eject_sound_show:
          priority: 950
          loops: 0
          events_when_completed: scoop_eject, local_timer_unpause
      scoop_eject_light_show:
          priority: 950
          loops: 0
  generic_scoop_eject_trigger:
      scoop_eject_sound_show:
          priority: 950
          loops: 0
          events_when_completed: scoop_eject, local_timer_unpause
      scoop_eject_light_show:
          priority: 950
          loops: 0

  extra_ball_is_lit:
      extra_lit:
          loops: -1
  extra_ball_is_earned:
      extra_lit:
          action: stop
      extra_earned:
          loops: -1
  player_score{value>0 and prev_value==0 and change!=0}:
      start_button:
        action: stop
      start_off:
        loops: -1
        priority: 10
  player_added{num==4}:
      start_off:
        loops: -1
        priority: 10
  player_bonus_l2{value==0}:
      bonusL2:
        loops: -1
        show_tokens:
          color: 000000
  player_bonus_l2{value==1}:
      bonusL2:
        loops: -1
        show_tokens:
          color: CC0000
  player_bonus_l2{value==2}:
      bonusL2:
        loops: -1
        show_tokens:
          color: 00CC00
  player_bonus_l2{value==3}:
      bonusL2:
        loops: -1
        show_tokens:
          color: 0000CC
  player_bonus_l3{value==0}:
      bonusL3:
        loops: -1
        show_tokens:
          color: 000000
  player_bonus_l3{value==1}:
      bonusL3:
        loops: -1
        show_tokens:
          color: CC0000
  player_bonus_l3{value==2}:
      bonusL3:
        loops: -1
        show_tokens:
          color: 00CC00
  player_bonus_l3{value==3}:
      bonusL3:
        loops: -1
        show_tokens:
          color: 0000CC
  player_bonus_l4{value==0}:
      bonusL4:
        loops: -1
        show_tokens:
          color: 000000
  player_bonus_l4{value==1}:
      bonusL4:
        loops: -1
        show_tokens:
          color: CC0000
  player_bonus_l4{value==2}:
      bonusL4:
        loops: -1
        show_tokens:
          color: 00CC00
  player_bonus_l4{value==3}:
      bonusL4:
        loops: -1
        show_tokens:
          color: 0000CC
  player_bonus_l5{value==0}:
      bonusL5:
        loops: -1
        show_tokens:
          color: 000000
  player_bonus_l5{value==1}:
      bonusL5:
        loops: -1
        show_tokens:
          color: CC0000
  player_bonus_l5{value==2}:
      bonusL5:
        loops: -1
        show_tokens:
          color: 00CC00
  player_bonus_l5{value==3}:
      bonusL5:
        loops: -1
        show_tokens:
          color: 0000CC


shows:
  scoop_show:
     - time: 0
       slides: scoop_slide
  extra_lit:
     - time: 0
       lights:
         l_shootAgain: red
     - time: +1
       lights:
         l_shootAgain: off
  extra_earned:
     - time: 0
       lights:
         l_shootAgain: green
  bonusL2:
     - time: 0
       lights:
         l_2x: (color)
  bonusL3:
     - time: 0
       lights:
         l_3x: (color)
  bonusL4:
     - time: 0
       lights:
         l_4x: (color)
  bonusL5:
     - time: 0
       lights:
         l_5x: (color)

