#config_version=5
config:
  - achievements.yaml
  - scoring.yaml
  - statemachines.yaml

mode:
  start_events: ball_starting
  priority: 100
  file_log: full

slide_player:
  mode_base_started: scoring_slide
#  scoop_slide: s_ir_scoop_detect_active

widget_player:
   s_jet_upper_left_active:
      sample_quick_vid:
         slide: scoring_slide
         widget_settings:
           expire: 2s

slides:
   scoring_slide:
    widgets:
      - type: image
        image: logo
        x: 150
        y: 650
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
        font_name: ocr-a-tribute-bold
        y: 40%
      - type: text
        text: PLAYER (number)
        y: 10
        x: 10
        font_size: 50
        font_name: ocr-a-tribute-bold
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 10
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_size: 50
        font_name: ocr-a-tribute-bold
      - type: text
        text: "Bonus Value (pds)"
        y: 30%
      - type: text
        text: "Bonus Count: (bonuscount)"
        y: 25%
      - type: text
        text: "BONUS X: (bonus_multiplier)"
        font_size: 30
        y: 20%
   scoop_slide:
    widgets:
      - type: text
        text: SCOOP MADNESS
        color: red
        font_size: 100
        font_name: ocr-a-tribute-bold
    expire: 3s

timers:
  targetRotator:
   start_value: 0
   tick_interval: 2s
   control_events:
     - event: mode_base_started
       action: start

shots:
  shotCenterPop:
    switch: s_jet_lower_center
    show_tokens:
      light: l_jetLowerCenter
    profile: shotProfilePops
  shotUpperLeftPop:
    switch: s_jet_upper_left
    show_tokens:
      light: l_jetUpperLeft
    profile: shotProfilePops
  shotUpperRightPop:
    switch: s_jet_upper_right
    show_tokens:
      light: l_jetUpperRight
    profile: shotProfilePops
  shotLane0:
    switch: s_lane0
    show_tokens:
      light: l_lane0
    profile: shotProfileToplanes
  shotLane1:
    switch: s_lane1
    show_tokens:
      light: l_lane1
    profile: shotProfileToplanes
  shotLane2:
    switch: s_lane2
    show_tokens:
      light: l_lane2
    profile: shotProfileToplanes
  shotLane3:
    switch: s_lane3
    show_tokens:
      light: l_lane3
    profile: shotProfileToplanes
  shotLane4:
    switch: s_lane4
    show_tokens:
      light: l_lane4
    profile: shotProfileToplanes
  shotTargetL0:
    switch: s_dTargetL0
    show_tokens:
      light: l_dropLeft0
    profile: shotProfileLeftTargets
    advance_events: lt0_flash_start, lt0_lit_start
    reset_events: lt0_off_start, shotTargetL0_unlit_hit
  shotTargetL1:
    switch: s_dTargetL1
    show_tokens:
      light: l_dropLeft1
    profile: shotProfileLeftTargets
    advance_events: lt1_flash_start, lt1_lit_start
    reset_events: lt1_off_start, shotTargetL1_unlit_hit
  shotTargetL2:
    switch: s_dTargetL2
    show_tokens:
      light: l_dropLeft2
    profile: shotProfileLeftTargets
    advance_events: lt2_flash_start, lt2_lit_start
    reset_events: lt2_off_start, shotTargetL2_unlit_hit
  shotTargetL3:
    switch: s_dTargetL3
    show_tokens:
      light: l_dropLeft3
    profile: shotProfileLeftTargets
    advance_events: lt3_flash_start, lt3_lit_start
    reset_events: lt3_off_start, shotTargetL3_unlit_hit
  shotTargetR0:
    switch: s_dTargetR0
    show_tokens:
      light: l_dropRight0
    profile: shotProfileRightTargets
    advance_events: rt0_flash_start, rt0_lit_start
    reset_events: rt0_off_start, shotTargetR0_unlit_hit
  shotTargetR1:
    switch: s_dTargetR1
    show_tokens:
      light: l_dropRight1
    profile: shotProfileRightTargets
    advance_events: rt1_flash_start, rt1_lit_start
    reset_events: rt1_off_start, shotTargetR1_unlit_hit
  shotTargetR2:
    switch: s_dTargetR2
    show_tokens:
      light: l_dropRight2
    profile: shotProfileRightTargets
    advance_events: rt2_flash_start, rt2_lit_start
    reset_events: rt2_off_start, shotTargetR2_unlit_hit
  shotTargetR3:
    switch: s_dTargetR3
    show_tokens:
      light: l_dropRight3
    profile: shotProfileRightTargets
    advance_events: rt3_flash_start, rt3_lit_start
    reset_events: rt3_off_start, shotTargetR3_unlit_hit
  shotScoop:
    switch: s_ir_scoop_detect
    show_tokens:
      light: l_scoop
    profile: shotProfileScoop
    advance_events: selector_item_selected, ach_completed, story_mode_completed
    enable_events: mode_base_started, scoop_reset
    disable_events: selector_item_selected
    reset_events: scoop_reset

event_player:
    shotGroupToplanes_lit_complete:
      - scoop_reset
    drop_target_bank_leftfull_down:
      - scoop_reset
    drop_target_bank_rightfull_down:
      - scoop_reset
    gravityAssistBonus:
      - scoop_reset
    mode_story01_stopped:
      - story_mode_completed
    achievement_untitled_mode_1_state_completed:
      - ach_completed
    mode_story02_stopped:
      - story_mode_completed
    achievement_untitled_mode_2_state_completed:
      - ach_completed
    mode_story03_stopped:
      - story_mode_completed
    achievement_untitled_mode_3_state_completed:
      - ach_completed
    mode_story04_stopped:
      - story_mode_completed
    achievement_untitled_mode_4_state_completed:
      - ach_completed
    mode_story05_stopped:
      - story_mode_completed
    achievement_untitled_mode_5_state_completed:
      - ach_completed
    mode_story06_stopped:
      - story_mode_completed
    achievement_untitled_mode_6_state_completed:
      - ach_completed
    mode_story07_stopped:
      - story_mode_completed
    achievement_untitled_mode_7_state_completed:
      - ach_completed

# shotGroupPopBumpers_popBumpBlue_complete
# shotGroupPopBumpers_popBumpGreen_complete
# shotGroupPopBumpers_popBumpRed_complete

shot_profiles:
  shotProfileLeftTargets:
    show_when_disabled: true
    states:
      - name: unlit
        show: off
      - name: flashing
        show: dk_blu_flash
        speed: 4
      - name: lit
        show: dk_blu_on
  shotProfileRightTargets:
    show_when_disabled: true
    states:
      - name: unlit
        show: off
      - name: flashing
        show: dk_blu_flash
        speed: 4
      - name: lit
        show: dk_blu_on
  shotProfileToplanes:
    states:
      - name: unlit
        show: off
      - name: lit
        show: dk_blu_on
    loop: false
  shotProfilePops:
    states:
      - name: popBumpRed
        show: popred
      - name: popBumpBlue
        show: popblue
      - name: popBumpGreen
        show: popgreen
    loop: true
  shotProfileScoop:
    advance_on_hit: false
    states:
      - name: scoopReady
        show: scoopReadyShow
        speed: 2
        priority: 101
      - name: scoopActive
        show: popgreen
      - name: scoopNotReady
        show: off

shot_groups:
   shotGroupPopBumpers:
       shots: shotCenterPop, shotUpperLeftPop, shotUpperRightPop
   shotGroupToplanes:
       shots: shotLane0, shotLane1, shotLane2, shotLane3, shotLane4
       rotate_left_events: s_flipper_left_active
       rotate_right_events: s_flipper_right_active
       reset_events: shotGroupToplanes_lit_complete
       enable_events: ball_started
       disable_events: ball_ending
   shotGroupLeftTargets:
       shots: shotTargetL0, shotTargetL1, shotTargetL2, shotTargetL3
       reset_events: reset_both_lane_lit_groups
       enable_events: ball_started
       disable_events: ball_ending
   shotGroupRightTargets:
       shots: shotTargetR0, shotTargetR1, shotTargetR2, shotTargetR3
       reset_events: reset_both_lane_lit_groups
       enable_events: ball_started
       disable_events: ball_ending

sound_player:
    s_slingshot_left_active: testFX1
    s_slingshot_right_active: testFX1
    s_jet_lower_center_active: testFX3
    s_jet_upper_right_active: testFX3
    s_jet_upper_left_active: testFX3
    mode_base_started:
      overture:
          action: play
          loops: -1
          mode_end_action: stop

show_player:
  mode_base_started:
      giWhite:
          loops: -1
  s_slingshot_left_active:
      redHitShow:
          priority: 101
          loops: 0
          speed: 10
          show_tokens:
            light0: l_GISlingLeft0
            light1: l_GISlingLeft1
  s_slingshot_right_active:
      redHitShow:
          priority: 101
          loops: 0
          speed: 10
          show_tokens:
            light0: l_GISlingRight0
            light1: l_GISlingRight1
  shotgrouplefttargets_hit:
      redHitShow:
          priority: 101
          loops: 0
          speed: 10
          show_tokens:
            light0: l_GIDropLeft0
            light1: l_GIDropLeft1
  shotgrouprighttargets_hit:
      redHitShow:
          priority: 101
          loops: 0
          speed: 10
          show_tokens:
            light0: l_GIDropRight0
            light1: l_GIDropRight1
  s_dtargetcr_active:
      redHitShow:
          priority: 101
          loops: 0
          speed: 10
          show_tokens:
            light0: l_GIDropCenterRight
  s_dtargetcl_active:
      redHitShow:
          priority: 101
          loops: 0
          speed: 10
          show_tokens:
            light0: l_GIDropCenterLeft
  s_sTargetDropR_active:
      redHitShow:
          priority: 101
          loops: 0
          speed: 10
          show_tokens:
            light0: l_GIDropRight0
            light1: l_GIDropRight1
  s_sTargetDropL_active:
      redHitShow:
          priority: 101
          loops: 0
          speed: 10
          show_tokens:
            light0: l_GIDropLeft0
            light1: l_GIDropLeft1
  s_sTargetLowR_active:
      redHitShow:
          priority: 101
          loops: 0
          speed: 10
          show_tokens:
            light0: l_GILowRight
  s_sTargetLowL_active:
      redHitShow:
          priority: 101
          loops: 0
          speed: 10
          show_tokens:
            light0: l_GILowLeft
  s_sTargetUpperR_active:
      redHitShow:
          priority: 101
          loops: 0
          speed: 10
          show_tokens:
            light0: l_GIAboveSpinnerUpper
  s_sTargetUpperL_active:
      redHitShow:
          priority: 102
          loops: 0
          speed: 10
          show_tokens:
            light0: l_GIScoopMR
            light1: l_GIScoopLR
  shotScoop_scoopReady_hit:
      scoop_show:
          loops: 0
          events_when_completed: select_mode_start
  shotScoop_scoopActive_hit:
      scoop_show_ip:
          loops: 0
          events_when_completed: scoop_eject
  shotScoop_scoopNotReady_hit:
      scoop_show_nr:
          loops: 0
          events_when_completed: scoop_eject
  extra_ball_is_lit:
      extra_lit:
          loops: -1
  extra_ball_is_earned:
      extra_lit:
          action: stop
      extra_earned:
          loops: -1

  player_bonus_l2{value==0}:
      bonusL2:
        loops: -1
        show_tokens:
          color: 000000
  player_bonus_l2{value==1}:
      bonusL2:
        loops: -1
        show_tokens:
          color: CC0000
  player_bonus_l2{value==2}:
      bonusL2:
        loops: -1
        show_tokens:
          color: 00CC00
  player_bonus_l2{value==3}:
      bonusL2:
        loops: -1
        show_tokens:
          color: 0000CC

  player_bonus_l3{value==0}:
      bonusL3:
        loops: -1
        show_tokens:
          color: 000000
  player_bonus_l3{value==1}:
      bonusL3:
        loops: -1
        show_tokens:
          color: CC0000
  player_bonus_l3{value==2}:
      bonusL3:
        loops: -1
        show_tokens:
          color: 00CC00
  player_bonus_l3{value==3}:
      bonusL3:
        loops: -1
        show_tokens:
          color: 0000CC

  player_bonus_l4{value==0}:
      bonusL4:
        loops: -1
        show_tokens:
          color: 000000
  player_bonus_l4{value==1}:
      bonusL4:
        loops: -1
        show_tokens:
          color: CC0000
  player_bonus_l4{value==2}:
      bonusL4:
        loops: -1
        show_tokens:
          color: 00CC00
  player_bonus_l4{value==3}:
      bonusL4:
        loops: -1
        show_tokens:
          color: 0000CC

  player_bonus_l5{value==0}:
      bonusL5:
        loops: -1
        show_tokens:
          color: 000000
  player_bonus_l5{value==1}:
      bonusL5:
        loops: -1
        show_tokens:
          color: CC0000
  player_bonus_l5{value==2}:
      bonusL5:
        loops: -1
        show_tokens:
          color: 00CC00
  player_bonus_l5{value==3}:
      bonusL5:
        loops: -1
        show_tokens:
          color: 0000CC


shows:
  scoop_show:
     - time: 0
       slides: scoop_slide
       lights:
         l_2x: red
         l_3x: red
         l_4x: red
         l_5x: red
     - time: +1
       lights:
         l_2x: blue
         l_3x: blue
         l_4x: blue
         l_5x: blue
     - time: +1
       lights:
         l_2x: green
         l_3x: green
         l_4x: green
         l_5x: green
  scoop_show_ip:
     - time: 0
       lights:
         l_2x: green
         l_3x: green
         l_4x: green
         l_5x: green
  scoop_show_nr:
     - time: 0
       lights:
         l_2x: red
         l_3x: red
         l_4x: red
         l_5x: red
  extra_lit:
     - time: 0
       lights:
         l_shootAgain: red
     - time: +1
       lights:
         l_shootAgain: off
  extra_earned:
     - time: 0
       lights:
         l_shootAgain: green
  bonusL2:
     - time: 0
       lights:
         l_2x: (color)
  bonusL3:
     - time: 0
       lights:
         l_3x: (color)
  bonusL4:
     - time: 0
       lights:
         l_4x: (color)
  bonusL5:
     - time: 0
       lights:
         l_5x: (color)
