#config_version=5

# Control behavior of Center Drop Targets, Yellow Targets, and Outlane Lighting

event_player:
   mode_base_started{ball==1 and is_extra_ball==0}:
     - ball1_ct1
     - ball1_ct2
     - ball1_ct3
   s_dtargetcr_active:
     - drop_left_center_reset
     - count_center_drop
   s_dtargetcl_active:
     - drop_right_center_reset
     - count_center_drop
   s_sTargetYellowL_active:
     - drop_right_center_reset
     - reenable_outlane_rescue
   s_sTargetYellowR_active:
     - drop_left_center_reset
     - reenable_outlane_sacrifice

variable_player:
   ball1_ct1:
     debug_rescue_count:
        action: add
        int: 1
   ball1_ct2:
     debug_rescue_count:
        action: add
        int: 1
   ball1_ct3:
     debug_rescue_count:
        action: add
        int: 1
   count_center_drop:
     debug_rescue_count:
        action: add
        int: 1
     debug_sacrifice_count:
        action: add
        int: 1

counters:
   center_drop_rescue:
     count_events: count_center_drop, ball1_ct1, ball1_ct2, ball1_ct3
     count_complete_value: 6
     events_when_complete: reenable_outlane_sacrifice
     persist_state: true
     reset_on_complete: true
     disable_on_complete: false
   center_drop_sac:
     count_events: count_center_drop
     count_complete_value: 6
     persist_state: true
     events_when_complete: reenable_outlane_rescue
     reset_on_complete: true
     disable_on_complete: false

