#config_version=5

# Control behavior of Center Drop Targets, Yellow Targets, and Outlane Lighting

event_player:
   mode_base_started{ball==1 and is_extra_ball==0}:
     - ball1_ct1
     - ball1_ct2
     - ball1_ct3
   s_dTargetCR_active:
     - drop_left_center_reset
     - count_center_drop
   s_dTargetCL_active:
     - drop_right_center_reset
     - count_center_drop
   s_sTargetYellowL_active:
     - drop_right_center_reset
     - reenable_outlane_rescue
   s_sTargetYellowR_active:
     - drop_left_center_reset
     - reenable_outlane_sacrifice

#TODO Add some points for hitting these targets!!!
counters:
   center_drop_rescue:
     count_events: count_center_drop, ball1_ct1, ball1_ct2, ball1_ct3
     count_complete_value: 6
     events_when_complete: reenable_outlane_sacrifice
     persist_state: true
   center_drop_sac:
     count_events: count_center_drop
     count_complete_value: 6
     persist_state: true
     events_when_complete: reenable_outlane_rescue

