#config_version=5

#TODO -- These outro widgets are all pretty junky and would benefit from standardizaion as well as a set of widget styles.
#NOTE -- All Widget Styles must be created in main/config/widget_styles.yaml - they don't seem to work at lower levels

widgets:
#  MODE EXIT BASE
   mode_exit_container:
      - type: image
        image: mode_title_exit_box
        anchor_x: center
        anchor_y: center
        y: 52.5%
        z: 49

#  MODE 01 -- LOCATE THE CYGNUS
   cygnus_located_outro:
      - type: text
        text: "CYGNUS LOCATED"
        style:
           - mode_outro_title
      - type: text
        text: "Time Taken: (cygnus_seconds) seconds"
        style:
           - mode_outro_data_line_1
      - type: text
        text: "Mode Scoring: (modestat_1_scoring)"
        style:
           - mode_outro_data_line_2
#      - type: video
#        video: test
#        style:
#           - mode_outro_video
# width/height values don't seem to work in widget styles
#        width: 400
#        height: 300
   cygnus_failed_outro:
      - type: text
        text: "CYGNUS NOT LOCATED"
        style:
           - mode_outro_title
      - type: text
        text: "MISSION FAILURE"
        style:
           - mode_outro_data_line_1
#  MODE 02 -- ESCAPE THE BLACK HOLE
   story_02_outro_fail_widget:
      - type: text
        text: ESCAPE THE BLACK HOLE FAILED
        style:
           - mode_outro_title
      - type: text
        text: You are *NOT* super duper neat
        style:
           - mode_outro_data_line_1
   story_02_outro_widget:
      - type: text
        text: BLACK HOLE ESCAPED
        style:
           - mode_outro_title
      - type: text
        text: (mode2_final_score_display)
        style:
           - mode_outro_data_line_1
#  MODE 03 -- SHOOTING GALLERY
   story_03_outro_fail_widget:
      - type: text
        text: SHOOTING GALLERY FAILED
        style:
           - mode_outro_title
      - type: text
        text: "If one dances, one MUST pay the piper."
        y: 30%
        font_size: 50
        z: 50
   story_03_outro_widget:
      - type: text
        text: SHOOTING GALLERY DONE
        style:
           - mode_outro_title
      - type: text
        text: "Meet me in parts storage..."
        style:
           - mode_outro_data_line_1
      - type: text
        text: "Targets Hit: (gallery_targets_hit)"
        style:
           - mode_outro_data_line_2
#  MODE 04 -- METEOR STRIKE
   story_04_outro_fail_widget:
      - type: text
        text: METEOR STRIKE FAILED
        style:
           - mode_outro_title
      - type: text
        text: You are sent home in a space box
        style:
           - mode_outro_data_line_1
   story_04_outro_widget:
      - type: text
        text: METEOR STRIKE PASSED
        style:
           - mode_outro_title
      - type: text
        text: "Meteor Scoring: (meteor_accum)"
        style:
           - mode_outro_data_line_1
#  MODE 05 -- CORRIDOR BATTLE
   story_05_outro_widget:
      - type: text
        text: CORRIDOR BATTLE ENDED
        style:
           - mode_outro_title
      - type: text
        text: "Remaining Time (corridor_seconds)s"
        style:
           - mode_outro_data_line_1
      - type: text
        text: "Bonus for remaining time: (corridor_bonus)"
        style:
           - mode_outro_data_line_2
   story_05_outro_fail_widget:
      - type: text
        text: CORRIDOR BATTLE LOST
        style:
           - mode_outro_title
      - type: text
        text: "You are bad and should feel bad."
        style:
           - mode_outro_data_line_1
#  MODE 06 -- DAVID VS GOLIATH
   story_06_outro_fail_widget:
      - type: text
        text: Goliath defeats David
        style:
           - mode_outro_title
      - type: text
        text: Only this time, David is overmatched...
        style:
           - mode_outro_data_line_1
   story_06_outro_widget:
      - type: text
        text: David defeats Goliath!
        style:
           - mode_outro_title
      - type: text
        text: "The bigger they are, the harder they fall. [Time taken:(battletime)s]"
        style:
           - mode_outro_data_line_1