#config_version=5

#TODO -- These outro widgets are all pretty junky and would benefit from standardizaion as well as a set of widget styles.
#NOTE -- All Widget Styles must be created in main/config/widget_styles.yaml - they don't seem to work at lower levels

widgets:
#  MODE EXIT BASE
   mode_exit_container:
      - type: image
        image: mode_title_exit_box
        anchor_x: center
        anchor_y: center
        y: 52.5%
        z: 40

# MODE EXIT WIDGETS
#   mode_01_outro_video:
#     - type: video
#       video: ltc_success
#       volume: 1
#       width: 683
#       height: 344
#       z: 50
#   mode_02_outro_video:
#     - type: video
#       video: etbh_success
#       volume: 1
#       width: 683
#       height: 344
#       z: 50
#   mode_03_outro_video:
#     - type: video
#       video: sg_success
#       volume: 1
#       width: 683
#       height: 344
#       z: 50
#   mode_04_outro_video:
#     - type: video
#       video: ms_success
#       volume: 1
#       width: 683
#       height: 344
#       z: 50
#   mode_05_outro_video:
#     - type: video
#       video: cb_success
#       volume: 1
#       width: 683
#       height: 344
#       z: 50
#   mode_06_outro_video:
#     - type: video
#       video: dg_success
#       volume: 1
#       width: 683
#       height: 344
#       z: 50

#  MODE 01 -- LOCATE THE CYGNUS
   cygnus_located_outro:
      - type: text
        text: "CYGNUS LOCATED"
        style:
           - mode_outro_title
      - type: text
        text: "Time Taken: (cygnus_seconds) seconds"
        style:
           - mode_outro_data_line_1
      - type: text
        text: "Mode Scoring: (modestat_1_scoring)"
        style:
           - mode_outro_data_line_2
   cygnus_failed_outro:
      - type: text
        text: "CYGNUS NOT LOCATED"
        style:
           - mode_outro_title
      - type: text
        text: "The story is over before it even began."
        style:
           - mode_outro_data_line_1
#  MODE 02 -- ESCAPE THE BLACK HOLE
   story_02_outro_widget:
      - type: text
        text: "BLACK HOLE ESCAPED"
        style:
           - mode_outro_title
      - type: text
        text: "Mode Scoring: (modestat_2_scoring)"
        style:
           - mode_outro_data_line_1
   story_02_outro_fail_widget:
      - type: text
        text: "THE BLACK HOLE IS INESCAPABLE"
        style:
           - mode_outro_title
      - type: text
        text: "The black hole has destroyed the Palomino."
        style:
           - mode_outro_data_line_1

#  MODE 03 -- SHOOTING GALLERY
   story_03_outro_widget:
      - type: text
        text: "CAPTAIN S.T.A.R. IS DEFEATED"
        style:
           - mode_outro_title
      - type: text
        text: "Mode Scoring: (modestat_3_scoring)"
        style:
           - mode_outro_data_line_1
      - type: text
        text: "Targets Hit: (gallery_targets_hit)"
        style:
           - mode_outro_data_line_2
   story_03_outro_fail_widget:
      - type: text
        text: "CAPTAIN S.T.A.R. REMAINS UNDEFEATED"
        style:
           - mode_outro_title
      - type: text
        text: "If one dances, one MUST pay the piper."
        style:
           - mode_outro_data_line_1
#  MODE 04 -- METEOR STRIKE
   story_04_outro_widget:
      - type: text
        text: "METEOR STRIKE EVADED"
        style:
           - mode_outro_title
      - type: text
        text: "Mode Scoring: (modestat_4_scoring)"
        style:
           - mode_outro_data_line_2
   story_04_outro_fail_widget:
      - type: text
        text: "METEOR STRICKEN"
        style:
           - mode_outro_title
      - type: text
        text: "The meteor ripped through the corridor... with you still in it."
        style:
           - mode_outro_data_line_1

#  MODE 05 -- CORRIDOR BATTLE
   story_05_outro_widget:
      - type: text
        text: "CORRIDOR BATTLE WON"
        style:
           - mode_outro_title
      - type: text
        text: "Bonus for remaining time: (corridor_bonus)"
        style:
           - mode_outro_data_line_1
      - type: text
        text: "Mode Scoring: (modestat_5_scoring)"
        style:
           - mode_outro_data_line_2
   story_05_outro_fail_widget:
      - type: text
        text: "CORRIDOR BATTLE LOST"
        style:
           - mode_outro_title
      - type: text
        text: "The robots pinned you down and eliminated you."
        style:
           - mode_outro_data_line_1
#  MODE 06 -- DAVID VS GOLIATH
   story_06_outro_widget:
      - type: text
        text: "VINCENT PREVAILS"
        style:
           - mode_outro_title
      - type: text
        text: "The bigger they are, the harder they fall. [Time taken:(battletime)s]"
        style:
           - mode_outro_data_line_1
      - type: text
        text: "Mode Scoring: (modestat_6_scoring)"
        style:
           - mode_outro_data_line_2
   story_06_outro_fail_widget:
      - type: text
        text: "MAXIMILIAN PREVAILS"
        style:
           - mode_outro_title
      - type: text
        text: "Only this time, David is overmatched..."
        style:
           - mode_outro_data_line_1
