#config_version=5

accruals:
  bonusAllow:
    events:
      - shotGroupToplanes_lit_complete
      - drop_target_bank_leftfull_down
      - drop_target_bank_rightfull_down
      - gravityAssistBonus
    events_when_complete: bonus_reset_achieved
    reset_on_complete: true
    disable_on_complete: false
  enableWizard:
    persist_state: true
    events:
      - acheivement_story01_successful
      - acheivement_story02_successful
      - acheivement_story03_successful
      - acheivement_story04_successful
      - acheivement_story05_successful
      - acheivement_story06_successful
    events_when_complete: enableWizardMode

counters:
  spinPop:
    enable_events: mode_base_started
    count_events: s_spinner_active, s_jet_upper_left_active, s_jet_upper_right_active:, s_jet_lower_center_active
    starting_count: 50
    count_complete_value: 0
    direction: down
    events_when_complete: gravityAssistBonus
    reset_on_complete: true
    disable_on_complete: false
    multiple_hit_window: 10ms

variable_player:
# This should tell the NOTIFY mode to add a scoop shot active box!
  do_scoop_notify:
    bonus_box_new_value:
       string: "ACTIVE"
    bonus_box_new_text:
       string: "SCOOP\nSHOT"
    bonus_box_counter: 1



  mode_base_started:
    pds:
       int: 100
       action: set
    bonustype1:
       int: 0
       action: set
    bonustype2:
       int: 0
       action: set
    bonustype3:
       int: 0
       action: set
    bonustype4:
       int: 0
       action: set
    bonuscount:
       int: 1
       action: set
    bonuscountdisplay:
       int: 0
       action: set
    bonus_multiplier:
       int: 1
       action: set
    bonus_l2:
       int: 0
       action: set
    bonus_l3:
       int: 0
       action: set
    bonus_l4:
       int: 0
       action: set
    bonus_l5:
       int: 0
       action: set

# -- Gravity Assist - Scoops
    gravassistTarget:
       int: 4
       action: set
    gravassist:
       int: 0
       action: set
    gravassistLevel:
       int: 1
       action: set

# -- Inertial Boost
    popsTarget:
       int: 20
       action: set
    pops:
       int: 0
       action: set
    popsLevel:
       int: 1
       action: set

# Coordinate Locks
    lanesTarget:
       int: 10
       action: set
    lanes:
       int: 0
       action: set
    lanesLevel:
       int: 1
       action: set

# Robots
    dropsTarget:
       int: 10
       action: set
    drops:
       int: 0
       action: set
    dropsLevel:
       int: 1
       action: set

# Gyro
    spinsTarget:
       int: 20
       action: set
    spins:
       int: 0
       action: set
    spinsLevel:
       int: 1
       action: set



  s_jet_upper_left_active:
    score: 100 * current_player.popsLevel
  s_jet_upper_right_active:
    score: 100 * current_player.popsLevel
  s_jet_lower_center_active:
    score: 100 * current_player.popsLevel

  s_slingshot_left_active:
    score: 50
  s_slingshot_right_active:
    score: 50

  shotGroupLeftTargets_unlit_hit:
    score: 100 * current_player.dropsLevel
    bonuscount: 1
  shotGroupLeftTargets_lit_hit:
    score: 250 * current_player.dropsLevel
    bonuscount: 1
  shotGroupLeftTargets_flashing_hit:
    score: 1000 * current_player.dropsLevel
    bonuscount: 1

  shotGroupRightTargets_unlit_hit:
    score: 100 * current_player.dropsLevel
    bonuscount: 1
  shotGroupRightTargets_lit_hit:
    score: 250 * current_player.dropsLevel
    bonuscount: 1
  shotGroupRightTargets_flashing_hit:
    score: 1000 * current_player.dropsLevel
    bonuscount: 1

#  shotTargetL0_unlit_hit:
#    score: 100 * current_player.dropsLevel
#    bonuscount: 1
#  shotTargetL1_unlit_hit:
#    score: 100 * current_player.dropsLevel
#    bonuscount: 1
#  shotTargetL2_unlit_hit:
#    score: 100 * current_player.dropsLevel
#    bonuscount: 1
#  shotTargetL3_unlit_hit:
#    score: 100 * current_player.dropsLevel
#    bonuscount: 1
#  shotTargetL0_flashing_hit:
#    score: 1000 * current_player.dropsLevel
#    bonuscount: 1
#  shotTargetL1_flashing_hit:
#    score: 1000 * current_player.dropsLevel
#    bonuscount: 1
#  shotTargetL2_flashing_hit:
#    score: 1000 * current_player.dropsLevel
#    bonuscount: 1
#  shotTargetL3_flashing_hit:
#    score: 1000 * current_player.dropsLevel
#    bonuscount: 1
#  shotTargetL0_lit_hit:
#    score: 250 * current_player.dropsLevel
#    bonuscount: 1
#  shotTargetL1_lit_hit:
#    score: 250 * current_player.dropsLevel
#    bonuscount: 1
#  shotTargetL2_lit_hit:
#    score: 250 * current_player.dropsLevel
#    bonuscount: 1
#  shotTargetL3_lit_hit:
#    score: 250 * current_player.dropsLevel
#    bonuscount: 1

  shotTargetR0_unlit_hit:
    score: 100 * current_player.dropsLevel
    bonuscount: 1
  shotTargetR1_unlit_hit:
    score: 100 * current_player.dropsLevel
    bonuscount: 1
  shotTargetR2_unlit_hit:
    score: 100 * current_player.dropsLevel
    bonuscount: 1
  shotTargetR3_unlit_hit:
    score: 100 * current_player.dropsLevel
    bonuscount: 1
  shotTargetR0_flashing_hit:
    score: 1000 * current_player.dropsLevel
    bonuscount: 1
  shotTargetR1_flashing_hit:
    score: 1000 * current_player.dropsLevel
    bonuscount: 1
  shotTargetR2_flashing_hit:
    score: 1000 * current_player.dropsLevel
    bonuscount: 1
  shotTargetR3_flashing_hit:
    score: 1000 * current_player.dropsLevel
    bonuscount: 1
  shotTargetR0_lit_hit:
    score: 250 * current_player.dropsLevel
    bonuscount: 1
  shotTargetR1_lit_hit:
    score: 250 * current_player.dropsLevel
    bonuscount: 1
  shotTargetR2_lit_hit:
    score: 250 * current_player.dropsLevel
    bonuscount: 1
  shotTargetR3_lit_hit:
    score: 250 * current_player.dropsLevel
    bonuscount: 1

  s_roInLaneLeft_active:
    score: 500
    bonuscount: 1
  s_roInLaneRight_active:
    score: 500
    bonuscount: 1
  s_roOutLaneLeft_active:
    score: 1000
    bonuscount: 3
  s_roOutLaneRight_active:
    score: 1000
    bonuscount: 3

  s_sTargetDropL_active:
    score: 10
    bonuscount: 1
  s_sTargetDropR_active:
    score: 10
    bonuscount: 1
  s_sTargetLowL_active:
    score: 10
    bonuscount: 1
  s_sTargetLowR_active:
    score: 10
    bonuscount: 1
  s_sTargetUpperL_active:
    score: 10
    bonuscount: 1
  s_sTargetUpperR_active:
    score: 10
    bonuscount: 1

  s_sTargetYellowL_active:
    score: 5000
    bonuscount: 3
  s_sTargetYellowR_active:
    score: 5000
    bonuscount: 3

  s_spinner_active:
    score: 100 * current_player.spinsLevel
    bounscount: 1

  s_ir_scoop_detect_active:
    score: 10000 * current_player.gravassistLevel
    bonuscount: 1

  shotLane0_shotProfileToplanes_unlit_hit:
    score: 100 * current_player.lanesLevel
    bonuscount: 1
  shotLane0_shotProfileToplanes_lit_hit:
    score: 100 * current_player.lanesLevel
    bonuscount: 3
  shotLane1_shotProfileToplanes_unlit_hit:
    score: 100 * current_player.lanesLevel
    bonuscount: 1
  shotLane1_shotProfileToplanes_lit_hit:
    score: 100 * current_player.lanesLevel
    bonuscount: 3
  shotLane2_shotProfileToplanes_unlit_hit:
    score: 100 * current_player.lanesLevel
    bonuscount: 1
  shotLane2_shotProfileToplanes_lit_hit:
    score: 100 * current_player.lanesLevel
    bonuscount: 3
  shotLane3_shotProfileToplanes_unlit_hit:
    score: 100 * current_player.lanesLevel
    bonuscount: 1
  shotLane3_shotProfileToplanes_lit_hit:
    score: 100 * current_player.lanesLevel
    bonuscount: 3
  shotLane4_shotProfileToplanes_unlit_hit:
    score: 100 * current_player.lanesLevel
    bonuscount: 1
  shotLane4_shotProfileToplanes_lit_hit:
    score: 100 * current_player.lanesLevel
    bonuscount: 3

  shotGroupToplanes_lit_complete:
    score: 1000  * current_player.lanesLevel
    bonustype1: 1
    bonuscount: 10
  drop_target_bank_leftfull_down:
    score: 1000
    bonustype2: 1
    bonuscount: 6
  drop_target_bank_rightfull_down:
    score: 1000
    bonustype3: 1
    bonuscount: 6
  gravityAssistBonus:
    score: 1000
    bonustype4: 1
    bonuscount: 10

  player_bonustype1{value==1}:
     bonus_multiplier:
        int: 1
     bonus_l2:
        int: 1
  player_bonustype1{value>1}:
     score:
        int: 5000
  player_bonustype2{value==1}:
     bonus_multiplier:
        int: 1
     bonus_l3:
        int: 1
  player_bonustype2{value>1}:
     score:
        int: 5000
  player_bonustype3{value==1}:
     bonus_multiplier:
        int: 1
     bonus_l4:
        int: 1
  player_bonustype3{value>1}:
     score:
        int: 5000
  player_bonustype4{value==1}:
     bonus_multiplier:
        int: 1
     bonus_l5:
        int: 1
  player_bonustype4{value>1}:
     score:
        int: 5000

  bonus_reset_achieved:
     bonustype4:
        int: 0
        action: set
     bonustype1:
        int: 0
        action: set
     bonustype2:
        int: 0
        action: set
     bonustype3:
        int: 0
        action: set

  shotGroupLeftTargets_lit_complete:
     score: 5000
     bonuscount: 3
  shotGroupRightTargets_lit_complete:
     score: 5000
     bonuscount: 3

  acheivement_story01_successful:
     status_untitled_mode_1: 1
  acheivement_story02_successful:
     status_untitled_mode_2: 1
  acheivement_story03_successful:
     status_untitled_mode_3: 1
  acheivement_story04_successful:
     status_untitled_mode_4: 1
  acheivement_story05_successful:
     status_untitled_mode_5: 1
  acheivement_story06_successful:
     status_untitled_mode_6: 1
  enableWizardMode:
     status_untitled_mode_7:
       int: 0
       action: set
