#config_version=5

accruals:
  bonusAllow:
    events:
      - shotGroupToplanes_lit_complete
      - drop_target_bank_leftfull_down
      - drop_target_bank_rightfull_down
      - gravityAssistBonus
    events_when_complete: bonus_reset_achieved
    reset_on_complete: true
    disable_on_complete: false
  enableWizard:
    events:
      - mode_story01_stopped
      - mode_story02_stopped
      - mode_story03_stopped
      - mode_story04_stopped
      - mode_story05_stopped
      - mode_story06_stopped
    events_when_complete: enableWizardMode

counters:
  spinPop:
    enable_events: mode_base_started
    count_events: s_spinner_active, s_jet_upper_left_active, s_jet_upper_right_active:, s_jet_lower_center_active
    starting_count: 50
    count_complete_value: 0
    direction: down
    events_when_complete: gravityAssistBonus
    reset_on_complete: true
    disable_on_complete: false
    multiple_hit_window: 10ms

variable_player:
  mode_base_started:
    pops:
       int: 0
       action: set
    drops:
       int: 0
       action: set
    spins:
       int: 0
       action: set
    bonustype1:
       int: 0
       action: set
    bonustype2:
       int: 0
       action: set
    bonustype3:
       int: 0
       action: set
    bonustype4:
       int: 0
       action: set
    bonuscount:
       int: 0
       action: set
    bonus_multiplier:
       int: 1
       action: set

  s_jet_upper_left_active:
    score: 1000
    pops: 1
  s_jet_upper_right_active:
    score: 1000
    pops: 1
  s_jet_lower_center_active:
    score: 1000
    pops: 1
  s_slingshot_left_active:
    score: 500
  s_slingshot_right_active:
    score: 500
  shotTargetL0_unlit_hit:
    score: 100
    drops: 1
  shotTargetL1_unlit_hit:
    score: 100
    drops: 1
  shotTargetL2_unlit_hit:
    score: 100
    drops: 1
  shotTargetL3_unlit_hit:
    score: 100
    drops: 1
  shotTargetL0_flashing_hit:
    score: 10000
    drops: 1
  shotTargetL1_flashing_hit:
    score: 10000
    drops: 1
  shotTargetL2_flashing_hit:
    score: 10000
    drops: 1
  shotTargetL3_flashing_hit:
    score: 10000
    drops: 1
  shotTargetL0_lit_hit:
    score: 400
    drops: 1
  shotTargetL1_lit_hit:
    score: 400
    drops: 1
  shotTargetL2_lit_hit:
    score: 400
    drops: 1
  shotTargetL3_lit_hit:
    score: 400
    drops: 1
  s_dTargetR0_active:
    score: 100
    drops: 1
  s_dTargetR1_active:
    score: 100
    drops: 1
  s_dTargetR2_active:
    score: 100
    drops: 1
  s_dTargetR3_active:
    score: 100
    drops: 1
  s_dTargetCL_active:
    score: 200
    drops: 1
  s_dTargetCR_active:
    score: 200
    drops: 1
  s_roInLaneLeft_active:
    score: 50
    bonuscount: 1
  s_roInLaneRight_active:
    score: 50
    bonuscount: 1
  s_roOutLaneLeft_active:
    score: 150
    bonuscount: 3
  s_roOutLaneRight_active:
    score: 150
    bonuscount: 3
  s_sTargetDropL_active:
    score: 1
    bonuscount: 1
  s_sTargetDropR_active:
    score: 1
    bonuscount: 1
  s_sTargetLowL_active:
    score: 1
    bonuscount: 1
  s_sTargetLowR_active:
    score: 1
    bonuscount: 1
  s_sTargetUpperL_active:
    score: 1
    bonuscount: 1
  s_sTargetUpperR_active:
    score: 1
    bonuscount: 1
  s_sTargetYellowL_active:
    score: 100
    bonuscount: 1
  s_sTargetYellowR_active:
    score: 100
    bonuscount: 1
  s_spinner_active:
    score: 100
    spins: 1
  s_ir_scoop_detect_active:
    score: 10000
    bonuscount: 1

  shotLane0_shotProfileToplanes_unlit_hit:
    score: 100
    bounscount: 1
  shotLane0_shotProfileToplanes_lit_hit:
    score: 100
    bounscount: 3
  shotLane1_shotProfileToplanes_unlit_hit:
    score: 100
    bounscount: 1
  shotLane1_shotProfileToplanes_lit_hit:
    score: 100
    bonuscount: 3
  shotLane2_shotProfileToplanes_unlit_hit:
    score: 100
    bonuscount: 1
  shotLane2_shotProfileToplanes_lit_hit:
    score: 100
    bonuscount: 3
  shotLane3_shotProfileToplanes_unlit_hit:
    score: 100
    bonuscount: 1
  shotLane3_shotProfileToplanes_lit_hit:
    score: 100
    bonuscount: 3
  shotLane4_shotProfileToplanes_unlit_hit:
    score: 100
    bonuscount: 1
  shotLane4_shotProfileToplanes_lit_hit:
    score: 100
    bonuscount: 3

  shotGroupToplanes_lit_complete:
    score: 1000
    bonustype1: 1
    bonuscount: 10
  drop_target_bank_leftfull_down:
    score: 1000
    bonustype2: 1
    bonuscount: 10
  drop_target_bank_rightfull_down:
    score: 1000
    bonustype3: 1
    bonuscount: 10
  gravityAssistBonus:
    score: 1000
    bonustype4: 1
    bonuscount: 10

  player_bonustype1{value==1}:
     bonus_multiplier:
        int: 1
  player_bonustype1{value>1}:
     score:
        int: 5000
     bonuscount:
        int: 10
  player_bonustype2{value==1}:
     bonus_multiplier:
        int: 1
  player_bonustype2{value>1}:
     score:
        int: 5000
     bonuscount:
        int: 10
  player_bonustype3{value==1}:
     bonus_multiplier:
        int: 1
  player_bonustype3{value>1}:
     score:
        int: 5000
     bonuscount:
        int: 10
  player_bonustype4{value==1}:
     bonus_multiplier:
        int: 1
  player_bonustype4{value>1}:
     score:
        int: 5000
     bonuscount:
        int: 10

  bonus_reset_achieved:
     bonustype4:
        int: 0
        action: set
     bonustype1:
        int: 0
        action: set
     bonustype2:
        int: 0
        action: set
     bonustype3:
        int: 0
        action: set

  shotGroupLeftTargets_lit_complete:
     score: 5000

  mode_story01_stopped:
     status_untitled_mode_1: 1
  mode_story02_stopped:
     status_untitled_mode_2: 1
  mode_story03_stopped:
     status_untitled_mode_3: 1
  mode_story04_stopped:
     status_untitled_mode_4: 1
  mode_story05_stopped:
     status_untitled_mode_5: 1
  mode_story06_stopped:
     status_untitled_mode_6: 1
  enableWizardMode:
     status_untitled_mode_7:
       int: 0
       action: set
