#config_version=5

widgets:
     badge01:
      - type: image
        image: badgeLocateTheCygnus
        anchor_x: center
        anchor_y: center
        x: 17%
        y: 94%
        z: 20
     badge02:
      - type: image
        image: badgeEscape
        anchor_x: center
        anchor_y: center
        x: 26%
        y: 94%
        z: 20
     badge03:
      - type: image
        image: badgeShooting
        anchor_x: center
        anchor_y: center
        x: 35%
        y: 94%
        z: 20
     badge04:
      - type: image
        image: badgeMeteor
        anchor_x: center
        anchor_y: center
        x: 44%
        y: 94%
        z: 20
     badge05:
      - type: image
        image: badgeCorridor
        anchor_x: center
        anchor_y: center
        x: 53%
        y: 94%
        z: 20
     badge06:
      - type: image
        image: badgeDavid
        anchor_x: center
        anchor_y: center
        x: 62%
        y: 94%
        z: 20
     badge07:
      - type: image
        image: badgeBeyond
        anchor_x: center
        anchor_y: center
        x: 71%
        y: 94%
        z: 20

     badge_dan:
      - type: image
        image: dan
        anchor_x: center
        anchor_y: center
        x: 17%
        y: 84%
        z: 20
     badge_charlie:
      - type: image
        image: charlie
        anchor_x: center
        anchor_y: center
        x: 25%
        y: 84%
        z: 20
     badge_harry:
      - type: image
        image: harry
        anchor_x: center
        anchor_y: center
        x: 33%
        y: 84%
        z: 20
     badge_kate:
      - type: image
        image: kate
        anchor_x: center
        anchor_y: center
        x: 41%
        y: 84%
        z: 20
     badge_alex:
      - type: image
        image: alex
        anchor_x: center
        anchor_y: center
        x: 49%
        y: 84%
        z: 20
     badge_hans:
      - type: image
        image: hanz
        anchor_x: center
        anchor_y: center
        x: 57%
        y: 84%
        z: 20
     badge_vincent:
      - type: image
        image: vincent
        anchor_x: center
        anchor_y: center
        x: 65%
        y: 84%
        z: 20
     badge_bob:
      - type: image
        image: bob
        anchor_x: center
        anchor_y: center
        x: 73%
        y: 84%
        z: 20

