#config_version=5

mode:
   start_events: selector_untitled_mode_7_selected
   stop_events: story_is_completed
   priority: 900

# All Story Modes --
#     Issue a scoop_eject after any introduction activities
# Modes that end with a Scoop Hit --
#     Issue a scoop eject after any outro-activities
# TEMP UNTIL REAL MODE PUT INTO PLACE

# Success/Failure
# By default, success = not losing ball, failure = losing ball
# If your mode has a different ruleset, change when the events
# story_is_completed_successful / acheivement_story##_successful
# story_is_completed_unsuccessful / acheivement_story##_unsuccessful
# are issued.

queue_relay_player:
  ball_ending:
    post: story_is_about_to_fail
    wait_for: story_outro_fail_complete

event_player:
   mode_story07_started:
     - story_is_about_to_begin
   story_intro_complete:
     - scoop_eject
     - story07_intro_complete
   in_mode_ball_save:
     - story_is_about_to_fail
   story_outro_complete:
     - story_is_completed_successful
     - acheivement_story07_successful
#    Only used when scoop hits end the mode
#    - scoop_eject
   story_outro_fail_complete:
     - story_is_completed_unsuccessful
     - acheivement_story07_unsuccessful
   story_is_completed_successful:
    - story_is_completed
   story_is_completed_unsuccessful:
    - story_is_completed
   player_wiz_feature_collects{value>=4}:
    - wiz_enable_discovery_collect
   shotScoopCollect_shotProfileScoopCollect_scoopActive_hit:
    - wizard_cashout
# Initial Discovery Bonus Events
   char_alex_is_complete:
    - discovery_char_bonus
   char_charlie_is_complete:
    - discovery_char_bonus
   char_dan_is_complete:
    - discovery_char_bonus
   char_kate_is_complete:
    - discovery_char_bonus
   char_harry_is_complete:
    - discovery_char_bonus
   char_hanz_is_complete:
    - discovery_char_bonus
   char_vincent_is_complete:
    - discovery_char_bonus
   char_bob_is_complete:
    - discovery_char_bonus

# Award Discovery Bonus, end the mode, reset things, eject the scoop
   story07_cashout_wiz_cashout_selected:
    - wizard_complete
# Reset shots, eject the scoop
   story07_cashout_wiz_cancel_selected:
    - wizard_continue
    - scoop_discovery_not_collected

# Trigger a reset event
   wizard_complete:
    - full_mode_and_char_reset
   story_is_about_to_fail:
    - full_mode_and_char_reset

#  Base intro / outro shows
show_player:
   story_is_about_to_begin:
      story_07_intro:
         events_when_completed: story_intro_complete
         loops: 0
   story_is_about_to_fail:
      story_07_fail_outro:
         events_when_completed: story_outro_fail_complete
         loops: 0
   story_is_about_to_end:
      story_07_outro:
         events_when_completed: story_outro_complete
         loops: 0
   shotScoopBeyond_shotProfileScoopBeyond_scoopInactive_hit:
      pinwheel:
        speed: 40
        loops: 1
        events_when_completed: scoop_eject
   wizard_complete:
      wizard_complete_show:
        events_when_completed: story_outro_complete
        loops: 0

shows:
   story_07_intro:
     - time: 0
       slides: story_07_intro_slide
       duration: 6
   story_07_fail_outro:
     - time: 0
       slides: story_07_outro_fail_slide
       duration: 3
   story_07_outro:
     - time: 0
       slides: story_07_outro_slide
       duration: 3
   discovery_collect_show:
     - time: 0
       slides: discovery_collect_slide
       duration: -1
   wizard_complete_show:
     - time: 0
       slides: discovery_collect_slide
       duration: 5

slides:
   story_07_intro_slide:
    widgets:
      - type: text
        text: In, Through, and Beyond!
        color: red
        font_size: 100
        font_name: ocr-a-tribute-bold
        anchor_x: center
        anchor_y: center
        y: 90%
      - type: text
        text: "Scenes"
        color: red
        font_size: 80
        font_name: ocr-a-tribute-bold
        anchor_x: center
        anchor_y: center
        y: 75%
        x: 16.5%
      - type: text
        text: "Bonus: (wizard_bonus_value)"
        color: red
        font_size: 80
        font_name: ocr-a-tribute-bold
        anchor_x: center
        anchor_y: center
        y: 60%
        x: 39%
      - type: image
        image: badgeLocateTheCygnusOff
        anchor_x: center
        anchor_y: center
        x: 36%
        y: 75%
        z: 10
      - type: image
        image: badgeEscapeOff
        anchor_x: center
        anchor_y: center
        x: 45%
        y: 75%
        z: 10
      - type: image
        image: badgeShootingOff
        anchor_x: center
        anchor_y: center
        x: 54%
        y: 75%
        z: 10
      - type: image
        image: badgeMeteorOff
        anchor_x: center
        anchor_y: center
        x: 63%
        y: 75%
        z: 10
      - type: image
        image: badgeCorridorOff
        anchor_x: center
        anchor_y: center
        x: 72%
        y: 75%
        z: 10
      - type: image
        image: badgeDavidOff
        anchor_x: center
        anchor_y: center
        x: 81%
        y: 75%
        z: 10
      - type: text
        text: "Crew:"
        color: red
        font_size: 80
        font_name: ocr-a-tribute-bold
        anchor_x: center
        anchor_y: center
        y: 45%
        x: 20.0%
      - type: image
        image: alexoff
        anchor_x: center
        anchor_y: center
        x: 36%
        y: 45%
        z: 10
        opacity: .5
      - type: image
        image: charlieoff
        anchor_x: center
        anchor_y: center
        x: 44%
        y: 45%
        z: 10
        opacity: .5
      - type: image
        image: danoff
        anchor_x: center
        anchor_y: center
        x: 52%
        y: 45%
        z: 10
        opacity: .5
      - type: image
        image: kateoff
        anchor_x: center
        anchor_y: center
        x: 60%
        y: 45%
        z: 10
        opacity: .5
      - type: image
        image: harryoff
        anchor_x: center
        anchor_y: center
        x: 68%
        y: 45%
        z: 10
        opacity: .5
      - type: image
        image: hanzoff
        anchor_x: center
        anchor_y: center
        x: 76%
        y: 45%
        z: 10
        opacity: .5
      - type: image
        image: vincentoff
        anchor_x: center
        anchor_y: center
        x: 84%
        y: 45%
        z: 10
        opacity: .7
      - type: image
        image: boboff
        anchor_x: center
        anchor_y: center
        x: 92%
        y: 45%
        z: 10
        opacity: .7
      - type: text
        text: "Discovery Value: (discovery_base_char_value)"
        color: red
        font_size: 80
        font_name: ocr-a-tribute-bold
        anchor_x: center
        anchor_y: center
        y: 30%
        x: 40%
      - type: text
        text: "Collect data from left drop bank, right drop bank, lanes, and pops/spinner"
        font_size: 32
        font_name: ocr-a-tribute-bold
        anchor_x: center
        anchor_y: center
        y: 21%
        x: 50%
      - type: text
        text: "Hit the scoop to collect discovery bonus or continue to build it"
        font_size: 32
        font_name: ocr-a-tribute-bold
        anchor_x: center
        anchor_y: center
        y: 16%
        x: 50%
   story_07_outro_fail_slide:
    widgets:
      - type: text
        text: NO BEYOND FOR YOU
        color: red
        font_size: 100
        font_name: ocr-a-tribute-bold
   story_07_outro_slide:
    widgets:
      - type: text
        text: "--- Beyond ---"
        color: red
        font_size: 100
        font_name: ocr-a-tribute-bold
   discovery_collect_slide:
    widgets:
      - type: text
        text: "--- Collect Discovery Bonus Placeholder ---"
        color: red
        font_size: 50
        font_name: ocr-a-tribute-bold


# The below is mode specific data



variable_player:
  story_is_about_to_begin:
    wizard_bonus_value:
       action: set
       int: 0
    discovery_bonus_value:
       action: set
       int: 0
    discovery_base_char_value:
       action: set
       int: 2000000
    modestat_7_base_scoring:
       action: set
       int: 0
    modestat_7_scoring:
       action: set
       int: 0
  discovery_char_bonus:
    discovery_base_char_value:
       action: set
       int: current_player.discovery_base_char_value * 2
  wizard_bonus_increment:
    wizard_bonus_value:
       action: add
       int: 1500000
  wizard_bonus_multiply:
    wizard_bonus_value:
       action: set
       int: current_player.wizard_bonus_value * 2
  slide_story_07_intro_slide_removed:
    score:
       action: add
       int: current_player.wizard_bonus_value
  wizard_complete:
    score:
       action: add
       int: current_player.discovery_base_char_value * current_player.temp_playfield_x * current_player.perm_playfield_x
    modestat_7_scoring:
       action: add
       int: current_player.discovery_base_char_value * current_player.temp_playfield_x * current_player.perm_playfield_x
    modestat_7_base_scoring:
       action: add
       int: current_player.discovery_base_char_value
  mode_story07_started:
    wiz_feature_collects:
       action: set
       int: 0
    wiz_lane_collect:
       action: set
       int: 0
    wiz_left_collect:
       action: set
       int: 0
    wiz_right_collect:
       action: set
       int: 0
    wiz_ps_collect:
       action: set
       int: 0
  wizard_continue:
    wiz_feature_collects:
       action: set
       int: 0
    wiz_lane_collect:
       action: set
       int: 0
    wiz_left_collect:
       action: set
       int: 0
    wiz_right_collect:
       action: set
       int: 0
    wiz_ps_collect:
       action: set
       int: 0
  wiz_lanes_hit{current_player.wiz_lane_collect==0}:
    wiz_lane_collect:
       action: set
       int: 1
    wiz_feature_collects:
       action: add
       int: 1
    discovery_base_char_value:
       action: set
       int: current_player.discovery_base_char_value * 1.25
  wiz_left_bank_hit{current_player.wiz_left_collect==0}:
    wiz_left_collect:
       action: set
       int: 1
    wiz_feature_collects:
       action: add
       int: 1
    discovery_base_char_value:
       action: set
       int: current_player.discovery_base_char_value * 1.25
  wiz_right_bank_hit{current_player.wiz_right_collect==0}:
    wiz_right_collect:
       action: set
       int: 1
    wiz_feature_collects:
       action: add
       int: 1
    discovery_base_char_value:
       action: set
       int: current_player.discovery_base_char_value * 1.25
  wiz_pop_spin_hit{current_player.wiz_ps_collect==0}:
    wiz_ps_collect:
       action: set
       int: 1
    wiz_feature_collects:
       action: add
       int: 1
    discovery_base_char_value:
       action: set
       int: current_player.discovery_base_char_value * 1.25

shots:
   wiz_lane_0:
     switch: s_lane0
     advance_events: wiz_lanes_hit
     profile: wiz_lane_profile
   wiz_lane_1:
     switch: s_lane1
     advance_events: wiz_lanes_hit
     profile: wiz_lane_profile
   wiz_lane_2:
     switch: s_lane2
     advance_events: wiz_lanes_hit
     profile: wiz_lane_profile
   wiz_lane_3:
     switch: s_lane3
     advance_events: wiz_lanes_hit
     profile: wiz_lane_profile
   wiz_lane_4:
     switch: s_lane4
     advance_events: wiz_lanes_hit
     profile: wiz_lane_profile
   wiz_left_0:
     switch: s_dTargetL0
     advance_events: wiz_left_bank_hit
     profile: wiz_lb_profile
   wiz_left_1:
     switch: s_dTargetL1
     advance_events: wiz_left_bank_hit
     profile: wiz_lb_profile
   wiz_left_2:
     switch: s_dTargetL2
     advance_events: wiz_left_bank_hit
     profile: wiz_lb_profile
   wiz_left_3:
     switch: s_dTargetL3
     advance_events: wiz_left_bank_hit
     profile: wiz_lb_profile
   wiz_right_0:
     switch: s_dTargetR0
     advance_events: wiz_right_bank_hit
     profile: wiz_rb_profile
   wiz_right_1:
     switch: s_dTargetR1
     advance_events: wiz_right_bank_hit
     profile: wiz_rb_profile
   wiz_right_2:
     switch: s_dTargetR2
     advance_events: wiz_right_bank_hit
     profile: wiz_rb_profile
   wiz_right_3:
     switch: s_dTargetR3
     advance_events: wiz_right_bank_hit
     profile: wiz_rb_profile
   wiz_pop_bot:
     switch: s_jet_lower_center
     advance_events: wiz_pop_spin_hit
     profile: wiz_ps_profile
   wiz_pop_left:
     switch: s_jet_upper_left
     advance_events: wiz_pop_spin_hit
     profile: wiz_ps_profile
   wiz_pop_right:
     switch: s_jet_upper_right
     advance_events: wiz_pop_spin_hit
     profile: wiz_ps_profile
   wiz_spin:
     switch: s_spinner
     advance_events: wiz_pop_spin_hit
     profile: wiz_ps_profile
   shotScoopCollect:
     switch: s_ir_scoop_detect
     reset_events: story_intro_complete, scoop_discovery_not_collected
     advance_events: wiz_enable_discovery_collect
     show_tokens:
       light: l_scoop
     profile: shotProfileScoopCollect

shot_profiles:
   wiz_lb_profile:
      states:
        - name: waiting
          show: wiz_lb_waiting
        - name: collected
          show: wiz_lb_collected
   wiz_rb_profile:
      states:
        - name: waiting
          show: wiz_rb_waiting
        - name: collected
          show: wiz_rb_collected
   wiz_lane_profile:
      states:
        - name: waiting
          show: wiz_lane_waiting
        - name: collected
          show: wiz_lane_collected
   wiz_ps_profile:
      states:
        - name: waiting
          show: wiz_ps_waiting
        - name: collected
          show: wiz_ps_collected
   shotProfileScoopCollect:
      show_when_disabled: true
      advance_on_hit: false
      block: true
      states:
        - name: scoopInactive
          show: off
        - name: scoopActive
          show: scoopReadyShow

shot_groups:
   wiz_left_bank:
      shots: wiz_left_0, wiz_left_1, wiz_left_2, wiz_left_3
      reset_events: scoop_discovery_not_collected
   wiz_right_bank:
      shots: wiz_right_0, wiz_right_1, wiz_right_2, wiz_right_3
      reset_events: scoop_discovery_not_collected
   wiz_lanes:
      shots: wiz_lane_0, wiz_lane_1, wiz_lane_2, wiz_lane_3, wiz_lane_4
      reset_events: scoop_discovery_not_collected
   wiz_pop_spin:
      shots: wiz_pop_bot, wiz_pop_left, wiz_pop_right, wiz_spin
      reset_events: scoop_discovery_not_collected

#timers:

widget_player:
   mode_story07_started:
      yt_remain_widget_07:
         slide: scoring_slide
   story07_ended:
      yt_remain_widget_07:
         action: remove
   status_untitled_mode_1_completed:
      ach_01_on:
         slide: story_07_intro_slide
   status_untitled_mode_2_completed:
      ach_02_on:
         slide: story_07_intro_slide
   status_untitled_mode_3_completed:
      ach_03_on:
         slide: story_07_intro_slide
   status_untitled_mode_4_completed:
      ach_04_on:
         slide: story_07_intro_slide
   status_untitled_mode_5_completed:
      ach_05_on:
         slide: story_07_intro_slide
   status_untitled_mode_6_completed:
      ach_06_on:
         slide: story_07_intro_slide
   char_alex_is_complete:
      alex_on:
         slide: story_07_intro_slide
   char_bob_is_complete:
      bob_on:
         slide: story_07_intro_slide
   char_charlie_is_complete:
      charlie_on:
         slide: story_07_intro_slide
   char_dan_is_complete:
      dan_on:
         slide: story_07_intro_slide
   char_hanz_is_complete:
      hanz_on:
         slide: story_07_intro_slide
   char_harry_is_complete:
      harry_on:
         slide: story_07_intro_slide
   char_kate_is_complete:
      kate_on:
         slide: story_07_intro_slide
   char_vincent_is_complete:
      vincent_on:
         slide: story_07_intro_slide

sound_player:
    status_untitled_mode_1_completed: bass_hit
    status_untitled_mode_2_completed: bass_hit
    status_untitled_mode_3_completed: bass_hit
    status_untitled_mode_4_completed: bass_hit
    status_untitled_mode_5_completed: bass_hit
    status_untitled_mode_6_completed: bass_hit
    status_untitled_mode_7_completed: bass_hit
    char_alex_is_complete: bass_hit
    char_bob_is_complete: bass_hit
    char_charlie_is_complete: bass_hit
    char_dan_is_complete: bass_hit
    char_hanz_is_complete: bass_hit
    char_harry_is_complete: bass_hit
    char_kate_is_complete: bass_hit
    char_vincent_is_complete: bass_hit

widgets:
   yt_remain_widget_07:
     - type: text
       text: "spinner then lanes ya dolt"
       y: 80%
   ach_01_on:
     - type: image
       image: badgeLocateTheCygnus
       anchor_x: center
       anchor_y: center
       x: 36%
       y: 75%
       z: 11
   ach_02_on:
     - type: image
       image: badgeEscape
       anchor_x: center
       anchor_y: center
       x: 45%
       y: 75%
       z: 11
   ach_03_on:
     - type: image
       image: badgeShooting
       anchor_x: center
       anchor_y: center
       x: 54%
       y: 75%
       z: 11
   ach_04_on:
     - type: image
       image: badgeMeteor
       anchor_x: center
       anchor_y: center
       x: 63%
       y: 75%
       z: 11
   ach_05_on:
     - type: image
       image: badgeCorridor
       anchor_x: center
       anchor_y: center
       x: 72%
       y: 75%
       z: 11
   ach_06_on:
     - type: image
       image: badgeDavid
       anchor_x: center
       anchor_y: center
       x: 81%
       y: 75%
       z: 11
   alex_on:
      - type: image
        image: alex
        anchor_x: center
        anchor_y: center
        x: 36%
        y: 45%
        z: 11
   charlie_on:
      - type: image
        image: charlie
        anchor_x: center
        anchor_y: center
        x: 44%
        y: 45%
        z: 11
   dan_on:
      - type: image
        image: dan
        anchor_x: center
        anchor_y: center
        x: 52%
        y: 45%
        z: 11
   kate_on:
      - type: image
        image: kate
        anchor_x: center
        anchor_y: center
        x: 60%
        y: 45%
        z: 11
   harry_on:
      - type: image
        image: harry
        anchor_x: center
        anchor_y: center
        x: 68%
        y: 45%
        z: 11
   hanz_on:
      - type: image
        image: hanz
        anchor_x: center
        anchor_y: center
        x: 76%
        y: 45%
        z: 11
   vincent_on:
      - type: image
        image: vincent
        anchor_x: center
        anchor_y: center
        x: 84%
        y: 45%
        z: 11
   bob_on:
      - type: image
        image: bob
        anchor_x: center
        anchor_y: center
        x: 92%
        y: 45%
        z: 11



