#config_version=5

config:
   - ballsave.yaml

mode:
   start_events: selector_untitled_mode_7_selected
   stop_events: story_is_completed
   priority: 900

# All Story Modes --
#     Issue a scoop_eject after any introduction activities
# Modes that end with a Scoop Hit --
#     Issue a scoop eject after any outro-activities
# TEMP UNTIL REAL MODE PUT INTO PLACE

# Success/Failure
# By default, success = not losing ball, failure = losing ball
# If your mode has a different ruleset, change when the events
# story_is_completed_successful / acheivement_story##_successful
# story_is_completed_unsuccessful / acheivement_story##_unsuccessful
# are issued.

queue_relay_player:
  ball_ending:
    post: story_is_about_to_fail
    wait_for: story_outro_fail_complete

event_player:
   mode_story07_started:
     - story_is_about_to_begin
   story_intro_complete:
     - scoop_eject
   in_mode_ball_save:
     - story_is_about_to_fail
   shotScoopBeyond_shotProfileScoopBeyond_scoopActive_hit:
     - story_is_about_to_end
   story_outro_complete:
     - story_is_completed_successful
     - acheivement_story07_successful
#    Only used when scoop hits end the mode
#    - scoop_eject
   story_outro_fail_complete:
     - story_is_completed_unsuccessful
     - acheivement_story07_unsuccessful
   story_is_completed_successful:
    - story_is_completed
   story_is_completed_unsuccessful:
    - story_is_completed
# Mode Specific Event Player Stuff
   s_spinner_active:
       - enable_lane_shot
   timer_traj_timer_complete:
       - traj_time_out
   lanetraj0_available_hit:
       - traj_set
   lanetraj1_available_hit:
       - traj_set
   lanetraj2_available_hit:
       - traj_set
   lanetraj3_available_hit:
       - traj_set
   lanetraj4_available_hit:
       - traj_set

#  Base intro / outro shows
show_player:
   story_is_about_to_begin:
      story_07_intro:
         events_when_completed: story_intro_complete
         loops: 0
   story_is_about_to_fail:
      story_07_fail_outro:
         events_when_completed: story_outro_fail_complete
         loops: 0
   story_is_about_to_end:
      story_07_outro:
         events_when_completed: story_outro_complete
         loops: 0
   enable_lane_shot_1:
      lane1shot:
        priority: 950
        loops: -1
   enable_lane_shot_2:
      lane2shot:
        priority: 950
        loops: -1
   enable_lane_shot_3:
      lane3shot:
        priority: 950
        loops: -1
   enable_lane_shot_4:
      lane4shot:
        priority: 950
        loops: -1
   enable_lane_shot_5:
      lane5shot:
        priority: 950
        loops: -1
   traj_time_out:
      lane1shot:
         action: stop
      lane2shot:
         action: stop
      lane3shot:
         action: stop
      lane4shot:
         action: stop
      lane5shot:
         action: stop
   traj_set:
      lane1shot:
         action: stop
      lane2shot:
         action: stop
      lane3shot:
         action: stop
      lane4shot:
         action: stop
      lane5shot:
         action: stop
   shotScoopBeyond_shotProfileScoopBeyond_scoopInactive_hit:
      pinwheel:
        speed: 40
        loops: 1
        events_when_completed: scoop_eject

shows:
   story_07_intro:
     - time: 0
       slides: story_07_intro_slide
       duration: 3
   story_07_fail_outro:
     - time: 0
       slides: story_07_outro_fail_slide
       duration: 3
   story_07_outro:
     - time: 0
       slides: story_07_outro_slide
       duration: 3

slides:
   story_07_intro_slide:
    widgets:
      - type: text
        text: In, Through, and Beyond!
        color: red
        font_size: 100
        font_name: ocr-a-tribute-bold
   story_07_outro_fail_slide:
    widgets:
      - type: text
        text: NO BEYOND FOR YOU
        color: red
        font_size: 100
        font_name: ocr-a-tribute-bold
   story_07_outro_slide:
    widgets:
      - type: text
        text: "--- Beyond ---"
        color: red
        font_size: 100
        font_name: ocr-a-tribute-bold

# The below is mode specific data

random_event_player:
  enable_lane_shot:
    - enable_lane_shot_1
    - enable_lane_shot_2
    - enable_lane_shot_3
    - enable_lane_shot_4
    - enable_lane_shot_5
  time_traj_timer_complete:
    - traj_time_out

variable_player:
  traj_set:
    score: 100000
  scoop_out_success:
    score: 500000

shots:
   laneTraj0:
     switch: s_lane0
     profile: traj_lanes
     advance_events: enable_lane_shot_1
     reset_events: traj_time_out, traj_set
   laneTraj1:
     switch: s_lane1
     profile: traj_lanes
     advance_events: enable_lane_shot_2
     reset_events: traj_time_out, traj_set
   laneTraj2:
     switch: s_lane2
     profile: traj_lanes
     advance_events: enable_lane_shot_3
     reset_events: traj_time_out, traj_set
   laneTraj3:
     switch: s_lane3
     profile: traj_lanes
     advance_events: enable_lane_shot_4
     reset_events: traj_time_out, traj_set
   laneTraj4:
     switch: s_lane4
     profile: traj_lanes
     advance_events: enable_lane_shot_5
     reset_events: traj_time_out, traj_set
   shotScoopBeyond:
     switch: s_ir_scoop_detect
     advance_events: enable_scoop_loop, timer_scoop_off_timer_complete
     reset_events: timer_scoop_timer_complete
     show_tokens:
       light: l_scoop
     profile: shotProfileScoopBeyond

shot_profiles:
   traj_lanes:
     block: true
     advance_on_hit: false
     states:
       - name: off
       - name: available
   shotProfileScoopBeyond:
     show_when_disabled: true
     advance_on_hit: false
     block: true
     states:
       - name: scoopInactive
         show: off
       - name: scoopActive
         show: popgreen

#variable_player:
#   mode_story07_started:
#     temp_ythurryup_value:
#       action: set
#       int: 100000
#   timer_yttimer07_tick:
#     temp_ythurryup_value: -300
#   s_sTargetYellowL_active:
#     score: current_player.temp_ythurryup_value|block
#   s_sTargetYellowR_active:
#     score: current_player.temp_ythurryup_value|block

timers:
   traj_timer:
     start_value: 5
     end_value: 0
     tick_interval: 1s
     direction: down
     start_running: no
     control_events:
       - event: enable_lane_shot
         action: restart
   scoop_timer:
     start_value: 10
     end_value: 0
     tick_interval: 1s
     direction: down
     start_running: no
     control_events:
       - event: enable_scoop_loop
         action: restart
       - event: timer_scoop_off_timer_complete
         action: restart
   scoop_off_timer:
     start_value: 10
     end_value: 0
     tick_interval: 1s
     direction: down
     start_running: no
     control_events:
       - event: timer_scoop_timer_complete
         action: restart


widget_player:
   mode_story07_started:
      yt_remain_widget_07:
         slide: scoring_slide
   story07_ended:
      yt_remain_widget_07:
         action: remove

widgets:
   yt_remain_widget_07:
     - type: text
       text: "spinner then lanes ya dolt"
       y: 80%

# Mode 7 States
state_machines:
  beyond:
     states:
       start:
         label: mode_entry
         events_when_started: debug_beyond_start
       traj01:
         label: Set Trajectory 1
         events_when_started: debug_beyond_traj01
       traj01hit:
         label: Trajectory 1 Set
         events_when_started: debug_beyond_traj01hit
       traj02:
         label: Set Trajectory 2
         events_when_started: debug_beyond_traj02
       traj02hit:
         label: Trajectory 2 Set
         events_when_started: debug_beyond_traj02hit
       traj03:
         label: Set Trajectory 3
         events_when_started: debug_beyond_traj03
       scoopOpen:
         label: Scoop Open
         events_when_started: enable_scoop_loop, debug_beyond_scoop_open
       scoopClosed:
         label: Scoop Closed
         events_when_started: debug_beyond_scoop_closed
       completion:
         label: completion
         events_when_started: debug_beyond_completion
     transitions:
       - source: start
         target: traj01
         events: enable_lane_shot
       - source: traj01hit
         target: traj02
         events: enable_lane_shot
       - source: traj02hit
         target: traj03
         events: enable_lane_shot
       - source: traj01
         target: start
         events: traj_time_out
       - source: traj02
         target: traj01hit
         events: traj_time_out
       - source: traj03
         target: traj02hit
         events: traj_time_out
       - source: traj01
         target: traj01hit
         events: traj_set
       - source: traj02
         target: traj02hit
         events: traj_set
       - source: traj03
         target: scoopOpen
         events: traj_set
       - source: scoopOpen
         target: scoopClosed
         events: scoop_timeout
       - source: scoopClosed
         target: scoopOpen
         events: scoop_timer_reset
       - source: scoopOpen
         target: completion
         events: scoop_out_success

