#config_version=5

mode_settings:
  keep_multiplier: True
  display_delay_ms: 2500ms
  hurry_up_delay_ms: 1000ms
  bonus_entries:
      - event: bonus_product
        score: (current_player.pds) * (current_player.bonuscount)
        skip_if_zero: false
slide_player:
  bonus_start: slide_6
slides:
  slide_6:
  - type: image
    image: tbh-slide-template
    z: 10
  - type: text
    text: END OF BALL BONUS
    style:
       - eob_bonus_title

event_player:
  bonus_product:
    - do_my_nothing_event
  bonus_start:
    - bonus_slide_is_displayed
  flipper_cancel:
    - bonus_countdown_speed_up

#sound_player:
#  bonus_countdown_decrement_audio: bass_hit

widget_player:
  bonus_product:
    bonus_pops:
       action: add
       slide: slide_6
    bonus_count:
       action: add
       slide: slide_6
  bonus_subtotal_display:
    bonus_sub:
       action: add
       slide: slide_6
  bonus_multiplier:
    bonus_multi:
       action: add
       slide: slide_6
  bonus_total:
    bonus_final:
       action: add
       slide: slide_6

widgets:
  bonus_title:
  - type: text
    text: END OF BALL BONUS
    style:
       - eob_bonus_title
  bonus_pops:
  - type: text
    text: 'Bonus Value:'
    style:
       - eob_bonus_text_title
       - eob_bonus_line_1
  - type: text
    text: '(pds)'
    style:
       - eob_bonus_values
       - eob_bonus_line_1
  - type: text
    text: '888888888888'
    style:
       - eob_bonus_value_background
       - eob_bonus_line_1
  - type: text
    text: '   ,   ,   ,   '
    style:
       - eob_bonus_value_background
       - eob_bonus_line_1
  bonus_count:
  - type: text
    text: 'Bonus Count:'
    style:
       - eob_bonus_text_title
       - eob_bonus_line_2
  - type: text
    text: '(bonuscountdisplay)'
    style:
       - eob_bonus_values
       - eob_bonus_line_2
  - type: text
    text: '888888888888'
    style:
       - eob_bonus_value_background
       - eob_bonus_line_2
  - type: text
    text: '   ,   ,   ,   '
    style:
       - eob_bonus_value_background
       - eob_bonus_line_2
  bonus_sub:
  - type: text
    text: 'SUBTOTAL:'
    style:
       - eob_bonus_text_title
       - eob_bonus_line_3
  - type: text
    text: '(score)'
    style:
       - eob_bonus_values
       - eob_bonus_line_3
  - type: text
    text: '888888888888'
    style:
       - eob_bonus_value_background
       - eob_bonus_line_3
  - type: text
    text: '   ,   ,   ,   '
    style:
       - eob_bonus_value_background
       - eob_bonus_line_3
  bonus_multi:
  - type: text
    text: 'MULTIPLIER'
    style:
       - eob_bonus_text_title
       - eob_bonus_line_4
  - type: text
    text: '(bonus_multiplier)'
    style:
       - eob_bonus_values
       - eob_bonus_line_4
  - type: text
    text: '888888888888'
    style:
       - eob_bonus_value_background
       - eob_bonus_line_4
  - type: text
    text: '   ,   ,   ,   '
    style:
       - eob_bonus_value_background
       - eob_bonus_line_4
  bonus_final:
  - type: text
    text: 'TOTAL BONUS'
    style:
       - eob_bonus_text_title
       - eob_bonus_line_5
  - type: text
    text: '(score)'
    style:
       - eob_bonus_values
       - eob_bonus_line_5
  - type: text
    text: '888888888888'
    style:
       - eob_bonus_value_background
       - eob_bonus_line_5
  - type: text
    text: '   ,   ,   ,   '
    style:
       - eob_bonus_value_background
       - eob_bonus_line_5
