#config_version=5

mode_settings:
  keep_multiplier: True
  display_delay_ms: 2000ms
  hurry_up_delay_ms: 0
  bonus_entries:
      - event: bonus_product
        score: (current_player.pds) * (current_player.bonuscount)
        skip_if_zero: false
slide_player:
  bonus_start: slide_6
slides:
  slide_6:
  - type: text
    text: END OF BALL BONUS
    y: 85%
    font_size: 100

event_player:
  bonus_product:
    - do_my_nothing_event
  bonus_start:
    - bonus_slide_is_displayed

widget_player:
  bonus_product:
    bonus_pops:
       action: add
       slide: slide_6
    bonus_drops:
       action: add
       slide: slide_6
    bonus_count:
       action: add
       slide: slide_6
  bonus_subtotal_display:
    bonus_sub:
       action: add
       slide: slide_6
  bonus_multiplier:
    bonus_multi:
       action: add
       slide: slide_6
  bonus_total:
    bonus_final:
       action: add
       slide: slide_6

widgets:
  bonus_title:
  - type: text
    text: END OF BALL BONUS
    y: 85%
    font_size: 100
  bonus_pops:
  - type: text
    text: 'Bonus Value: (pds) '
    font_size: 40
    y: 70%
  bonus_drops:
  - type: text
    text: ' X '
    font_size: 40
    y: 60%
  bonus_count:
  - type: text
    text: 'Bonus Count: (bonuscountdisplay)  ='
    font_size: 40
    y: 50%
  bonus_sub:
  - type: text
    text: 'SUBTOTAL: (score)'
    number_grouping: true
    font_size: 40
    y: 40%
  bonus_multi:
  - type: text
    text: (bonus_multiplier)X
    font_size: 70
    y: 25%
  bonus_final:
  - type: text
    text: 'TOTAL BONUS: (score)'
    number_grouping: true
    font_size: 70
    y: 10%