#config_version=5

config:
   - story02-scoring.yaml
#   - ballsave.yaml

#TODO Character collect -- could be completion, or reaching stabilization

mode:
   start_events: selector_untitled_mode_2_selected
   stop_events: story_is_completed
   priority: 900

# All Story Modes --
#     Issue a scoop_eject after any introduction activities
# Modes that end with a Scoop Hit --
#     Issue a scoop eject after any outro-activities

# Success/Failure
# By default, success = not losing ball, failure = losing ball
# If your mode has a different ruleset, change when the events
# story_is_completed_successful / acheivement_story##_successful
# story_is_completed_unsuccessful / acheivement_story##_unsuccessful
# are issued.

queue_relay_player:
  ball_ending:
    post: story_is_about_to_fail
    wait_for: story_outro_fail_complete

event_player:
   mode_story02_started:
     - story_is_about_to_begin
   in_mode_ball_save:
     - story_is_about_to_fail
   story_intro_complete:
     - scoop_eject
#   shotScoopEscape_shotProfileScoopEscape_inactive_hit:
#     - scoop_eject
   shotScoopEscape_shotProfileScoopEscape_scoopActive_hit:
     - story_is_about_to_end
   story_outro_complete:
     - scoop_eject
     - story_is_completed_successful
     - acheivement_story02_successful
   story_outro_complete{current_player.escape_lane_count==3}:
     - random_character_collect|3100ms
   story_outro_fail_complete:
     - story_is_completed_unsuccessful
     - acheivement_story02_unsuccessful
   story_is_completed_successful:
    - story_is_completed
   story_is_completed_unsuccessful:
    - story_is_completed
   s_spinner_active{current_player.escape_scoop_enabled==0 and current_player.lane_spin_count<5}:
    - enable_lane_shot
   timer_traj_timer_complete:
    - traj_time_out
   lanetraj0_available_hit:
    - traj_set
   lanetraj1_available_hit:
    - traj_set
   lanetraj2_available_hit:
    - traj_set
   lanetraj3_available_hit:
    - traj_set
   lanetraj4_available_hit:
    - traj_set
   lanetraj0_off_hit:
    - traj_time_out
   lanetraj1_off_hit:
    - traj_time_out
   lanetraj2_off_hit:
    - traj_time_out
   lanetraj3_off_hit:
    - traj_time_out
   lanetraj4_off_hit:
    - traj_time_out
   enable_scoop_loop:
    - status_escape
   timer_scoop_timer_complete:
    - scoop_off


random_event_player:
  enable_lane_shot:
    - enable_lane_shot_1
    - enable_lane_shot_2
    - enable_lane_shot_3
    - enable_lane_shot_4
    - enable_lane_shot_5
  time_traj_timer_complete:
    - traj_time_out

#  Base intro / outro shows
show_player:
   story_is_about_to_begin:
      story_02_intro:
         events_when_completed: story_intro_complete
         loops: 0
   story_is_about_to_fail:
      story_02_fail_outro:
         events_when_completed: story_outro_fail_complete
         loops: 0
   story_is_about_to_end:
      story_02_outro:
         events_when_completed: story_outro_complete
         loops: 0
   shotScoopEscape_shotProfileScoopEscape_inactive_hit:
      pinwheel:
        speed: 40
        loops: 1
        events_when_completed: scoop_eject
   player_shot_lanetraj0{value==1}:
      lane1shot:
        priority: 950
        loops: -1
      lane2shot:
        action: stop
      lane3shot:
        action: stop
      lane4shot:
        action: stop
      lane5shot:
        action: stop
   player_shot_lanetraj1{value==1}:
      lane2shot:
        priority: 950
        loops: -1
      lane1shot:
        action: stop
      lane3shot:
        action: stop
      lane4shot:
        action: stop
      lane5shot:
        action: stop
   player_shot_lanetraj2{value==1}:
      lane3shot:
        priority: 950
        loops: -1
      lane1shot:
        action: stop
      lane2shot:
        action: stop
      lane4shot:
        action: stop
      lane5shot:
        action: stop
   player_shot_lanetraj3{value==1}:
      lane4shot:
        priority: 950
        loops: -1
      lane1shot:
        action: stop
      lane2shot:
        action: stop
      lane3shot:
        action: stop
      lane5shot:
        action: stop
   player_shot_lanetraj4{value==1}:
      lane5shot:
        priority: 950
        loops: -1
      lane1shot:
        action: stop
      lane2shot:
        action: stop
      lane3shot:
        action: stop
      lane4shot:
        action: stop
   traj_time_out:
      lane1shot:
         action: stop
      lane2shot:
         action: stop
      lane3shot:
         action: stop
      lane4shot:
         action: stop
      lane5shot:
         action: stop
   traj_set:
      lane1shot:
         action: stop
      lane2shot:
         action: stop
      lane3shot:
         action: stop
      lane4shot:
         action: stop
      lane5shot:
         action: stop
#variable_player:
#  traj_set:
#    score: 100000
#  scoop_out_success:
#    score: 500000

shows:
   story_02_intro:
     - time: 0
       slides: story_02_intro_slide
       duration: 3
   story_02_fail_outro:
     - time: 0
       slides: story_02_outro_fail_slide
       duration: 3
   story_02_outro:
     - time: 0
       slides: story_02_outro_slide
       duration: 3

slides:
   story_02_intro_slide:
    widgets:
      - type: text
        text: Escape The Black Hole
        color: red
        font_size: 100
        font_name: ocr-a-tribute-bold
      - type: text
        text: Hit the Spinner
        y: 40%
        color: red
        font_size: 50
      - type: text
        text: Then hit the lit lane (3x)
        y: 30%
        color: red
        font_size: 50
      - type: text
        text: Then ESCAPE the black hole out the scoop!
        y: 20%
        color: red
        font_size: 50
   story_02_outro_fail_slide:
    widgets:
      - type: text
        text: YOU FAILED TO ESCAPE THE BLACK HOLE
        color: red
        font_size: 60
        font_name: ocr-a-tribute-bold
      - type: text
        text: You are *NOT* super duper neat
        y: 40%
        color: red
        font_size: 50
   story_02_outro_slide:
    widgets:
      - type: text
        text: YOU HAVE ESCAPED THE BLACK HOLE
        color: red
        font_size: 80
        font_name: ocr-a-tribute-bold
      - type: text
        text: You are super duper neat
        y: 40%
        color: red
        font_size: 50

# The below is mode specific data

timers:
   traj_timer:
     start_value: 5
     end_value: 0
     tick_interval: 1s
     direction: down
     start_running: no
     control_events:
       - event: enable_lane_shot
         action: restart
       - event: traj_time_out
         action: stop
   scoop_timer:
     start_value: 15
     end_value: 0
     tick_interval: 1s
     direction: down
     start_running: no
     control_events:
       - event: enable_scoop_loop
         action: restart

widget_player:
   status_escape:
      yt_escape_widget_02:
         slide: scoring_slide
   scoop_off:
      yt_escape_widget_02:
         action: remove
   story02_ended:
      yt_engine_widget_02:
         action: remove

shots:
   lanetraj0:
     switch: s_lane0
     profile: traj_lanes
     advance_events: enable_lane_shot_1
     reset_events: traj_time_out, traj_set, enable_lane_shot_2, enable_lane_shot_3, enable_lane_shot_4, enable_lane_shot_5, lanetraj1_traj_lanes_off_hit, lanetraj2_traj_lanes_off_hit, lanetraj3_traj_lanes_off_hit, lanetraj4_traj_lanes_off_hit
   lanetraj1:
     switch: s_lane1
     profile: traj_lanes
     advance_events: enable_lane_shot_2
     reset_events: traj_time_out, traj_set, enable_lane_shot_1, enable_lane_shot_3, enable_lane_shot_4, enable_lane_shot_5, lanetraj0_traj_lanes_off_hit, lanetraj2_traj_lanes_off_hit, lanetraj3_traj_lanes_off_hit, lanetraj4_traj_lanes_off_hit
   lanetraj2:
     switch: s_lane2
     profile: traj_lanes
     advance_events: enable_lane_shot_3
     reset_events: traj_time_out, traj_set, enable_lane_shot_1, enable_lane_shot_2, enable_lane_shot_4, enable_lane_shot_5, lanetraj0_traj_lanes_off_hit, lanetraj1_traj_lanes_off_hit, lanetraj3_traj_lanes_off_hit, lanetraj4_traj_lanes_off_hit
   lanetraj3:
     switch: s_lane3
     profile: traj_lanes
     advance_events: enable_lane_shot_4
     reset_events: traj_time_out, traj_set, enable_lane_shot_1, enable_lane_shot_2, enable_lane_shot_3, enable_lane_shot_5, lanetraj0_traj_lanes_off_hit, lanetraj1_traj_lanes_off_hit, lanetraj2_traj_lanes_off_hit, lanetraj4_traj_lanes_off_hit
   lanetraj4:
     switch: s_lane4
     profile: traj_lanes
     advance_events: enable_lane_shot_5
     reset_events: traj_time_out, traj_set, enable_lane_shot_1, enable_lane_shot_2, enable_lane_shot_3, enable_lane_shot_4, lanetraj0_traj_lanes_off_hit, lanetraj1_traj_lanes_off_hit, lanetraj2_traj_lanes_off_hit, lanetraj3_traj_lanes_off_hit
   shotScoopEscape:
     switch: s_ir_scoop_detect
     reset_events: story_intro_complete, scoop_off
     advance_events: status_escape
     show_tokens:
       light: l_scoop
     profile: shotProfileScoopEscape

shot_profiles:
   traj_lanes:
     block: true
     advance_on_hit: false
     states:
       - name: off
       - name: available
   shotProfileScoopEscape:
     show_when_disabled: true
     advance_on_hit: false
     block: true
     states:
       - name: scoopInactive
         show: off
       - name: scoopActive
         show: popgreen

shot_groups:
   shot_group_traj:
       shots: lanetraj0, lanetraj1, lanetraj2, lanetraj3, lanetraj4
       rotate_left_events: s_flipper_left_active
       rotate_right_events: s_flipper_right_active
       enable_events: story_is_about_to_begin
       disable_events: ball_ending

# Mode 7 States
state_machines:
  beyond:
     states:
       start:
         label: mode_entry
         events_when_started: debug_beyond_start
       traj01:
         label: Set Trajectory 1
         events_when_started: debug_beyond_traj01
       traj01hit:
         label: Trajectory 1 Set
         events_when_started: debug_beyond_traj01hit
       traj02:
         label: Set Trajectory 2
         events_when_started: debug_beyond_traj02
       traj02hit:
         label: Trajectory 2 Set
         events_when_started: debug_beyond_traj02hit
       traj03:
         label: Set Trajectory 3
         events_when_started: debug_beyond_traj03
       scoopOpen:
         label: Scoop Open
         events_when_started: enable_scoop_loop, debug_beyond_scoop_open
       completion:
         label: completion
         events_when_started: debug_beyond_completion
     transitions:
       - source: start
         target: traj01
         events: enable_lane_shot
       - source: traj01hit
         target: traj02
         events: enable_lane_shot
       - source: traj02hit
         target: traj03
         events: enable_lane_shot
       - source: traj01
         target: start
         events: traj_time_out
       - source: traj02
         target: traj01hit
         events: traj_time_out
       - source: traj03
         target: traj02hit
         events: traj_time_out
       - source: traj01
         target: traj01hit
         events: traj_set
       - source: traj02
         target: traj02hit
         events: traj_set
       - source: traj03
         target: scoopOpen
         events: traj_set
       - source: scoopOpen
         target: traj03
         events: scoop_off
       - source: scoopOpen
         target: completion
         events: scoop_out_success


widgets:
   yt_escape_widget_02:
     - type: text
       font_size: 30
       text: " -- ENGINES ENGAGED ** ESCAPE THE BLACK HOLE --"
       y: 80%


