#config_version=5

config:
   - story02-scoring.yaml
   - infoboard.yaml

mode:
   start_events: ready_to_start_mode_2
   stop_events: story_is_completed
   priority: 900

# All Story Modes --
#     Issue a scoop_eject after any introduction activities
# Modes that end with a Scoop Hit --
#     Issue a scoop eject after any outro-activities

# Success/Failure
# By default, success = not losing ball, failure = losing ball
# If your mode has a different ruleset, change when the events
# story_is_completed_successful / acheivement_story##_successful
# story_is_completed_unsuccessful / acheivement_story##_unsuccessful
# are issued.

queue_relay_player:
  ball_ending:
    post: story_is_about_to_fail
    wait_for: story_outro_fail_complete

event_player:
   mode_story02_started:
     - story_is_about_to_begin
     - information_board_start
   in_mode_ball_save:
     - story_is_about_to_fail
   story_intro_complete:
     - scoop_eject
     - global_timer_unpause
#   shotScoopEscape_shotProfileScoopEscape_inactive_hit:
#     - scoop_eject
   shotScoopEscape_shotProfileScoopEscape_scoopActive_hit:
     - information_board_end
     - global_timer_pause
     - story_is_about_to_end
     - story02_is_about_to_end
   story_outro_complete:
     - global_timer_unpause
     - scoop_eject
     - story_is_completed_successful
     - acheivement_story02_successful
   story_outro_complete{current_player.escape_lane_count==3}:
     - random_character_collect|3100ms
   story_outro_fail_complete:
     - story_is_completed_unsuccessful
     - acheivement_story02_unsuccessful
   story_is_completed_successful:
    - story_is_completed
   story_is_completed_unsuccessful:
    - story_is_completed
   s_spinner_active{current_player.escape_scoop_enabled==0 and current_player.lane_spin_count<5}:
    - enable_lane_shot
   timer_traj_timer_complete:
    - traj_time_out
   lanetraj0_available_hit:
    - traj_set
   lanetraj1_available_hit:
    - traj_set
   lanetraj2_available_hit:
    - traj_set
   lanetraj3_available_hit:
    - traj_set
   lanetraj4_available_hit:
    - traj_set
   lanetraj0_off_hit:
    - traj_time_out
   lanetraj1_off_hit:
    - traj_time_out
   lanetraj2_off_hit:
    - traj_time_out
   lanetraj3_off_hit:
    - traj_time_out
   lanetraj4_off_hit:
    - traj_time_out
   enable_scoop_loop:
    - status_escape
   timer_scoop_timer_complete:
    - scoop_off


random_event_player:
  enable_lane_shot:
    - enable_lane_shot_1
    - enable_lane_shot_2
    - enable_lane_shot_3
    - enable_lane_shot_4
    - enable_lane_shot_5
  time_traj_timer_complete:
    - traj_time_out

#  Base intro / outro shows
show_player:
#   story_is_about_to_begin:
#      story_02_intro:
#         events_when_completed: story_intro_complete
#         loops: 0
   story_is_about_to_fail:
      story_02_fail_outro:
         events_when_completed: story_outro_fail_complete
         loops: 0
   story_is_about_to_end:
      story_02_outro:
         events_when_completed: story_outro_complete
         loops: 0
   shotScoopEscape_shotProfileScoopEscape_scoopInactive_hit:
      pinwheel:
        speed: 40
        loops: 1
        events_when_completed: scoop_eject
   player_shot_lanetraj0{value==1}:
      lane1shot:
        priority: 950
        loops: -1
      lane2shot:
        action: stop
      lane3shot:
        action: stop
      lane4shot:
        action: stop
      lane5shot:
        action: stop
   player_shot_lanetraj1{value==1}:
      lane2shot:
        priority: 950
        loops: -1
      lane1shot:
        action: stop
      lane3shot:
        action: stop
      lane4shot:
        action: stop
      lane5shot:
        action: stop
   player_shot_lanetraj2{value==1}:
      lane3shot:
        priority: 950
        loops: -1
      lane1shot:
        action: stop
      lane2shot:
        action: stop
      lane4shot:
        action: stop
      lane5shot:
        action: stop
   player_shot_lanetraj3{value==1}:
      lane4shot:
        priority: 950
        loops: -1
      lane1shot:
        action: stop
      lane2shot:
        action: stop
      lane3shot:
        action: stop
      lane5shot:
        action: stop
   player_shot_lanetraj4{value==1}:
      lane5shot:
        priority: 950
        loops: -1
      lane1shot:
        action: stop
      lane2shot:
        action: stop
      lane3shot:
        action: stop
      lane4shot:
        action: stop
   traj_time_out:
      lane1shot:
         action: stop
      lane2shot:
         action: stop
      lane3shot:
         action: stop
      lane4shot:
         action: stop
      lane5shot:
         action: stop
   traj_set:
      lane1shot:
         action: stop
      lane2shot:
         action: stop
      lane3shot:
         action: stop
      lane4shot:
         action: stop
      lane5shot:
         action: stop

# The below is mode specific data

timers:
   traj_timer:
     start_value: 50
     end_value: 0
     tick_interval: .1s
     direction: down
     start_running: no
     control_events:
       - event: enable_lane_shot
         action: restart
       - event: traj_time_out
         action: stop
       - event: traj_set
         action: pause
       - event: local_timer_pause
         action: pause
       - event: local_timer_unpause
         action: start

   scoop_timer:
     start_value: 150
     end_value: 0
     tick_interval: .1s
     direction: down
     start_running: no
     control_events:
       - event: enable_scoop_loop
         action: restart
       - event: local_timer_pause
         action: pause
       - event: local_timer_unpause
         action: start

shots:
   lanetraj0:
     switch: s_lane0
     profile: traj_lanes
     advance_events: enable_lane_shot_1
     reset_events: traj_time_out, traj_set, enable_lane_shot_2, enable_lane_shot_3, enable_lane_shot_4, enable_lane_shot_5, lanetraj1_traj_lanes_off_hit, lanetraj2_traj_lanes_off_hit, lanetraj3_traj_lanes_off_hit, lanetraj4_traj_lanes_off_hit
   lanetraj1:
     switch: s_lane1
     profile: traj_lanes
     advance_events: enable_lane_shot_2
     reset_events: traj_time_out, traj_set, enable_lane_shot_1, enable_lane_shot_3, enable_lane_shot_4, enable_lane_shot_5, lanetraj0_traj_lanes_off_hit, lanetraj2_traj_lanes_off_hit, lanetraj3_traj_lanes_off_hit, lanetraj4_traj_lanes_off_hit
   lanetraj2:
     switch: s_lane2
     profile: traj_lanes
     advance_events: enable_lane_shot_3
     reset_events: traj_time_out, traj_set, enable_lane_shot_1, enable_lane_shot_2, enable_lane_shot_4, enable_lane_shot_5, lanetraj0_traj_lanes_off_hit, lanetraj1_traj_lanes_off_hit, lanetraj3_traj_lanes_off_hit, lanetraj4_traj_lanes_off_hit
   lanetraj3:
     switch: s_lane3
     profile: traj_lanes
     advance_events: enable_lane_shot_4
     reset_events: traj_time_out, traj_set, enable_lane_shot_1, enable_lane_shot_2, enable_lane_shot_3, enable_lane_shot_5, lanetraj0_traj_lanes_off_hit, lanetraj1_traj_lanes_off_hit, lanetraj2_traj_lanes_off_hit, lanetraj4_traj_lanes_off_hit
   lanetraj4:
     switch: s_lane4
     profile: traj_lanes
     advance_events: enable_lane_shot_5
     reset_events: traj_time_out, traj_set, enable_lane_shot_1, enable_lane_shot_2, enable_lane_shot_3, enable_lane_shot_4, lanetraj0_traj_lanes_off_hit, lanetraj1_traj_lanes_off_hit, lanetraj2_traj_lanes_off_hit, lanetraj3_traj_lanes_off_hit
   shotScoopEscape:
     switch: s_ir_scoop_detect
     reset_events: story_intro_complete, scoop_off
     advance_events: status_escape
     show_tokens:
       light: l_scoop
     profile: shotProfileScoopEscape

shot_profiles:
   traj_lanes:
     block: false
     advance_on_hit: false
     states:
       - name: off
       - name: available
   shotProfileScoopEscape:
     show_when_disabled: true
     advance_on_hit: false
     block: false
     states:
       - name: scoopInactive
         show: off
       - name: scoopActive
         show: scoopReadyShow

shot_groups:
   shot_group_traj:
       shots: lanetraj0, lanetraj1, lanetraj2, lanetraj3, lanetraj4
       rotate_left_events: s_flipper_left_active
       rotate_right_events: s_flipper_right_active
       enable_events: story_is_about_to_begin
       disable_events: ball_ending

# Mode 7 States
state_machines:
  beyond:
     states:
       start:
         label: mode_entry
         events_when_started: debug_beyond_start
       traj01:
         label: Set Trajectory 1
         events_when_started: debug_beyond_traj01
       traj01hit:
         label: Trajectory 1 Set
         events_when_started: debug_beyond_traj01hit
       traj02:
         label: Set Trajectory 2
         events_when_started: debug_beyond_traj02
       traj02hit:
         label: Trajectory 2 Set
         events_when_started: debug_beyond_traj02hit
       traj03:
         label: Set Trajectory 3
         events_when_started: debug_beyond_traj03
       scoopOpen:
         label: Scoop Open
         events_when_started: enable_scoop_loop, debug_beyond_scoop_open
       completion:
         label: completion
         events_when_started: debug_beyond_completion
     transitions:
       - source: start
         target: traj01
         events: enable_lane_shot
       - source: traj01hit
         target: traj02
         events: enable_lane_shot
       - source: traj02hit
         target: traj03
         events: enable_lane_shot
       - source: traj01
         target: start
         events: traj_time_out
       - source: traj02
         target: traj01hit
         events: traj_time_out
       - source: traj03
         target: traj02hit
         events: traj_time_out
       - source: traj01
         target: traj01hit
         events: traj_set
       - source: traj02
         target: traj02hit
         events: traj_set
       - source: traj03
         target: scoopOpen
         events: traj_set
       - source: scoopOpen
         target: traj03
         events: scoop_off
       - source: scoopOpen
         target: completion
         events: scoop_out_success

sound_player:
    mode_story02_started:
      overture:
          action: stop
          fade_out: 0
    mode_02_end_video:
      durantisdead:
          action: play
          loops: -1
          mode_end_action: stop




