#config_version=5

config:
#   - ballsave.yaml
   - story02-scoring.yaml

#TODO We should fail the mode if stablization gets to 0
#TODO Character collect -- could be completion, or reaching stabilization

mode:
   start_events: selector_untitled_mode_2_selected
   stop_events: story_is_completed
   priority: 900

# All Story Modes --
#     Issue a scoop_eject after any introduction activities
# Modes that end with a Scoop Hit --
#     Issue a scoop eject after any outro-activities

# Success/Failure
# By default, success = not losing ball, failure = losing ball
# If your mode has a different ruleset, change when the events
# story_is_completed_successful / acheivement_story##_successful
# story_is_completed_unsuccessful / acheivement_story##_unsuccessful
# are issued.

queue_relay_player:
  ball_ending:
    post: story_is_about_to_fail
    wait_for: story_outro_fail_complete

event_player:
   mode_story02_started:
     - story_is_about_to_begin
   in_mode_ball_save:
     - story_is_about_to_fail
   story_intro_complete:
     - scoop_eject
#   shotScoopEscape_shotProfileScoopEscape_inactive_hit:
#     - scoop_eject
   shotScoopEscape_shotProfileScoopEscape_scoopActive_hit:
     - story_is_about_to_end
   story_outro_complete:
     - scoop_eject
     - story_is_completed_successful
     - acheivement_story02_successful
#TODO -- for now we are granting a character just for completing
     - random_character_collect|3100ms
   story_outro_fail_complete:
     - story_is_completed_unsuccessful
     - acheivement_story02_unsuccessful
   story_is_completed_successful:
    - story_is_completed
   story_is_completed_unsuccessful:
    - story_is_completed

#  Base intro / outro shows
show_player:
   story_is_about_to_begin:
      story_02_intro:
         events_when_completed: story_intro_complete
         loops: 0
   story_is_about_to_fail:
      story_02_fail_outro:
         events_when_completed: story_outro_fail_complete
         loops: 0
   story_is_about_to_end:
      story_02_outro:
         events_when_completed: story_outro_complete
         loops: 0
   shotScoopEscape_shotProfileScoopEscape_inactive_hit:
      pinwheel:
        speed: 40
        loops: 1
        events_when_completed: scoop_eject

shows:
   story_02_intro:
     - time: 0
       slides: story_02_intro_slide
       duration: 3
   story_02_fail_outro:
     - time: 0
       slides: story_02_outro_fail_slide
       duration: 3
   story_02_outro:
     - time: 0
       slides: story_02_outro_slide
       duration: 3

slides:
   story_02_intro_slide:
    widgets:
      - type: text
        text: Escape The Black Hole
        color: red
        font_size: 100
        font_name: ocr-a-tribute-bold
      - type: text
        text: Stabalize the Palomino by hitting Pop Bumpers
        y: 40%
        color: red
        font_size: 50
      - type: text
        text: When lit, hit the spinner to engage Thrusters
        y: 30%
        color: red
        font_size: 50
      - type: text
        text: Then ESCAPE the black hole out the scoop!
        y: 20%
        color: red
        font_size: 50
   story_02_outro_fail_slide:
    widgets:
      - type: text
        text: YOU FAILED TO ESCAPE THE BLACK HOLE
        color: red
        font_size: 60
        font_name: ocr-a-tribute-bold
      - type: text
        text: You are *NOT* super duper neat
        y: 40%
        color: red
        font_size: 50
   story_02_outro_slide:
    widgets:
      - type: text
        text: YOU HAVE ESCAPED THE BLACK HOLE
        color: red
        font_size: 80
        font_name: ocr-a-tribute-bold
      - type: text
        text: You are super duper neat
        y: 40%
        color: red
        font_size: 50

# The below is mode specific data


variable_player:
   story_intro_complete:
     stability:
       action: set
       int: 50
   timer_destablizer_tick:
      stability: -1
   shotgrouppopbumpers_hit:
      stability: 5


timers:
   destablizer:
     start_value: 0
     tick_interval: 1s
     direction: up
     start_running: no
     control_events:
       - event: story_intro_complete
         action: start

widget_player:
#   story_intro_complete:
#      yt_remain_widget_02:
#         slide: scoring_slide
   status_stabilize_engines:
      yt_remain_widget_02:
         slide: scoring_slide
   status_engage_engines:
      yt_remain_widget_02:
         action: remove
      yt_engine_widget_02:
         slide: scoring_slide
   remove_status_engage_engines:
      yt_engine_widget_02:
         action: remove
   status_escape:
      yt_engine_widget_02:
         action: remove
      yt_escape_widget_02:
         slide: scoring_slide
   story02_ended:
      yt_remain_widget_02:
         action: remove
      yt_engine_widget_02:
         action: remove

shots:
  spinnerEngines:
    switch: s_spinner
    show_tokens:
       light: l_spinner
    disable_events: status_stabilize_engines
    enable_events: status_engage_engines
  shotScoopEscape:
    switch: s_ir_scoop_detect
    reset_events: story_intro_complete
    advance_events: status_escape
    show_tokens:
      light: l_scoop
    profile: shotProfileScoopEscape

shot_profiles:
  shotProfileScoopEscape:
    show_when_disabled: true
    advance_on_hit: false
    block: true
    states:
      - name: inactive
        show: off
      - name: scoopActive
        show: popgreen

state_machines:
   escapeMachine:
     states:
       start:
         label: Start State
       stabilizeEngines:
         label: start
         events_when_started: status_stabilize_engines
       engageEngines:
         label: Engage State
         events_when_started: status_engage_engines
         events_when_stopped: remove_status_engage_engines
       escapeReady:
         label: Escape State
         events_when_started: status_escape
     transitions:
       - source: start
         target: stabilizeEngines
         events: story_intro_complete
       - source: stabilizeEngines
         target: engageEngines
         events: player_stability{value>=100}
       - source: engageEngines
         target: stabilizeEngines
         events: player_stability{value<100}
       - source: engageEngines
         target: escapeReady
         events: spinnerengines_hit


widgets:
   yt_remain_widget_02:
     - type: text
       text: "PALOMINO STABILITY: (stability)"
       y: 80%
   yt_engine_widget_02:
     - type: text
       text: " -- STABILITY ACHIEVED * ENGAGE ENGINES --"
       y: 80%
   yt_escape_widget_02:
     - type: text
       font_size: 30
       text: " -- ENGINES ENGAGED ** ESCAPE THE BLACK HOLE --"
       y: 80%


