#config_version=5

variable_player:
  story_is_about_to_begin:
     esacpe_lane_base:
        action: set
        int: 500000
     escape_lane_count:
        action: set
        int: 0
     escape_completed_scoring_base:
        action: set
        int: 10000000
     escape_scoop_enabled:
        action: set
        int: 0
     lane_spin_count:
        action: set
        int: 0
     modestat_2_base_scoring:
        action: set
        int: 0
     modestat_2_scoring:
        action: set
        int: 0
  enable_lane_shot:
     lane_spin_count: 1
  traj_time_out:
     lane_spin_count:
        action: set
        int: 0
  enable_scoop_loop:
     escape_scoop_enabled:
        action: set
        int: 1
  scoop_off:
     escape_scoop_enabled:
        action: set
        int: 0
  traj_set:
     escape_lane_count: 1
     bonuscount: 3
     lane_spin_count:
        action: set
        int: 0
  player_escape_lane_count{value==1}:
     score:
      int: current_player.esacpe_lane_base * current_player.temp_playfield_x * current_player.perm_playfield_x
      action: add
     modestat_2_scoring:
      int: current_player.esacpe_lane_base * current_player.temp_playfield_x * current_player.perm_playfield_x
      action: add
     modestat_2_base_scoring: current_player.esacpe_lane_base
  player_escape_lane_count{value==2}:
     score:
      int: 3 * current_player.esacpe_lane_base * current_player.temp_playfield_x * current_player.perm_playfield_x
      action: add
     modestat_2_scoring: 3 * current_player.esacpe_lane_base * current_player.temp_playfield_x * current_player.perm_playfield_x
     modestat_2_base_scoring: 3 * current_player.esacpe_lane_base
  player_escape_lane_count{value==3}:
     score:
      int: 6 * current_player.esacpe_lane_base * current_player.temp_playfield_x * current_player.perm_playfield_x
      action: add
     modestat_2_scoring: 6 * current_player.esacpe_lane_base * current_player.temp_playfield_x * current_player.perm_playfield_x
     modestat_2_base_scoring: 6 * current_player.esacpe_lane_base
  player_escape_lane_count{value>3}:
     score:
      int: current_player.esacpe_lane_base * current_player.temp_playfield_x * current_player.perm_playfield_x
      action: add
     escape_completed_scoring_base: -1000000
     modestat_2_scoring: current_player.esacpe_lane_base * current_player.temp_playfield_x * current_player.perm_playfield_x
     modestat_2_base_scoring: current_player.esacpe_lane_base
  player_escape_completed_scoring_base{value==0}:
     escape_completed_scoring_base: 1000000
  shotScoopEscape_shotProfileScoopEscape_scoopActive_hit:
     score: current_player.escape_completed_scoring_base * current_player.temp_playfield_x * current_player.perm_playfield_x
     bonuscount: 10
     mode2_final_score_display: current_player.escape_completed_scoring_base * current_player.temp_playfield_x * current_player.perm_playfield_x
     modestat_2_scoring: current_player.escape_completed_scoring_base * current_player.temp_playfield_x * current_player.perm_playfield_x
     modestat_2_base_scoring: current_player.escape_completed_scoring_base
