#config_version=5

assets:
    sounds:
        default:
            track: sfx
        music:
            track: music
        sfx:
            track: sfx
        voice:
            track: voice
    images:
        default:
            load: preload
        preload:
            load: preload
        on_demand:
            load: on_demand

images:
    logo:
       file: BlackholeLogo.gif
    david_goliath:
       file: MaxVsVincent.jpg
