#config_version=5

assets:
    sounds:
        default:
            track: sfx
        music:
            track: music
        sfx:
            track: sfx
        voice:
            track: voice
    images:
        default:
            load: preload
        preload:
            load: preload
        on_demand:
            load: on_demand

images:
    cygnus_logo:
       file: Black-Hole-Movie.jpg
    logo:
       file: BlackholeLogo.gif
    starfield:
       file: starfield.jpg
    david_goliath:
       file: MaxVsVincent.jpg
    singlePlayerScoreFrame:
       file: CurrentPlayerScoreForSingle.png
    multiPlayerScoreFrame:
       file: CurrentPlayerScoreForMultiple.png
    ballBar:
       file: BallBar.png
    ballSpinner:
       file: BallSpinner.png
    bonusBase:
       file: BonusBase.png
    bonusPopBox:
       file: BonusPopBox.png
    leftBar:
       file: LeftBar.png
    multiScoreLeft:
       file: MultiPlayerHoldBoxLeft.png
    multiScoreMid:
       file: MultiPlayerHoldBoxMiddle.png
    multiScoreMidDummy:
       file: MultiPlayerDummyBoxMiddle.png
    multiScoreRight:
       file: MultiPlayerHoldBoxRight.png
    badgeLocateTheCygnus:
       file: badge-locate_the_cygnus.png
    badgeLocateTheCygnusOff:
       file: badge-locate_the_cygnus-off.png
    badgeEscapeOff:
       file: badge-escape_the_black_hole-off.png
    badgeEscape:
       file: badge-escape_the_black_hole.png
    badgeShootingOff:
       file: badge-shooting_gallery-off.png
    badgeShooting:
       file: badge-shooting_gallery.png
    badgeMeteorOff:
       file: badge-meteor_strike-off.png
    badgeMeteor:
       file: badge-meteor_strike.png
    badgeCorridorOff:
       file: badge-corridor_battle-off.png
    badgeCorridor:
       file: badge-corridor_battle.png
    badgeDavidOff:
       file: badge-david_vs_goliath-off.png
    badgeDavid:
       file: badge-david_vs_goliath.png
    badgeBeyondOff:
       file: badge-in_through_beyond-off.png
    badgeBeyond:
       file: badge-in_through_beyond.png
