#config_version=5

assets:
    sounds:
        default:
            track: sfx
        music:
            track: music
        sfx:
            track: sfx
        voice:
            track: voice
    images:
        default:
            load: preload
        preload:
            load: preload
        on_demand:
            load: on_demand

images:
    cygnus_logo:
       file: Black-Hole-Movie.jpg
    logo:
       file: BlackholeLogo.gif
    starfield:
       file: starfield.jpg
    david_goliath:
       file: MaxVsVincent.jpg
    singlePlayerScoreFrame:
       file: CurrentPlayerScoreForSingle.png
    multiPlayerScoreFrame:
       file: CurrentPlayerScoreForMultiple.png
    ballBar:
       file: BallBar.png
    ballSpinner:
       file: BallSpinner.png
    bonusBase:
       file: BonusBase.png
    bonusPopBox:
       file: BonusPopBox.png
    leftBar:
       file: LeftBar.png
    multiScoreLeft:
       file: MultiPlayerHoldBoxLeft.png
    multiScoreMid:
       file: MultiPlayerHoldBoxMiddle.png
    multiScoreMidDummy:
       file: MultiPlayerDummyBoxMiddle.png
    multiScoreRight:
       file: MultiPlayerHoldBoxRight.png
