#config_version=5

assets:
    sounds:
        default:
            track: sfx
        music:
            track: music
        sfx:
            track: sfx
        voice:
            track: voice
    images:
        default:
            load: preload
        preload:
            load: preload
        on_demand:
            load: on_demand

images:
    cygnus_logo:
       file: Black-Hole-Movie.jpg
    logo:
       file: BlackholeLogo.gif
    starfield:
       file: starfield.jpg
    david_goliath:
       file: MaxVsVincent-sm.jpg
    singlePlayerScoreFrame:
       file: CurrentPlayerScoreForSingle.png
    scoreBlueLightLitSp:
       file: score_blue_light_box-lit-sp.png
    multiPlayerScoreFrame:
       file: CurrentPlayerScoreForMultiple.png
    scoreBlueLightLitMp:
       file: score_blue_light_box-lit-mp.png
    ballBar:
       file: BallBar.png
    ballSpinner:
       file: BallSpinner.png
    bonusBase:
       file: BonusBase.png
    bonusPopBox:
       file: BonusPopBox.png
    leftBar:
       file: LeftBar.png
    leftGreenLightsLit:
       file: left_green_light_bundle-lit.png
    multiScoreLeft:
       file: MultiPlayerHoldBoxLeft.png
    multiScoreMid:
       file: MultiPlayerHoldBoxMiddle.png
    multiScoreMidDummy:
       file: MultiPlayerDummyBoxMiddle.png
    multiScoreRight:
       file: MultiPlayerHoldBoxRight.png
    badgeLocateTheCygnus:
       file: badge-locate_the_cygnus.png
    badgeLocateTheCygnusOff:
       file: badge-locate_the_cygnus-off.png
    badgeEscapeOff:
       file: badge-escape_the_black_hole-off.png
    badgeEscape:
       file: badge-escape_the_black_hole.png
    badgeShootingOff:
       file: badge-shooting_gallery-off.png
    badgeShooting:
       file: badge-shooting_gallery.png
    badgeMeteorOff:
       file: badge-meteor_strike-off.png
    badgeMeteor:
       file: badge-meteor_strike.png
    badgeCorridorOff:
       file: badge-corridor_battle-off.png
    badgeCorridor:
       file: badge-corridor_battle.png
    badgeDavidOff:
       file: badge-david_vs_goliath-off.png
    badgeDavid:
       file: badge-david_vs_goliath.png
    badgeBeyondOff:
       file: badge-in_through_beyond-off.png
    badgeBeyond:
       file: badge-in_through_beyond.png
    badgeLocateTheCygnusBig:
       file: badge-locate_the_cygnus-big.png
    badgeEscapeBig:
       file: badge-escape_the_black_hole-big.png
    badgeShootingBig:
       file: badge-shooting_gallery-big.png
    badgeMeteorBig:
       file: badge-meteor_strike-big.png
    badgeCorridorBig:
       file: badge-corridor_battle-big.png
    badgeDavidBig:
       file: badge-david_vs_goliath-big.png
    badgeBeyondBig:
       file: badge-in_through_beyond-big.png
    checkmark:
       file: checkmark.png
    nomark:
       file: nomark.png
#    redx:
#       file: redx.png
    alex:
       file: alex.png
    alexoff:
       file: alex-off.png
    charlie:
       file: charlie.png
    charlieoff:
       file: charlie-off.png
    dan:
       file: dan.png
    danoff:
       file: dan-off.png
    kate:
       file: kate.png
    kateoff:
       file: kate-off.png
    harry:
       file: harry.png
    harryoff:
       file: harry-off.png
    hanz:
       file: hanz.png
    hanzoff:
       file: hanz-off.png
    vincent:
       file: vincent.png
    vincentoff:
       file: vincent-off.png
    bob:
       file: bob.png
    boboff:
       file: bob-off.png
    tbh-slide-template:
       file: TBH-SlideTemplate.png
    mode_title_display_box:
       file: mode-title-display-box.png
# Experimental Assets
    mode_title_exit_box:
       file: mode-exit-display-box.png
# Thank you slides
    thank_you_proc:
       file: ty01-p-roc-logo.png
    belles_phx:
       file: bandclogo_phoenix.jpg
    firebird:
       file: firebird-pinball.jpg
    missionpinball:
       file: mpf-logo-200.png
    prusa:
       file: prusaresearch-logo-final-2017.png
    marco:
       file: marco-logo.gif
    pblife:
       file: pinball-life.png
    pinside:
       file: pinside.png
    starfighters:
       file: starfighters.jpg
    pf1:
       file: phoenix-flyer-1.jpg
    pf2:
       file: phoenix-flyer-2.jpg
    pf3:
       file: phoenix-flyer.jpg
    pf4:
       file: phoenix-flyer-4.jpg
