#config_version=5
config:
  - hardware.yaml
  - sound.yaml
  - assets.yaml

#slides:
#  welcome_slide:
#    widgets:
#      - type: text
#        text: PINBALL!
#        font_size: 50
#        color: red
#      - type: rectangle
#        width: 240
#        height: 60
#
#slide_player:
#  init_done: welcome_slide

modes:
  - base
  - high_score
  - bonus

player_vars:
  pops:
     initial_value: 0
  drops:
     initial_value: 0
  bonusmulti:
     initial_value: 1


keyboard:
  "!":
    switch: s_credit
  t:
    switch: s_dTargetCL
  y:
    switch: s_dTargetCR
  q:
    switch: s_dTargetL0
  w:
    switch: s_dTargetL1
  e:
    switch: s_dTargetL2
  r:
    switch: s_dTargetL3
  u:
    switch: s_dTargetR3
  i:
    switch: s_dTargetR2
  o:
    switch: s_dTargetR1
  p:
    switch: s_dTargetR0
  d:
    switch: s_drain
  z:
    switch: s_flipper_left
  a:
    switch: s_flipper_right
  s:
    switch: s_start
  "[":
    switch: s_ir_scoop_detect
  j:
    switch: s_jet_lower_center
  k:
    switch: s_jet_upper_left
  l:
    switch: s_jet_upper_right
  0:
    switch: s_lane0
  1:
    switch: s_lane1
  2:
    switch: s_lane2
  3:
    switch: s_lane3
  4:
    switch: s_lane4
  x:
    switch: s_roOutLaneLeft
  c:
    switch: s_roInLaneLeft
  v:
    switch: s_roInLaneRight
  b:
    switch: s_roOutLaneRight
  f:
    switch: s_sTargetDropL
  g:
    switch: s_sTargetDropR
  n:
    switch: s_sTargetLowL
  m:
    switch: s_sTargetLowR
  ",":
    switch: s_slingshot_left
  ".":
    switch: s_slingshot_right
  6:
    switch: s_sTargetYellowL
  8:
    switch: s_sTargetYellowR
  7:
    switch: s_spinner
  5:
    switch: diag01
  9:
    switch: diag02
  "-":
    switch: diag03
  "=":
    switch: diag04



