#config_version=5
config:
  - hardware.yaml
  - sound.yaml
  - assets.yaml
  - widgets.yaml
  - lights.yaml
  - scriptlets.yaml
  - switches.yaml
  - display.yaml

#slides:
#  welcome_slide:
#    widgets:
#      - type: text
#        text: PINBALL!
#        font_size: 50
#        color: red
#      - type: rectangle
#        width: 240
#        height: 60
#
#slide_player:
#  init_done: welcome_slide

modes:
  - base
#  - selector
  - selector2
  - high_score
  - bonus
  - story01
  - story02
  - story03
  - story04
  - story05
  - story06
  - story07
  - information
  - ball_goals
  - notify
  - storyScoopOverride
  - playfieldTriple
  - playfieldDouble
  - superJets
  - superSpins
  - insaneSpins
  - endOfGame
  - outlaneBots
#  - yt_hurry_up
#  - pop_red
#  - pop_green
#  - pop_blue

player_vars:
  pops:
     initial_value: 0
  drops:
     initial_value: 0
  spins:
     initial_value: 0
  bonuscount:
     initial_value: 0
  bonus_multiplier:
     initial_value: 1
  bonustype1:
     initial_value: 0
  bonustype2:
     initial_value: 0
  bonustype3:
     initial_value: 0
  bonustype4:
     initial_value: 0
  bonusTypeMax:
     initial_value: 1

# Normal Game Settings
  status_untitled_mode_1:
     initial_value: 0
  status_untitled_mode_2:
     initial_value: 0
  status_untitled_mode_3:
     initial_value: 0
  status_untitled_mode_4:
     initial_value: 0
  status_untitled_mode_5:
     initial_value: 0
  status_untitled_mode_6:
     initial_value: 0
  status_untitled_mode_7:
     initial_value: 0

# Testing Mode 7
#  status_untitled_mode_1:
#     initial_value: 1
#  status_untitled_mode_2:
#     initial_value: 1
#  status_untitled_mode_3:
#     initial_value: 1
#  status_untitled_mode_4:
#     initial_value: 1
#  status_untitled_mode_5:
#     initial_value: 1
#  status_untitled_mode_6:
#     initial_value: 1
#  status_untitled_mode_7:
#     initial_value: 0

# This is where some mode achievement text can be stored
  modestat_1_final_timing:
     initial_value: 0.0
     value_type: float
  modestat_3_final_hits:
     initial_value: 0
     value_type: int
  modestat_4_final_hits:
     initial_value: 0
     value_type: int
  modestat_5_final_extra_time:
     initial_value: 0.0
     value_type: float
  modestat_6_final_time:
     initial_value: 0.0
     value_type: float

keyboard:
  "!":
    switch: s_credit
  t:
    switch: s_dtargetcl
  y:
    switch: s_dtargetcr
  q:
    switch: s_dTargetL0
  w:
    switch: s_dTargetL1
  e:
    switch: s_dTargetL2
  r:
    switch: s_dTargetL3
  u:
    switch: s_dTargetR3
  i:
    switch: s_dTargetR2
  o:
    switch: s_dTargetR1
  p:
    switch: s_dTargetR0
  d:
    switch: s_drain
  z:
    switch: s_flipper_left
  a:
    switch: s_flipper_right
  s:
    switch: s_start
  "[":
    switch: s_ir_scoop_detect
  j:
    switch: s_jet_lower_center
  k:
    switch: s_jet_upper_left
  l:
    switch: s_jet_upper_right
  0:
    switch: s_lane0
  1:
    switch: s_lane1
  2:
    switch: s_lane2
  3:
    switch: s_lane3
  4:
    switch: s_lane4
  x:
    switch: s_rooutlaneleft
  c:
    switch: s_roInLaneLeft
  v:
    switch: s_roInLaneRight
  b:
    switch: s_rooutlaneright
  f:
    switch: s_sTargetDropL
  g:
    switch: s_sTargetDropR
  n:
    switch: s_sTargetLowL
  m:
    switch: s_sTargetLowR
  ",":
    switch: s_slingshot_left
  ".":
    switch: s_slingshot_right
  6:
    switch: s_sTargetYellowL
  8:
    switch: s_sTargetYellowR
  7:
    switch: s_spinner
  5:
    switch: diag01
  9:
    switch: diag02
  "-":
    switch: diag03
  "=":
    switch: diag04



