#config_version=5

hardware:
  platform: p3_roc
  driverboards: pdb

p3_roc:
  use_watchdog: true
  watchdog_time: 1s

displays:
  lcd:
    width: 1366
    height: 768
    default: true

window:
  width: 1366
  height: 768
  title: The Black Hole
  resizable: false
  fullscreen: false
  borderless: false
  exit_on_escape: true
  source_display: lcd

switches:
  #Cabinet switches
  s_drain: #wired to left side controller
    number: 0/1/7
  s_start: #wired to right side controller
    number: 1/1/7
    tags: start

  #Left side switches
  s_flipper_left:
    number: 0/0/0
    tags: left_flipper
  s_slingshot_left:
    number: 0/0/1
    tags: playfield_active
  s_sTargetLowL:
    number: 0/0/2
    tags: playfield_active
  s_sTargetDropL:
    number: 0/0/3
    tags: playfield_active
  s_dTargetL0:
    number: 0/0/4
    tags: playfield_active
  s_dTargetL1:
    number: 0/0/5
    tags: playfield_active
  s_dTargetL2:
    number: 0/0/6
    tags: playfield_active
  s_dTargetL3:
    number: 0/0/7
    tags: playfield_active
  s_roOutLaneLeft:
    number: 0/1/0
    tags: playfield_active
  s_roInLaneLeft:
    number: 0/1/1
    tags: playfield_active
  s_sTargetYellowL:
    number: 0/1/2
    tags: playfield_active
  s_sTargetUpperL:
    number: 0/1/3
    tags: playfield_active
  s_ir_scoop_detect:
    number: 0/1/4
    type: NC

  #Right side switches
  s_flipper_right:
    number: 1/0/0
    tags: right_flipper
  s_slingshot_right:
    number: 1/0/1
    tags: playfield_active
  s_sTargetLowR:
    number: 1/0/2
    tags: playfield_active
  s_sTargetDropR:
    number: 1/0/3
    tags: playfield_active
  s_dTargetR0:
    number: 1/0/4
    tags: playfield_active
  s_dTargetR1:
    number: 1/0/5
    tags: playfield_active
  s_dTargetR2:
    number: 1/0/6
    tags: playfield_active
  s_dTargetR3:
    number: 1/0/7
    tags: playfield_active
  s_roOutLaneRight:
    number: 1/1/0
    tags: playfield_active
  s_roInLaneRight:
    number: 1/1/1
    tags: playfield_active
  s_sTargetYellowR:
    number: 1/1/2
    tags: playfield_active
  s_sTargetUpperR:
    number: 1/1/3
    tags: playfield_active
  s_spinner:
    number: 1/1/4
    tags: playfield_active

  #Upper and center switches
  s_lane0:
    number: 2/0/0
    tags: playfield_active
  s_lane1:
    number: 2/0/1
    tags: playfield_active
  s_lane2:
    number: 2/0/2
    tags: playfield_active
  s_lane3:
    number: 2/0/3
    tags: playfield_active
  s_lane4:
    number: 2/0/4
    tags: playfield_active
  s_jet_upper_left:
    number: 2/1/0
    tags: playfield_active
  s_jet_lower_center:
    number: 2/1/1
    tags: playfield_active
  s_jet_upper_right:
    number: 2/1/2
    tags: playfield_active
  s_dTargetCL:
    number: 2/1/4
    tags: playfield_active
  s_dTargetCR:
    number: 2/1/3
    tags: playfield_active
  s_credit: #wired to upper/center controller
    number: 2/1/7


coils:
  c_flipper_right_main:
    number: A0-B0-0
    default_pulse_ms: 7
    debug: true
    allow_enable: true
  c_flipper_left_main:
    number: A0-B1-0
    default_pulse_ms: 7
    debug: true
    allow_enable: true
  c_slingshot_right:
    number: A0-B0-1
    default_pulse_ms: 12
  c_dropRight0:
    number: A0-B0-2
    default_pulse_ms: 60
  c_dropRight1:
    number: A0-B0-3
    default_pulse_ms: 60
  c_dropCenterR:
    number: A0-B0-4
    default_pulse_ms: 60
  c_jet_upper_right:
    number: A0-B0-5
    default_pulse_ms: 20
  c_drain_eject:
    number: A0-B0-6
    default_pulse_ms: 15
  c_slingshot_left:
    number: A0-B1-1
    default_pulse_ms: 12
  c_dropLeft0:
    debug: true
    number: A0-B1-2
    default_pulse_ms: 60
  c_dropLeft1:
    number: A0-B1-3
    default_pulse_ms: 60
  c_dropCenterL:
    number: A0-B1-4
    default_pulse_ms: 60
  c_jet_lower_center:
    number: A0-B1-5
    default_pulse_ms: 20
  c_jet_upper_left:
    number: A0-B1-6
    default_pulse_ms: 20
  c_scoop_eject:
    number: A0-B1-7
    default_pulse_ms: 45

playfields:
  playfield:
    tags: default
    default_source_device: bd_drain

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    activation_switch: s_flipper_left
    debug: true
  right_flipper:
    main_coil: c_flipper_right_main
    activation_switch: s_flipper_right
    debug: true

ball_devices:
  bd_drain:
    ball_switches: s_drain
    eject_coil: c_drain_eject
    tags: drain, home, trough
    debug: true
  bd_scoop:
    ball_switches: s_ir_scoop_detect
    eject_coil: c_scoop_eject
    eject_timeouts: 3s
    debug: true

autofire_coils:
  slingshot_left:
    coil: c_slingshot_left
    switch: s_slingshot_left
    timeout_watch_time: 1s
    timeout_max_hits: 1
    timeout_disable_time: 300ms
  slingshot_right:
    coil: c_slingshot_right
    switch: s_slingshot_right
    timeout_watch_time: 1s
    timeout_max_hits: 1
    timeout_disable_time: 300ms
  jet_upper_left:
    coil: c_jet_upper_left
    switch: s_jet_upper_left
  jet_upper_right:
    coil: c_jet_upper_right
    switch: s_jet_upper_right
  jet_lower_center:
    coil: c_jet_lower_center
    switch: s_jet_lower_center

drop_targets:
     L0:
         switch: s_dTargetL0
     L1:
         switch: s_dTargetL1
     L2:
         switch: s_dTargetL2
     L3:
         switch: s_dTargetL3
     R0:
         switch: s_dTargetR0
     R1:
         switch: s_dTargetR1
     R2:
         switch: s_dTargetR2
     R3:
         switch: s_dTargetR3
     LC:
         switch: s_dTargetCL
     RC:
         switch: s_dTargetCR

drop_target_banks:
     leftFull:
         drop_targets: L0, L1, L2, L3
         reset_coils: c_dropLeft0, c_dropLeft1
         reset_on_complete: 500ms
         reset_events:
           ball_starting: 300ms
         debug: true
     rightFull:
         drop_targets: R0, R1, R2, R3
         reset_coils: c_dropRight0, c_dropRight1
         reset_on_complete: 500ms
         reset_events:
           ball_starting: 300ms
     leftCenter:
         drop_targets: LC
         reset_coils: c_dropCenterL
         reset_on_complete: 500ms
         reset_events:
           ball_starting: 300ms
     rightCenter:
         drop_targets: RC
         reset_coils: c_dropCenterR
         reset_on_complete: 500ms
         reset_events:
           ball_starting: 300ms

lights:

  l_yellowTargetLeft: #needs to be drilled
    number: 4-48-49-50
    subtype: led
    platform_settings:
      polarity: true
  l_yellowTargetRight: #needs to be drilled
    number: 4-51-52-53
    subtype: led
    platform_settings:
      polarity: true
  l_GIScoopLR: #needs to be drilled
    number: 4-81-82-83
    subtype: led
    platform_settings:
      polarity: true
  l_GIScoopMR: #needs to be drilled
    number: 4-0-1-2
    subtype: led
    platform_settings:
      polarity: true

#-----------------------------------------------------------------------
#LED BOARD 1
#-----------------------------------------------------------------------
#J5   0..11
  l_jetUpperRight:
    number: 1-0-1-2
    subtype: led
    platform_settings:
      polarity: true
  l_jetUpperLeft:
    number: 1-3-4-5
    subtype: led
    platform_settings:
      polarity: true

#J9  12..23
  l_GIAboveScoopLower:
    number: 1-12-13-14
    subtype: led
    platform_settings:
      polarity: true
  l_GILane0:
    number: 1-15-16-17
    subtype: led
    platform_settings:
      polarity: true
  l_GIScoopUC:
    number: 1-18-19-20
    subtype: led
    platform_settings:
      polarity: true

#J6  24..35
  l_GILane1:
    number: 1-24-25-26
    subtype: led
    platform_settings:
      polarity: true
  l_GILane2:
    number: 1-27-28-29
    subtype: led
    platform_settings:
      polarity: true
  l_GILane3:
    number: 1-30-31-32
    subtype: led
    platform_settings:
      polarity: true
  l_GILane4:
    number: 1-33-34-35
    subtype: led
    platform_settings:
      polarity: true

#J10 36..47
  l_GIAboveScoopUpper:
    number: 1-36-37-38
    subtype: led
    platform_settings:
      polarity: true
  l_GIUpperL:
    number: 1-39-40-41
    subtype: led
    platform_settings:
      polarity: true
  l_lane0:
    number: 1-42-43-44
    subtype: led
    platform_settings:
      polarity: true
  l_GIUpperCL:
    number: 1-45-46-47
    subtype: led
    platform_settings:
      polarity: true

#J7  48..59
  l_lane1:
    number: 1-48-49-50
    subtype: led
    platform_settings:
      polarity: true
  l_lane2:
    number: 1-51-52-53
    subtype: led
    platform_settings:
      polarity: true
  l_lane3:
    number: 1-54-55-56
    subtype: led
    platform_settings:
      polarity: true
  l_lane4:
    number: 1-57-58-59
    subtype: led
    platform_settings:
      polarity: true

#J11 60..71
  l_GILane5:
    number: 1-60-61-62
    subtype: led
    platform_settings:
      polarity: true
  l_GIAboveSpinnerUpper:
    number: 1-63-64-65
    subtype: led
    platform_settings:
      polarity: true
  l_GIUpperCR:
    number: 1-66-67-68
    subtype: led
    platform_settings:
      polarity: true
  l_GIUpperR:
    number: 1-69-70-71
    subtype: led
    platform_settings:
      polarity: true


#J8  72..83
  l_GIAboveSpinnerLower:
    number: 1-72-73-74
    subtype: led
    platform_settings:
      polarity: true
  l_spinner:
    number: 1-75-76-77
    subtype: led
    platform_settings:
      polarity: true
  l_GIDropRight0:
    number: 1-78-79-80
    subtype: led
    platform_settings:
      polarity: true
  l_GIDropRight1:
    number: 1-81-82-83
    subtype: led
    platform_settings:
      polarity: true

#-----------------------------------------------------------------------
#LED BOARD 2
#-----------------------------------------------------------------------
#J5   0..11
  l_GIDropCenterLeft:
    number: 2-0-1-2
    subtype: led
    platform_settings:
      polarity: true
  l_GIDropCenterRight:
    number: 2-3-4-5
    subtype: led
    platform_settings:
      polarity: true
  l_jetLowerCenter:
    number: 2-6-7-8
    subtype: led
    platform_settings:
      polarity: true

#J9  12..23
  l_dropRight3:
    number: 2-12-13-14
    subtype: led
    platform_settings:
      polarity: true
  l_dropRight2:
    number: 2-15-16-17
    subtype: led
    platform_settings:
      polarity: true
  l_dropRight1:
    number: 2-18-19-20
    subtype: led
    platform_settings:
      polarity: true
  l_dropRight0:
    number: 2-21-22-23
    subtype: led
    platform_settings:
      polarity: true

#J6  24..35
  l_bonusBig1:
    number: 2-24-25-26
    subtype: led
    platform_settings:
      polarity: true
  l_bonus7:
    number: 2-27-28-29
    subtype: led
    platform_settings:
      polarity: true
  l_bonus8:
    number: 2-30-31-32
    subtype: led
    platform_settings:
      polarity: true
  l_dropCenterRight:
    number: 2-33-34-35
    subtype: led
    platform_settings:
      polarity: true

#J10 36..47
  l_bonus4:
    number: 2-36-37-38
    subtype: led
    platform_settings:
      polarity: true
  l_bonus5:
    number: 2-39-40-41
    subtype: led
    platform_settings:
      polarity: true
  l_bonus6:
    number: 2-42-43-44
    subtype: led
    platform_settings:
      polarity: true
  l_bonusBig0:
    number: 2-45-46-47
    subtype: led
    platform_settings:
      polarity: true

#J7  48..59
  l_dropLeft0:
    number: 2-48-49-50
    subtype: led
    platform_settings:
      polarity: true
  l_dropLeft1:
    number: 2-51-52-53
    subtype: led
    platform_settings:
      polarity: true
  l_dropLeft2:
    number: 2-54-55-56
    subtype: led
    platform_settings:
      polarity: true
  l_dropLeft3:
    number: 2-57-58-59
    subtype: led
    platform_settings:
      polarity: true

#J11 60..71
  l_mode4:
    number: 2-60-61-62
    subtype: led
    platform_settings:
      polarity: true
  l_mode5:
    number: 2-63-64-65
    subtype: led
    platform_settings:
      polarity: true
  l_mode6:
    number: 2-66-67-68
    subtype: led
    platform_settings:
      polarity: true
  l_dropCenterLeft:
    number: 2-69-70-71
    subtype: led
    platform_settings:
      polarity: true

#J8  72..83
  l_scoop:
    number: 2-72-73-74
    subtype: led
    platform_settings:
      polarity: true
  l_GIScoopLL:
    number: 2-75-76-77
    subtype: led
    platform_settings:
      polarity: true
  l_GIScoopML:
    number: 2-78-79-80
    subtype: led
    platform_settings:
      polarity: true

#-----------------------------------------------------------------------
#LED BOARD 3
#-----------------------------------------------------------------------
#J5 0..11
  l_GISlingLeft1:
    number: 3-0-1-2
    subtype: led
    platform_settings:
      polarity: true
  l_GILowLeft:
    number: 3-3-4-5
    subtype: led
    platform_settings:
      polarity: true
  l_GIDropLeft0:
    number: 3-6-7-8
    subtype: led
    platform_settings:
      polarity: true
  l_GIDropLeft1:
    number: 3-9-10-11
    subtype: led
    platform_settings:
      polarity: true

#J9 12..23
  l_mode0:
    number: 3-12-13-14
    subtype: led
    platform_settings:
      polarity: true
  l_mode1:
    number: 3-15-16-17
    subtype: led
    platform_settings:
      polarity: true
  l_mode2:
    number: 3-18-19-20
    subtype: led
    platform_settings:
      polarity: true
  l_mode3:
    number: 3-21-22-23
    subtype: led
    platform_settings:
      polarity: true

#J6 24..35
  l_bonus3:
    number: 3-24-25-26
    subtype: led
    platform_settings:
      polarity: true
  l_bonus2:
    number: 3-27-28-29
    subtype: led
    platform_settings:
      polarity: true
  l_bonus1:
    number: 3-30-31-32
    subtype: led
    platform_settings:
      polarity: true
  l_bonus0:
    number: 3-33-34-35
    subtype: led
    platform_settings:
      polarity: true

#J10 36..47 -- Flipper Lane GI Planned Here

#J7 48..59
  l_specialRight:
    number: 3-48-49-50
    subtype: led
    platform_settings:
      polarity: true
  l_GISlingRight0:
    number: 3-51-52-53
    subtype: led
    platform_settings:
      polarity: true
  l_GISlingRight1:
    number: 3-54-55-56
    subtype: led
    platform_settings:
      polarity: true
  l_GILowRight:
    number: 3-57-58-59
    subtype: led
    platform_settings:
      polarity: true

#J11 60..71
  l_5x:
    number: 3-60-61-62
    subtype: led
    platform_settings:
      polarity: true
  l_4x:
    number: 3-63-64-65
    subtype: led
    platform_settings:
      polarity: true
  l_3x:
    number: 3-66-67-68
    subtype: led
    platform_settings:
      polarity: true
  l_2x:
    number: 3-69-70-71
    subtype: led
    platform_settings:
      polarity: true


#J8 72..83
  l_shootAgain:
    number: 3-72-73-74
    subtype: led
    platform_settings:
      polarity: true
  l_GISlingLeft0:
    number: 3-75-76-77
    subtype: led
    platform_settings:
      polarity: true
  l_specialLeft:
    number: 3-78-79-80
    subtype: led
    platform_settings:
      polarity: true
  l_GICreditsIn:
    number: 3-81-82-83
    subtype: led
    platform_settings:
      polarity: true




virtual_platform_start_active_switches:
  s_drain