#config_version=5

hardware:
  platform: p3_roc
  driverboards: pdb

p3_roc:
  use_watchdog: true
  watchdog_time: 1s

displays:
  lcd:
    width: 1366
    height: 768
    default: true

window:
  width: 1366
  height: 768
  title: The Black Hole
  resizable: false
  fullscreen: false
  borderless: false
  exit_on_escape: true
  source_display: lcd

coils:
  c_flipper_right_main:
    number: A0-B0-0
    default_pulse_ms: 7
    debug: true
    allow_enable: true
  c_flipper_left_main:
    number: A0-B1-0
    default_pulse_ms: 7
    debug: true
    allow_enable: true
  c_slingshot_right:
    number: A0-B0-1
    default_pulse_ms: 12
  c_dropRight0:
    number: A0-B0-2
    default_pulse_ms: 25
  c_dropRight1:
    number: A0-B0-3
    default_pulse_ms: 25
  c_dropCenterR:
    number: A0-B0-4
    default_pulse_ms: 25
  c_jet_upper_right:
    number: A0-B0-5
    default_pulse_ms: 20
  c_drain_eject:
    number: A0-B0-6
    default_pulse_ms: 15
  c_slingshot_left:
    number: A0-B1-1
    default_pulse_ms: 12
  c_dropLeft0:
    debug: true
    number: A0-B1-2
    default_pulse_ms: 25
  c_dropLeft1:
    number: A0-B1-3
    default_pulse_ms: 25
  c_dropCenterL:
    number: A0-B1-4
    default_pulse_ms: 25
  c_jet_lower_center:
    number: A0-B1-5
    default_pulse_ms: 30
  c_jet_upper_left:
    number: A0-B1-6
    default_pulse_ms: 20
  c_scoop_eject:
    number: A0-B1-7
    default_pulse_ms: 45

playfields:
  playfield:
    tags: default
    default_source_device: bd_drain

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    activation_switch: s_flipper_left
    debug: true
  right_flipper:
    main_coil: c_flipper_right_main
    activation_switch: s_flipper_right
    debug: true

ball_devices:
  bd_drain:
    ball_switches: s_drain
    eject_coil: c_drain_eject
    tags: drain, home, trough
    debug: true
  bd_scoop:
    ball_switches: s_ir_scoop_detect
    eject_coil: c_scoop_eject
    #eject_events: selector_item_selected, scoop_eject
    debug: true

ball_holds:
   scoop:
     balls_to_hold: 1
     hold_devices: bd_scoop
     release_one_events: scoop_eject

autofire_coils:
  slingshot_left:
    coil: c_slingshot_left
    switch: s_slingshot_left
    timeout_watch_time: 1s
    timeout_max_hits: 1
    timeout_disable_time: 300ms
  slingshot_right:
    coil: c_slingshot_right
    switch: s_slingshot_right
    timeout_watch_time: 1s
    timeout_max_hits: 1
    timeout_disable_time: 300ms
  jet_upper_left:
    coil: c_jet_upper_left
    switch: s_jet_upper_left
  jet_upper_right:
    coil: c_jet_upper_right
    switch: s_jet_upper_right
  jet_lower_center:
    coil: c_jet_lower_center
    switch: s_jet_lower_center

drop_targets:
     L0:
         switch: s_dTargetL0
     L1:
         switch: s_dTargetL1
     L2:
         switch: s_dTargetL2
     L3:
         switch: s_dTargetL3
     R0:
         switch: s_dTargetR0
     R1:
         switch: s_dTargetR1
     R2:
         switch: s_dTargetR2
     R3:
         switch: s_dTargetR3
     LC:
         switch: s_dTargetCL
     RC:
         switch: s_dTargetCR

drop_target_banks:
     leftFull:
         drop_targets: L0, L1, L2, L3
         reset_coils: c_dropLeft0, c_dropLeft1
         reset_on_complete: 500ms
         ignore_switch_ms: 200ms
         reset_events:
           player_turn_will_start, mode_using_targets_ended
     rightFull:
         drop_targets: R0, R1, R2, R3
         reset_coils: c_dropRight0, c_dropRight1
         reset_on_complete: 500ms
         ignore_switch_ms: 200ms
         reset_events:
           player_turn_will_start, mode_using_targets_ended
     leftCenter:
         drop_targets: LC
         reset_coils: c_dropCenterL
         reset_on_complete: 500ms
         ignore_switch_ms: 200ms
         reset_events:
           player_turn_will_start, mode_using_targets_ended
     rightCenter:
         drop_targets: RC
         reset_coils: c_dropCenterR
         reset_on_complete: 500ms
         ignore_switch_ms: 200ms
         reset_events:
           player_turn_will_start, mode_using_targets_ended

virtual_platform_start_active_switches:
  s_drain