#config_version=5

scriptlets:
  - start_interruptor_scriptlet.StartInterruptor
  - bonus_light_controller_scriptlet.BonusLightController
  - bonus_countdown_scriptlet.BonusCountdown
  - shooting_gallery_light_controller.ShootingGalleryLightController
  - shooting_gallery_achievement.ShootingGalleryAchievement
  - player_turn_rethrower.PlayerTurnRethrower
  - ball_goal_calc.BallGoalCalc
  - bonus_box_rotate.BonusBoxRotate
  - bonus_multi_notify.BonusMultiNotify
  - endGame.EndGameEvents
  - selected_check.SelectedCheck
  - flip_delay_scriptlet.FlipDelay
  - last_game_scores.LastGameScores
  - text_type_in.TextTypeIn
  - light_timers_scriptlet.LightTimers
  - wizard_intro.wizardIntro
  - infobox.infobox