#config_version=5

sound_system:
    buffer: 1024
    channels: 1
    enabled: True
    frequency: 44100
    master_volume: 0.75
    tracks:
       music:
          type: standard
          simultaneous_sounds: 1
          volume: .5
       voice:
          type: standard
          simultaneous_sounds: 10
          volume: 0.8
       sfx:
          type: standard
          simultaneous_sounds: 32
          volume: 0.8

sounds:
    # Generic SFX
    soft_laser:
        file: silencedlaser.wav
        track: sfx
        volume: .5
    laser_blast:
        file: laserblast.wav
        track: sfx
        volume: .3
    testFX7:
        file: 39457__the-bizniss__laser-3.wav
    testFX8:
        file: 135885__andre-onate__gama-laser.wav
    bass_hit:
        file: bass_hit.wav
        track: sfx
    character_collect_sound:
        file: character_collect.wav
        track: sfx
        volume: .2
        ducking:
          target: music
          delay: 0ms
          attack: 100ms
          attenuation: .3
          release_point: 1s
          release: 500ms
    laser_pistol:
        file: laser_pistol.wav
        track: sfx
        volume: .2
    explosion1:
        file: explosion1.wav
        track: sfx
        volume: .2
    explosion2:
        file: explosion2.wav
        track: sfx
        volume: .2
    explosion3:
        file: explosion3.wav
        track: sfx
        volume: .2
    triple_explosion:
        file: triple_explosion.wav
        track: sfx
        volume: .2
    charge_shot:
        file: charge_shot.wav
        track: sfx
        volume: .2
    swoosh:
        file: swoosh.wav
        track: sfx
        volume: .8
    drainout:
        file: machinefail.wav
        track: sfx
        volume: .35
    klaxon1:
        file: klaxon1.wav
        track: sfx
        volume: .2
    klaxon2:
        file: klaxon2.wav
        track: sfx
        volume: .2
    blaster:
        file: blaster.wav
        track: sfx
        volume: .7
    drop:
        file: pulserifle.wav
        track: sfx
        volume: .15
    beep:
        file: beep.wav
        track: sfx
        volume: .7

    # Movie SFX
    gallerylaser:
        track: sfx
        file: gallery-laser.wav
    starlaser:
        track: sfx
        file: gallery-star-laser.wav
    gallerylaser_hit:
        track: sfx
        file: gallery-laser-hit.wav

    # Music
    bobandvincent:
        file: BobandVINCent.wav
        track: music
        fade_out: 1s
    cygnusfloating:
        file: CygnusFloating.wav
        track: music
        fade_out: 1s
    durantisdead:
        file: DurantIsDead.wav
        track: music
        fade_out: 1s
    endtheme:
        file: EndTheme.wav
        track: music
        fade_out: 1s
    hotandheavy:
        file: HotAndHeavy.wav
        track: music
        fade_out: 1s
    hotterandheavier:
        file: HotterAndHeavier-SecondHalf.wav
        track: music
        fade_out: 1s
    intothehole:
        file: IntoTheHole.wav
        track: music
        fade_out: 1s
    katesok:
        file: KatesOK.wav
        track: music
        fade_out: 1s
    laser:
        file: Laser.wav
        track: music
        fade_out: 1s
    overture:
        file: Overture.wav
        track: music
        fade_out: 1s
        volume: .3
    prettybusy:
        file: PrettyBusy.wav
        track: music
        fade_out: 1s
    thatsit:
        file: ThatsIt.wav
        track: music
        fade_out: 1s
    thedooropens:
        file: TheDoorOpens.wav
        track: music
        fade_out: 1s
    theme:
        file: Theme.wav
        track: music
        fade_out: 1s
    zerogravity:
        file: ZeroGravity.wav
        track: music
        fade_out: 1s

    #Voice clips
    alex_01:
        file: a_glorious-pilgramage.wav
        track: voice
    alex_02:
        file: a_greatest-space-scientist-2.wav
        track: voice
    bob_01:
        file: b_if-maximilian-knew.wav
        track: voice
    bob_02:
        file: b_this-is-a-death-ship.wav
        track: voice
    charlie_01:
        file: c_lets-get-cracking.wav
        track: voice
    harry_01:
        file: h_are-you-programmed.wav
        track: voice
    kate_01:
        file: k_if-there's-any-justice.wav
        track: voice
    kate_02:
        file: k_old-and-bold-pilots.wav
        track: voice
    kate_03:
        file: k_uss-cygnus-mission.wav
        track: voice
    hans_01:
        file: r_end-justifies-the-means.wav
        track: voice
    hans_02:
        file: r_give-them-distance.wav
        track: voice
    hans_03:
        file: r_in-through-and-beyond.wav
        track: voice
    hans_04:
        file: r_maximilian.wav
        track: voice
    hans_05:
        file: r_one-step-too-far.wav
        track: voice
    hans_06:
        file: r_protect-me-from-maximilian.wav
        track: voice
    hans_07:
        file: r_the-esp-you-share.wav
        track: voice
    vincent_01:
        file: v_a-wolf-remains-a-wolf.wav
        track: voice
    vincent_02:
        file: v_nothing-a-hammer.wav
        track: voice
    vincent_03:
        file: v_ship_uss-cygnus.wav
        track: voice
    vincent_04:
        file: v_to-quote-cicero.wav
        track: voice
    vincent_05:
        file: v_vincent's-my-name.wav
        track: voice
    ball_saved:
        file: ball_saved.wav
        track: voice
    ball_rescued:
        file: ball_rescued.wav
        track: voice
    extra_ball:
        file: extra_ball.wav
        track: voice
    sacrifice:
        file: sacrifice.wav
        track: voice
    scene_ready:
        file: scene_ready.wav
        track: voice
    player_one_up:
        file: first_player_up.wav
        track: voice
        ducking:
          target: music
          delay: 0ms
          attack: 100ms
          attenuation: .1
          release_point: 1.7s
          release: 500ms
    player_two_up:
        file: second_player_up.wav
        track: voice
        ducking:
          target: music
          delay: 0ms
          attack: 100ms
          attenuation: .1
          release_point: 1.7s
          release: 500ms
    player_three_up:
        file: third_player_up.wav
        track: voice
        ducking:
          target: music
          delay: 0ms
          attack: 100ms
          attenuation: .1
          release_point: 1.7s
          release: 500ms
    player_four_up:
        file: fourth_player_up.wav
        track: voice
        ducking:
          target: music
          delay: 0ms
          attack: 100ms
          attenuation: .1
          release_point: 1.7s
          release: 500ms

sound_pools:
  atract_voice:
    type: random_force_all
    track: voice
    sounds:
      - alex_01
      - alex_02
      - bob_01
      - bob_02
      - charlie_01
      - harry_01
      - kate_01
#      - kate_02
      - kate_03
      - hans_01
      - hans_02
      - hans_03
      - hans_04
      - hans_05
      - hans_06
      - hans_07
      - vincent_01
      - vincent_02
#      - vincent_03
      - vincent_04
      - vincent_05
  explosions:
    type: random_force_all
    track: sfx
    sounds:
      - triple_explosion
      - explosion1
      - explosion2
      - explosion3
  ball_end_clips:
    type: random_force_all
    track: voice
    sounds:
      - bob_02
      - hans_02
      - kate_01
      - vincent_02
      - hans_05

