#config_version=5

sound_system:
    buffer: 1024
    channels: 1
    enabled: True
    frequency: 44100
    master_volume: 0.75
    tracks:
       music:
          type: standard
          simultaneous_sounds: 1
          volume: 0.5
       voice:
          type: standard
          simultaneous_sounds: 1
          volume: 0.9
       sfx:
          type: standard
          simultaneous_sounds: 32
          volume: 0.9

sounds:
    # Generic SFX
    testFX1_old:
        file: 18382infernohvylas.wav
    testFX2:
        file: 151022__bubaproducer__laser-shot-silenced.wav
    testFX1:
        file: 191594__fins__laser.wav
    testFX3:
        file: 191594__fins__laser2.wav
    testFX4:
        file: 234083__211redman112__lasgun-fire.ogg
    testFX5:
        file: 321102__nsstudios__laser1.wav
    testFX6:
        file: 344276__nsstudios__laser3.wav
    testFX7:
        file: 39457__the-bizniss__laser-3.wav
    testFX8:
        file: 135885__andre-onate__gama-laser.wav
    bass_hit:
        file: bass_hit.wav
        track: sfx
    character_collect_sound:
        file: character_collect.wav
        track: sfx
        volume: .7
        ducking:
          target: music
          delay: 0ms
          attack: 100ms
          attenuation: .3
          release_point: 1s
          release: 500ms

    # Movie SFX
    gallerylaser:
        file: gallery-laser.wav
    starlaser:
        file: gallery-star-laser.wav
    gallerylaser_hit:
        file: gallery-laser-hit.wav

    # Music
    bobandvincent:
        file: BobandVINCent.wav
        track: music
        fade_out: 1s
    cygnusfloating:
        file: CygnusFloating.wav
        track: music
        fade_out: 1s
        volume: .6
    durantisdead:
        file: DurantIsDead.wav
        track: music
        fade_out: 1s
    endtheme:
        file: EndTheme.wav
        track: music
        fade_out: 1s
    hotandheavy:
        file: HotAndHeavy.wav
        track: music
        fade_out: 1s
    hotterandheavier:
        file: HotterAndHeavier-SecondHalf.wav
        track: music
        fade_out: 1s
    intothehole:
        file: IntoTheHole.wav
        track: music
        fade_out: 1s
    katesok:
        file: KatesOK.wav
        track: music
        fade_out: 1s
    laser:
        file: Laser.wav
        track: music
        fade_out: 1s
    overture:
        file: Overture.wav
        track: music
        fade_out: 1s
        volume: .3
    prettybusy:
        file: PrettyBusy.wav
        track: music
        fade_out: 1s
    thatsit:
        file: ThatsIt.wav
        track: music
        fade_out: 1s
    thedooropens:
        file: TheDoorOpens.wav
        track: music
        fade_out: 1s
    theme:
        file: Theme.wav
        track: music
        fade_out: 1s
    zerogravity:
        file: ZeroGravity.wav
        track: music
        fade_out: 1s

    #Voice clips
    alex_01:
        file: a_glorious-pilgramage.wav
    alex_02:
        file: a_greatest-space-scientist-2.wav
    bob_01:
        file: b_if-maximilian-knew.wav
    bob_02:
        file: b_this-is-a-death-ship.wav
    charlie_01:
        file: c_lets-get-cracking.wav
    harry_01:
        file: h_are-you-programmed.wav
    kate_01:
        file: k_if-there's-any-justice.wav
    kate_02:
        file: k_old-and-bold-pilots.wav
    kate_03:
        file: k_uss-cygnus-mission.wav
    hans_01:
        file: r_end-justifies-the-means.wav
    hans_02:
        file: r_give-them-distance.wav
    hans_03:
        file: r_in-through-and-beyond.wav
    hans_04:
        file: r_maximilian.wav
    hans_05:
        file: r_one-step-too-far.wav
    hans_06:
        file: r_protect-me-from-maximilian.wav
    hans_07:
        file: r_the-esp-you-share.wav
    vincent_01:
        file: v_a-wolf-remains-a-wolf.wav
    vincent_02:
        file: v_nothing-a-hammer.wav
    vincent_03:
        file: v_ship_uss-cygnus.wav
    vincent_04:
        file: v_to-quote-cicero.wav
    vincent_05:
        file: v_vincent's-my-name.wav

sound_pools:
  atract_voice:
    type: random_force_all
    track: voice
    sounds:
      - alex_01
      - alex_02
      - bob_01
      - bob_02
      - charlie_01
      - harry_01
      - kate_01
#      - kate_02
      - kate_03
      - hans_01
      - hans_02
      - hans_03
      - hans_04
      - hans_05
      - hans_06
      - hans_07
      - vincent_01
      - vincent_02
#      - vincent_03
      - vincent_04
      - vincent_05
