#config_version=5

sound_system:
    buffer: 1024
    channels: 1
    enabled: True
    frequency: 44100
    master_volume: 0.75
    tracks:
       music:
          type: standard
          simultaneous_sounds: 1
          volume: 0.5
       voice:
          type: standard
          simultaneous_sounds: 1
          volume: 1.0
       sfx:
          type: standard
          simultaneous_sounds: 32
          volume: 1.0

sounds:
    # Generic SFX
    testFX1_old:
        file: 18382infernohvylas.wav
    testFX2:
        file: 151022__bubaproducer__laser-shot-silenced.wav
    testFX1:
        file: 191594__fins__laser.wav
    testFX3:
        file: 191594__fins__laser2.wav
    testFX4:
        file: 234083__211redman112__lasgun-fire.ogg
    testFX5:
        file: 321102__nsstudios__laser1.wav
    testFX6:
        file: 344276__nsstudios__laser3.wav
    testFX7:
        file: 39457__the-bizniss__laser-3.wav
    testFX8:
        file: 135885__andre-onate__gama-laser.wav
    bass_hit:
        file: bass_hit.wav

    # Movie SFX
    gallerylaser:
        file: gallery-laser.wav
    starlaser:
        file: gallery-star-laser.wav
    gallerylaser_hit:
        file: gallery-laser-hit.wav

    # Music
    overture:
        file: Overture.wav
    meteor:
        file: HotterAndHeavier-SecondHalf.wav
    bobandvincent:
        file: BobandVINCent.wav
    thatsit:
        file: ThatsIt.wav


