#config_version=5

sound_system:
    buffer: 1024
    channels: 1
    enabled: True
    frequency: 44100
    master_volume: 0.75
    tracks:
       music:
          type: standard
          simultaneous_sounds: 1
          volume: 0.5
       voice:
          type: standard
          simultaneous_sounds: 1
          volume: 0.9
       sfx:
          type: standard
          simultaneous_sounds: 32
          volume: 0.9

sounds:
    # Generic SFX
    testFX1_old:
        file: 18382infernohvylas.wav
    testFX2:
        file: 151022__bubaproducer__laser-shot-silenced.wav
    testFX1:
        file: 191594__fins__laser.wav
    testFX3:
        file: 191594__fins__laser2.wav
    testFX4:
        file: 234083__211redman112__lasgun-fire.ogg
    testFX5:
        file: 321102__nsstudios__laser1.wav
    testFX6:
        file: 344276__nsstudios__laser3.wav
    testFX7:
        file: 39457__the-bizniss__laser-3.wav
    testFX8:
        file: 135885__andre-onate__gama-laser.wav
    bass_hit:
        file: bass_hit.wav
        track: sfx
    character_collect_sound:
        file: character_collect.wav
        track: sfx
        ducking:
          target: music
          delay: 0ms
          attack: 100ms
          attenuation: .3
          release_point: 1s
          release: 500ms

    # Movie SFX
    gallerylaser:
        file: gallery-laser.wav
    starlaser:
        file: gallery-star-laser.wav
    gallerylaser_hit:
        file: gallery-laser-hit.wav

    # Music
    bobandvincent:
        file: BobandVINCent.wav
        track: music
        fade_out: 1s
    cygnusfloating:
        file: CygnusFloating.wav
        track: music
        fade_out: 1s
        volume: .6
    durantisdead:
        file: DurantIsDead.wav
        track: music
        fade_out: 1s
    endtheme:
        file: EndTheme.wav
        track: music
        fade_out: 1s
    hotandheavy:
        file: HotAndHeavy.wav
        track: music
        fade_out: 1s
    hotterandheavier:
        file: HotterAndHeavier-SecondHalf.wav
        track: music
        fade_out: 1s
    intothehole:
        file: IntoTheHole.wav
        track: music
        fade_out: 1s
    katesok:
        file: KatesOK.wav
        track: music
        fade_out: 1s
    laser:
        file: Laser.wav
        track: music
        fade_out: 1s
    overture:
        file: Overture.wav
        track: music
        fade_out: 1s
        volume: .3
    prettybusy:
        file: PrettyBusy.wav
        track: music
        fade_out: 1s
    thatsit:
        file: ThatsIt.wav
        track: music
        fade_out: 1s
    thedooropens:
        file: TheDoorOpens.wav
        track: music
        fade_out: 1s
    theme:
        file: Theme.wav
        track: music
        fade_out: 1s
    zerogravity:
        file: ZeroGravity.wav
        track: music
        fade_out: 1s
