#config_version=5

# *** For some reason, it seems widget styles MUST be part of the base "config.yaml"
# *** This file is included in config.yaml so all widget_styles to be used system-wide should be placed in this file only

widget_styles:
   char_collect_style_top:
        color: red
        font_size: 68
        font_name: ocr-a-tribute-bold
        opacity: .9
        z: 15
        y: 77%
        anchor_y: top
        anchor_x: center
   char_collect_style_bottom:
        color: red
        font_size: 70
        font_name: ocr-a-tribute-bold
        opacity: .9
        z: 15
        y: 31%
        number_grouping: true
        anchor_y: top
        anchor_x: center
   high_score_mode_style:
        font_name: ocr-a-tribute-bold
        font_size: 50
        color: FF2C1F
        anchor_y: top
        anchor_x: right
        number_grouping: true
   high_score_mode_title_style:
        font_name: ocr-a-tribute-bold
        font_size: 50
        color: FF2C1F
        y: top - 40
        x: center
        anchor_y: top
        anchor_x: center
        opacity: 1
        z: 15
   hs_pos_1:
        y: 540
        x: 500
        z: 1
   hs_pos_2:
        y: 480
        x: 500
        z: 1
   hs_pos_3:
        y: 420
        x: 500
        z: 1
   hs_pos_4:
        y: 360
        x: 500
        z: 1
   hs_pos_5:
        y: 300
        x: 500
        z: 1
   hs_pos_6:
        y: 240
        x: 500
        z: 1
   hs_pos_1_score:
        y: 540
        x: 950
        z: 1
   hs_pos_2_score:
        y: 480
        x: 950
        z: 1
   hs_pos_3_score:
        y: 420
        x: 950
        z: 1
   hs_pos_4_score:
        y: 360
        x: 950
        z: 1
   hs_pos_5_score:
        y: 300
        x: 950
        z: 1
   hs_pos_6_score:
        y: 240
        x: 950
        z: 1
   hs_badge:
        anchor_x: center
        anchor_y: center
        z: 1
        opacity: .25
        scale: 2
   thank_you_style:
        color: red
        font_size: 90
        font_name: ocr-a-tribute-bold
        opacity: .9
        z: 15
        x: center
   thank_you_style_alt:
        color: red
        font_name: ocr-a-tribute-bold
        opacity: .9
        anchor_x: center
        anchor_y: top
        font_size: 40
        x: 76%
        z: 15
   thank_you_style2:
        color: blue
        font_size: 90
        font_name: ocr-a-tribute-bold
        opacity: .9
        z: 15
        x: center
        y: 75%

# MODE INFOBOARD STYLES
   infoboard_line_1_background:
        font_size: 48
        font_name: digital-7-mono
        color: 380000
        anchor_x: left
        anchor_y: top
        x: 14.6%
        y: 96.8%
        z: 61
   infoboard_line_1_data:
        number_grouping: true
        min_digits: 2
        font_size: 48
        font_name: digital-7-mono
        color: AC0000
        anchor_x: left
        anchor_y: top
        x: 14.6%
        y: 96.8%
        z: 70
   infoboard_line_2_background:
        font_size: 48
        font_name: digital-7-mono
        color: 380000
        anchor_x: left
        anchor_y: top
        x: 14.6%
        y: 91.8%
        z: 61
   infoboard_line_2_data:
        number_grouping: true
        min_digits: 2
        font_size: 48
        font_name: digital-7-mono
        color: AC0000
        anchor_x: left
        anchor_y: top
        x: 14.6%
        y: 91.8%
        z: 70
   infoboard_line_3_background:
        font_size: 48
        font_name: digital-7-mono
        color: 380000
        anchor_x: left
        anchor_y: top
        x: 14.6%
        y: 86.8%
        z: 61
   infoboard_line_3_data:
        number_grouping: true
        min_digits: 2
        font_size: 48
        font_name: digital-7-mono
        color: AC0000
        anchor_x: left
        anchor_y: top
        x: 14.6%
        y: 86.8%
        z: 70

# MODE 1-6 OUTRO STYLES
   mode_outro_title:
        color: red
        font_size: 40
        anchor_x: left
        anchor_y: top
        font_name: ocr-a-tribute-bold
        opacity: 1
        x: 16%
        y: 71%
        z: 50
   mode_outro_data_line_1:
        x: 16%
        y: 66%
        anchor_x: left
        anchor_y: top
        color: red
        opacity: 1
        z: 50
        number_grouping: true
   mode_outro_data_line_2:
        x: 16%
        y: 62%
        anchor_x: left
        anchor_y: top
        color: red
        opacity: 1
        z: 50
        number_grouping: true
   mode_outro_video:
        volume: 0.5
#        width: 400
#        height: 300
        z: 51
        anchor_x: left
        anchor_y: top
        x: 50%
        y: 72%
   mode_out_title_with_video:
        color: red
        font_size: 40
        anchor_x: left
        anchor_y: top
        font_name: ocr-a-tribute-bold
        opacity: 1
        x: 15%
        y: 74%
        z: 51
   mode_out_detail_1_with_video:
        color: red
        font_size: 40
        anchor_x: right
        anchor_y: top
        font_name: ocr-a-tribute-bold
        opacity: 1
        x: 85%
        y: 74%
        z: 51
   mode_out_detail_2_with_video:
        color: red
        font_size: 40
        anchor_x: right
        anchor_y: top
        font_name: ocr-a-tribute-bold
        opacity: 1
        x: 85%
        y: 30%
        z: 51
        number_grouping: true

# END OF BALL BONUS STYLES
   eob_bonus_title:
        font_size: 100
        font_name: digital-7-mono
        text: END OF BALL BONUS
        color: AC0000
        y: 85%
        z: 20
   eob_bonus_text_title:
        font_size: 60
        font_name: digital-7-mono
        color: AC0000
        anchor_x: left
        anchor_y: top
        x: 10%
        z: 20
   eob_bonus_values:
        font_size: 60
        font_name: digital-7-mono
        color: AC0000
        anchor_x: right
        anchor_y: top
        number_grouping: true
        x: 88%
        z: 20
   eob_bonus_value_background:
        font_size: 60
        font_name: digital-7-mono
        color: 380000
        anchor_x: right
        anchor_y: top
        number_grouping: true
        x: 88%
        z: 19
   eob_bonus_line_1:
        y: 70%
   eob_bonus_line_2:
        y: 61%
   eob_bonus_line_3:
        y: 52%
   eob_bonus_line_4:
        y: 43%
   eob_bonus_line_5:
        y: 34%
