#config_version=5
widgets:
  sample_quick_vid:
      - type: video
        video: test
        x: 1040
        y: 600
        width: 640
        height: 480
        auto_play: true
        end_behavior: stop
  select_01_off:
      - type: text
        text: Locate the Cygnus
        font_size: 100
        color: white
        y: 85%
  select_01_completed:
      - type: text
        text: --Cygnus Located--
        font_size: 100
        color: blue
        y: 85%
  select_02_off:
      - type: text
        text: Escape the Black Hole
        font_size: 100
        color: white
        y: 70%
  select_02_completed:
      - type: text
        text: --Black Hole Escaped--
        font_size: 100
        color: blue
        y: 70%
  select_03_off:
      - type: text
        text: Shooting Gallery
        font_size: 100
        color: white
        y: 55%
  select_03_completed:
      - type: text
        text: --Shooting Gallery Complete--
        font_size: 100
        color: blue
        y: 55%
  select_04_off:
      - type: text
        text: Meteor Strike
        font_size: 100
        color: white
        y: 40%
  select_04_completed:
      - type: text
        text: --Meteor Strike Complete--
        font_size: 100
        color: blue
        y: 40%
  select_05_off:
      - type: text
        text: Corridor Battle
        font_size: 100
        color: white
        y: 25%
  select_05_completed:
      - type: text
        text: --Corridor Battle Complete--
        font_size: 100
        color: blue
        y: 25%
  select_06_off:
      - type: text
        text: David vs. Goliath
        font_size: 100
        color: white
        y: 10%
  select_06_completed:
      - type: text
        text: --David vs. Goliath Complete--
        font_size: 100
        color: blue
        y: 10%