#config_version=5

widgets:
  sample_quick_vid:
      - type: video
        video: test
        x: 1040
        y: 600
        width: 640
        height: 480
        auto_play: true
        end_behavior: stop
  select_01_off:
      - type: text
        text: MODE 01
        font_size: 100
        color: white
        y: 85%
  select_01_completed:
      - type: text
        text: --Story 1 Complete--
        font_size: 100
        color: blue
        y: 85%
  select_02_off:
      - type: text
        text: MODE 02
        font_size: 100
        color: white
        y: 70%
  select_02_completed:
      - type: text
        text: --Story 2 Complete--
        font_size: 100
        color: blue
        y: 70%
  select_03_off:
      - type: text
        text: MODE 03
        font_size: 100
        color: white
        y: 55%
  select_03_completed:
      - type: text
        text: --Story 3 Complete--
        font_size: 100
        color: blue
        y: 55%
  select_04_off:
      - type: text
        text: MODE 04
        font_size: 100
        color: white
        y: 40%
  select_04_completed:
      - type: text
        text: --Story 4 Complete--
        font_size: 100
        color: blue
        y: 40%
  select_05_off:
      - type: text
        text: MODE 05
        font_size: 100
        color: white
        y: 25%
  select_05_completed:
      - type: text
        text: --Story 5 Complete--
        font_size: 100
        color: blue
        y: 25%
  select_06_off:
      - type: text
        text: MODE 06
        font_size: 100
        color: white
        y: 10%
  select_06_completed:
      - type: text
        text: --Story 6 Complete--
        font_size: 100
        color: blue
        y: 10%