#config_version=5

mode:
   start_events: yt_hurry_up_started
   stop_events: timer_yttimer_complete
   priority: 400

variable_player:
   mode_yt_hurry_up_started:
     temp_ythurryup_value:
       action: set
       int: 100000
   timer_yttimer_tick:
     temp_ythurryup_value: -300
   s_sTargetYellowL_active:
     score: current_player.temp_ythurryup_value|block
   s_sTargetYellowR_active:
     score: current_player.temp_ythurryup_value|block

timers:
   yttimer:
     start_value: 300
     end_value: 0
     tick_interval: .1s
     direction: down
     start_running: yes

widget_player:
   mode_yt_hurry_up_started:
      yt_remain_widget:
         slide: scoring_slide
   yt_hurry_up_ended:
      yt_remain_widget:
         action: remove

widgets:
   yt_remain_widget:
     - type: text
       text: "Yellow Hurry Up: (temp_ythurryup_value)"
       y: 20%

