#config_version=5

# *** ONLY *** Use this for modes that do not have their own purpose for the scoop!
# Right now this starts with all story modes **EXCEPT**
#   #1 (Locate the Cygnus)
#   #2 (Escape the black hole)
#   #4 (Meteor)
mode:
   start_events: selector_untitled_mode_3_selected, selector_untitled_mode_5_selected, selector_untitled_mode_6_selected
   stop_events: ball_will_end, mode_story01_stopped, mode_story02_stopped, mode_story03_stopped, mode_story05_stopped, mode_story06_stopped, mode_story07_stopped
   priority: 1000

event_player:
  shotScoopOverride_hit:
    - local_timer_pause

variable_player:
  shotScoopOverride_hit:
    score: 25000
    bonuscount: 10

shots:
  shotScoopOverride:
    switch: s_ir_scoop_detect
    show_tokens:
      light: l_scoop
    profile: shotProfileScoopOverride

shot_profiles:
  shotProfileScoopOverride:
    show_when_disabled: true
    advance_on_hit: false
    block: true
    states:
      - name: scoop_override
        show: off

