#config_version=5

mode:
   start_events: trigger_super_spins
   stop_events: end_super_spins, ball_ending
   priority: 2500

event_player:
   mode_superSpins_started:
     invoke_notify_by_event:
       new_text: "SUPER\nSPINS"
       new_value: "ACTIVE"
   timer_superspins_complete:
     - end_super_spins

show_player:
   mode_superSpins_started:
      superSpin:
        loops: -1
   timer_superspins_complete:
      superSpin:
        action: stop

timers:
   superspins:
     start_value: 30
     end_value: 0
     direction: down
     start_running: true
     control_events:
        - event: global_timer_pause
          action: pause
        - event: global_timer_unpause
          action: start

variable_player:
  s_spinner_active:
    score: 1000 * current_player.temp_playfield_x * current_player.perm_playfield_x|block

widget_player:
   mode_superSpins_started:
       superSpinTimer:
          slide: scoring_slide
   timer_superspins_complete:
       superSpinTimer:
          slide: scoring_slide
          action: remove

widgets:
  superSpinTimer:
    - type: ellipse
      width: 70
      height: 70
      color: 012077
      x: 77%
      y: 18%
      anchor_x: center
      anchor_y: center
      z: 10
    - type: ellipse
      width: 70
      height: 70
      color: black
      x: 77%
      y: 18%
      anchor_x: center
      anchor_y: center
      z: 20
      angle_start: 0
      angle_end: 12
      animations:
         timer_superspins_tick:
            property: angle_end
            value: 12
            relative: true
            duration: 1s
    - type: ellipse
      width: 60
      height: 60
      color: black
      x: 77%
      y: 18%
      anchor_x: center
      anchor_y: center
      z: 30
    - type: text
      text: "SUPER\nSPINS"
      font_name: lucon
      x: 77%
      y: 18%
      anchor_x: center
      anchor_y: center
      z: 40
      color: BBD8F0
      font_size: 16
