#config_version=5

# David vs. Goliath - Pop bumper frenzy. Pop bumpers do damage, time elapsed without pops costs points. Win!

config:
  - story06-scoring.yaml

mode:
   start_events: selector_untitled_mode_6_selected
   stop_events: story_is_completed
   stop_on_ball_end: false
   priority: 900

# All Story Modes --
#     Issue a scoop_eject after any introduction activities
# Modes that end with a Scoop Hit --
#     Issue a scoop eject after any outro-activities

# Success/Failure
# By default, success = not losing ball, failure = losing ball
# If your mode has a different ruleset, change when the events
# story_is_completed_successful / acheivement_story##_successful
# story_is_completed_unsuccessful / acheivement_story##_unsuccessful
# are issued.

queue_relay_player:
  ball_ending:
    post: story_is_about_to_fail
    wait_for: story_outro_fail_complete

event_player:
   mode_story06_started:
     - story_is_about_to_begin
   story_intro_complete:
     - scoop_eject
   player_damage{value<=0}:
     - story_is_about_to_end
   timer_battletimer_complete:
     - story_is_about_to_fail
   story_outro_complete:
     - story_is_completed_successful
     - acheivement_story06_successful
   story_outro_fail_complete:
     - story_is_completed_unsuccessful
     - acheivement_story06_unsuccessful
   story_is_completed_successful:
     - story_is_completed
   story_is_completed_unsuccessful:
     - story_is_completed

#  Base intro / outro shows
show_player:
   story_is_about_to_begin:
      story_06_intro:
         events_when_completed: story_intro_complete
         loops: 0
   story_is_about_to_fail:
      story_06_outro_fail:
         events_when_completed: story_outro_fail_complete
         loops: 0
   story_is_about_to_end:
      story_06_outro:
         events_when_completed: story_outro_complete
         loops: 0

shows:
   story_06_intro:
     - time: 0
       slides: story_06_intro_slide
       duration: 3
   story_06_outro_fail:
     - time: 0
       slides: story_06_outro_fail_slide
       duration: 3
   story_06_outro:
     - time: 0
       slides: story_06_outro_slide
       duration: 3

slides:
   story_06_intro_slide:
    widgets:
      - type: text
        text: DAVID VS. GOLIATH
        color: red
        font_size: 100
        font_name: ocr-a-tribute-bold
      - type: text
        text: Hit Pop Bumpers to attack MAXIMILLIAN!
        y: 40%
        color: red
        font_size: 50
   story_06_outro_fail_slide:
    widgets:
      - type: text
        text: DAVID VS. GOLIATH
        color: red
        font_size: 100
        font_name: ocr-a-tribute-bold
      - type: text
        text: No one sucks as bad as you.
        y: 40%
        color: red
        font_size: 50
   story_06_outro_slide:
    widgets:
      - type: text
        text: DAVID VS. GOLIATH
        color: red
        font_size: 100
        font_name: ocr-a-tribute-bold
      - type: text
        text: "You Kicked some Robot Butt in just (battletime)s"
        y: 40%
        color: red
        font_size: 50

# The below is mode specific data

variable_player:
   mode_story06_started:
     damage:
       action: set
       int: 999
   story_intro_complete:
     damage:
       action: set
       int: 30
     battleticks:
       action: set
       int: 0
     greenness:
       action: set
       int: 498
   timer_battletimer_tick:
     damage: 1
   timer_battlecounter_tick:
     battleticks: 1
   shotgrouppopbumpers_hit:
     damage: -3
   story_is_about_to_end:
     battletime:
       action: set
       float: current_player.battleticks / 10
   timer_greentimer_tick:
     greenness: -1

timers:
   battlecounter:
     start_value: 0
     tick_interval: .1s
     direction: up
     start_running: no
     control_events:
        - event: story_intro_complete
          action: start
        - event: story_is_about_to_end
          action: pause
          value: 0
   battletimer:
     start_value: 30
     end_value: 60
     tick_interval: 1s
     direction: up
     start_running: no
     control_events:
        - event: story_intro_complete
          action: start
        - event: shotgrouppopbumpers_hit
          action: subtract
          value: 3
        - event: story_is_about_to_end
          action: pause
          value: 0
   greentimer:
     start_value: 498
     end_value: 0
     tick_interval: 100ms
     direction: down
     start_running: yes

widget_player:
   mode_story06_started:
      yt_remain_widget_06:
         slide: scoring_slide
   story_intro_complete:
      david_and_goliath_widget:
         slide: scoring_slide
      green_bar_widget:
         slide: scoring_slide
      health_shell_blackout_widget:
         slide: scoring_slide
      health_shell_widget:
         slide: scoring_slide
   story_is_about_to_end:
      david_and_goliath_widget:
         action: remove
      health_shell_widget:
         action: remove
      health_shell_blackout_widget:
         action: remove
      green_bar_widget:
         action: remove
   story06_ended:
      yt_remain_widget_06:
         action: remove

widgets:
  yt_remain_widget_06:
    - type: text
      text: "VINCent :0:  (damage)   :60: Maximillian"
      y: 80%
  david_and_goliath_widget:
    - type: image
      image: david_goliath
  health_shell_widget:
    - type: rectangle
      y: 50
      width: 1000
      height: 20
      corner_radius: 3
      corner_segments: 3
      color: CC0000
  health_shell_blackout_widget:
    - type: rectangle
      y: 50
      width: 996
      height: 16
      corner_radius: 3
      corner_segments: 3
      color: 000000
  green_bar_widget:
    - type: rectangle
      y: 50
      z: 20
      anchor_x: left
      anchor_y: center
      width: 1
      height: 16
      corner_radius: 3
      corner_segments: 3
      color: 00FF00


#my_test_slide:
#  widgets:
#    - type: image
#      image: david_goliath
#    - type: rectangle
#      y: 50
#      width: 6
#      height: 20
#      color: CC0000
#    - type: rectangle
#      y: 50
#      anchor_x: left
#      anchor_y: center
#      width: 498
#      height: 16
#      corner_radius: 3
#      corner_segments: 3
#      color: 00FF00
#    - type: rectangle
#      y: 50
#      anchor_x: right
#      anchor_y: center
#      width: 235
#      height: 16
#      corner_radius: 3
#      corner_segments: 3
#      color: FF0000
#    - type: rectangle
#      y: 50
#      width: 996
#      height: 16
#      corner_radius: 3
#      corner_segments: 3
#      color: 000000
#    - type: rectangle
#      y: 50
#      width: 1000
#      height: 20
#      corner_radius: 3
#      corner_segments: 3
#      color: CC0000
#
