#config_version=5

# David vs. Goliath - Pop bumper frenzy. Pop bumpers do health, time elapsed without pops costs points. Win!

config:
  - story06-scoring.yaml
  - ballsave.yaml

mode:
  start_events: selector_untitled_mode_6_selected
  stop_events: story_is_completed
  stop_on_ball_end: false
  priority: 900
  file_log: full

# All Story Modes --
#     Issue a scoop_eject after any introduction activities
# Modes that end with a Scoop Hit --
#     Issue a scoop eject after any outro-activities

# Success/Failure
# By default, success = not losing ball, failure = losing ball
# If your mode has a different ruleset, change when the events
# story_is_completed_successful / acheivement_story##_successful
# story_is_completed_unsuccessful / acheivement_story##_unsuccessful
# are issued.

queue_relay_player:
  ball_ending:
    post: story_is_about_to_fail
    wait_for: story_outro_fail_complete

event_player:
  mode_story06_started:
    - story_is_about_to_begin
  story_intro_complete:
    - scoop_eject
  in_mode_ball_save:
     - story_is_about_to_fail
  player_health{value >= 100}:
    - story_is_about_to_end
  player_health{value <= 0}:
    - story_is_about_to_fail
  story_outro_complete:
    - story_is_completed_successful
    - acheivement_story06_successful
  story_outro_fail_complete:
    - story_is_completed_unsuccessful
    - acheivement_story06_unsuccessful
  story_is_completed_successful:
    - story_is_completed
  story_is_completed_unsuccessful:
    - story_is_completed

#  Base intro / outro shows
show_player:
  story_is_about_to_begin:
    story_06_intro:
      events_when_completed: story_intro_complete
      loops: 0
  story_is_about_to_fail:
    story_06_outro_fail:
      events_when_completed: story_outro_fail_complete
      loops: 0
  story_is_about_to_end:
    story_06_outro:
      events_when_completed: story_outro_complete
      loops: 0

shows:
  story_06_intro:
    - time: 0
      slides: story_06_intro_slide
      duration: 3
  story_06_outro_fail:
    - time: 0
      slides: story_06_outro_fail_slide
      duration: 3
  story_06_outro:
    - time: 0
      slides: story_06_outro_slide
      duration: 3

slides:
  story_06_intro_slide:
    widgets:
      - type: text
        text: David vs. Goliath
        color: red
        font_size: 100
        font_name: ocr-a-tribute-bold
      - type: text
        text: Hit pop bumpers to attack Maximilian!
        y: 40%
        color: red
        font_size: 50
  story_06_outro_fail_slide:
    widgets:
      - type: text
        text: Goliath defeats David
        color: red
        font_size: 100
        font_name: ocr-a-tribute-bold
      - type: text
        text: Only this time, David is overmatched...
        y: 40%
        color: red
        font_size: 50
  story_06_outro_slide:
    widgets:
      - type: text
        text: David defeats Goliath!
        color: red
        font_size: 100
        font_name: ocr-a-tribute-bold
      - type: text
        text: "The bigger they are, the harder they fall. [Time taken:(battletime)s]"
        y: 40%
        color: red
        font_size: 50

# The below is mode specific data
variable_player:
  story_intro_complete:
    health:
      action: set
      float: 50
    battleticks:
      action: set
      int: 0
  timer_battletimer_tick:
    health: -1 #Health lost per second.
  timer_battlecounter_tick:
    battleticks: 1
  shotgrouppopbumpers_hit:
    health: 5 #Health gained per pop bumper hit.
  story_is_about_to_end:
    battletime:
      action: set
      float: current_player.battleticks / 10
  player_health{value > 50}:
    red_width:
      action: set
      int: 0
    green_width:
      action: set
      int: (current_player.health - 50) / 50 * 298
  player_health{value < 50}:
    red_width:
      action: set
      int: (50 - current_player.health) / 50 * 298
    green_width:
      action: set
      int: 0
  player_health{value == 50}:
    red_width:
      action: set
      int: 0
    green_width:
      action: set
      int: 0

timers:
  battlecounter:
    start_value: 0
    tick_interval: .1s
    direction: up
    start_running: no
    control_events:
      - event: story_intro_complete
        action: start
      - event: story_is_about_to_end
        action: pause
        value: 0
  battletimer:
    start_value: 0 #50
#    end_value: 0
    tick_interval: 1s
    direction: up # down
    start_running: no
    control_events:
      - event: story_intro_complete
        action: start
#      - event: shotgrouppopbumpers_hit
#        action: add
#        value: 5
      - event: story_is_about_to_end
        action: pause
        value: 0

widget_player:
#  mode_story06_started:
#    yt_remain_widget_06:
#      slide: scoring_slide
  story_intro_complete:
    david_and_goliath_widget:
      slide: scoring_slide
    green_bar_widget:
      slide: scoring_slide
    red_bar_widget:
      slide: scoring_slide
    health_shell_blackout_widget:
      slide: scoring_slide
    health_shell_widget:
      slide: scoring_slide
    health_shell_centerline:
      slide: scoring_slide
  story_is_about_to_end:
    dsavid_and_goliath_widget:
      action: remove
    health_shell_widget:
      action: remove
    health_shell_blackout_widget:
      action: remove
    health_shell_centerline:
      action: remove
    green_bar_widget:
      action: remove
    red_bar_widget:
      action: remove
#  story06_ended:
#    yt_remain_widget_06:
#      action: remove

widgets:
#  yt_remain_widget_06:
#    - type: text
#      text: "H (health)  |  BT (battleticks)  |  RW (red_width)  |  GW (green_width)"
#      y: 80%
  david_and_goliath_widget:
    - type: image
      image: david_goliath
      z: 19
  health_shell_widget:
    - type: rectangle
      y: top - 50
      z: 20
      width: 600
      height: 20
      corner_radius: 3
      corner_segments: 3
      color: CC0000
  health_shell_blackout_widget:
    - type: rectangle
      y: top - 50
      z: 21
      width: 596
      height: 16
      corner_radius: 3
      corner_segments: 3
      color: 000000
  green_bar_widget:
    - type: rectangle
      y: top - 50
      z: 22
      anchor_x: left
      anchor_y: center
      width: 0
      height: 16
      corner_radius: 3
      corner_segments: 3
      color: 00FF00
      animations:
        player_green_width:
          - property: width
            value: (value)
            duration: 250ms
  red_bar_widget:
    - type: rectangle
      y: top - 50
      z: 22
      anchor_x: right
      anchor_y: center
      width: 0
      height: 16
      corner_radius: 3
      corner_segments: 3
      color: FF0000
      animations:
        player_red_width:
          - property: width
            value: (value)
            duration: 250ms
  health_shell_centerline:
    - type: rectangle
      y: top - 50
      z: 23
      width: 6
      height: 23
      color: CC0000