#config_version=5

# David vs. Goliath - Pop bumper frenzy. Pop bumpers do damage, time elapsed without pops costs points. Win!

config:
  - story06-scoring.yaml

mode:
   start_events: selector_untitled_mode_6_selected
   stop_events: story_is_completed
   priority: 400

# All Story Modes --
#     Issue a scoop_eject after any introduction activities
# Modes that end with a Scoop Hit --
#     Issue a scoop eject after any outro-activities

# Success/Failure
# By default, success = not losing ball, failure = losing ball
# If your mode has a different ruleset, change when the events
# story_is_completed_successful / acheivement_story##_successful
# story_is_completed_unsuccessful / acheivement_story##_unsuccessful
# are issued.

event_player:
   mode_story06_started:
     - story_is_about_to_begin
   story_intro_complete:
     - scoop_eject
   player_damage{value<=0}:
     - story_is_about_to_end
   timer_battletimer_complete:
     - story_is_about_to_fail
   story_outro_complete:
     - story_is_completed_successful
     - acheivement_story06_successful
   story_outro_fail_complete:
     - story_is_completed_unsuccessful
     - acheivement_story06_unsuccessful
   ball_will_end:
     - story_is_about_to_fail
#     - story_is_completed_unsuccessful
#     - acheivement_story06_unsuccessful
   story_is_completed_successful:
     - story_is_completed
   story_is_completed_unsuccessful:
     - story_is_completed

#  Base intro / outro shows
show_player:
   story_is_about_to_begin:
      story_06_intro:
         events_when_advanced: story_intro_complete
         events_when_completed: story_intro_complete
         events_when_stopped: story_intro_complete
         loops: 0
   story_is_about_to_fail:
      story_06_outro_fail:
         events_when_advanced: story_outro_fail_complete
         events_when_completed: story_outro_fail_complete
         events_when_stopped: story_outro_fail_complete
         loops: 0
   story_is_about_to_end:
      story_06_outro:
         events_when_advanced: story_outro_complete
         events_when_completed: story_outro_complete
         events_when_stopped: story_outro_complete
         loops: 0

shows:
   story_06_intro:
     - time: 0
       slides: story_06_intro_slide
       duration: 3
   story_06_outro_fail:
     - time: 0
       slides: story_06_outro_fail_slide
       duration: 3
   story_06_outro:
     - time: 0
       slides: story_06_outro_slide
       duration: 3

slides:
   story_06_intro_slide:
    widgets:
      - type: text
        text: DAVID VS. GOLIATH
        color: red
        font_size: 100
        font_name: ocr-a-tribute-bold
      - type: text
        text: Hit Pop Bumpers to attack MAXIMILLIAN!
        y: 40%
        color: red
        font_size: 50
   story_06_outro_fail_slide:
    widgets:
      - type: text
        text: DAVID VS. GOLIATH
        color: red
        font_size: 100
        font_name: ocr-a-tribute-bold
      - type: text
        text: No one sucks as bad as you.
        y: 40%
        color: red
        font_size: 50
   story_06_outro_slide:
    widgets:
      - type: text
        text: DAVID VS. GOLIATH
        color: red
        font_size: 100
        font_name: ocr-a-tribute-bold
      - type: text
        text: "You Kicked some Robot Butt in just (battletime)s"
        y: 40%
        color: red
        font_size: 50

# The below is mode specific data

variable_player:
   story_intro_complete:
     damage:
       action: set
       int: 30
     battleticks:
       action: set
       int: 0
   timer_battletimer_tick:
     damage: 1
   timer_battlecounter_tick:
     battleticks: 1
   shotgrouppopbumpers_hit:
     damage: -3
   story_is_about_to_end:
     battletime:
       action: set
       float: current_player.battleticks / 10

timers:
   battlecounter:
     start_value: 0
     tick_interval: .1s
     direction: up
     start_running: no
     control_events:
        - event: story_intro_complete
          action: start
        - event: story_is_about_to_end
          action: pause
          value: 0
   battletimer:
     start_value: 30
     end_value: 60
     tick_interval: 1s
     direction: up
     start_running: no
     control_events:
        - event: story_intro_complete
          action: start
        - event: shotgrouppopbumpers_hit
          action: subtract
          value: 3
        - event: story_is_about_to_end
          action: pause
          value: 0

widget_player:
   mode_story06_started:
      yt_remain_widget_06:
         slide: scoring_slide
   story06_ended:
      yt_remain_widget_06:
         action: remove

widgets:
   yt_remain_widget_06:
     - type: text
       text: "VINCent :0:  (damage)   :60: Maximillian"
       y: 80%

