#config_version=5

# David vs. Goliath - Pop bumper frenzy. Pop bumpers do health, time elapsed without pops costs points. Win!

#TODO -- Character Collect -- Certain amount of time overall?

config:
  - story06-scoring.yaml
  - infoboard.yaml

mode:
  start_events: ready_to_start_mode_6
  stop_events: story_is_completed
  stop_on_ball_end: false
  priority: 900
  file_log: full

# All Story Modes --
#     Issue a scoop_eject after any introduction activities
# Modes that end with a Scoop Hit --
#     Issue a scoop eject after any outro-activities

# Success/Failure
# By default, success = not losing ball, failure = losing ball
# If your mode has a different ruleset, change when the events
# story_is_completed_successful / acheivement_story##_successful
# story_is_completed_unsuccessful / acheivement_story##_unsuccessful
# are issued.

queue_relay_player:
  ball_ending:
    post: story_is_about_to_fail
    wait_for: story_outro_fail_complete

event_player:
  mode_story06_started:
    - story_is_about_to_begin
    - information_board_start
  story_intro_complete:
    - scoop_eject
    - start_david_timer
    - global_timer_unpause
  story_is_about_to_fail:
     - information_board_end
  story_is_about_to_end:
     - information_board_end
  player_health{value >= 100}:
    - story_is_about_to_end
  player_health{value <= 0}:
    - story_is_about_to_fail
  story_outro_complete:
    - story_is_completed_successful
    - acheivement_story06_successful
  story_outro_fail_complete:
    - story_is_completed_unsuccessful
    - acheivement_story06_unsuccessful
  story_is_completed_successful:
    - story_is_completed
#TODO -- for now we are granting a character just for completing
    - random_character_collect|3100ms
  story_is_completed_unsuccessful:
    - story_is_completed

#  Base intro / outro shows
show_player:
#  story_is_about_to_begin:
#    story_06_intro:
#      events_when_completed: story_intro_complete
#      loops: 0
  story_is_about_to_fail:
    story_06_outro_fail:
      events_when_completed: story_outro_fail_complete
      loops: 0
  story_is_about_to_end:
    story_06_outro:
      events_when_completed: story_outro_complete
      loops: 0



# The below is mode specific data
variable_player:
  story_intro_complete:
    health:
      action: set
      float: 50
    battleticks:
      action: set
      int: 0
  timer_battletimer_tick{current_player.health<100}:
    health: -1 #Health lost per second.
  timer_battlecounter_tick:
    battleticks: 1
  shotgrouppopbumpers_hit{current_player.health<100}:
    health: 5 #Health gained per pop bumper hit.
  story_is_about_to_end:
    battletime:
      action: set
      float: current_player.battleticks / 10
  player_battletime:
    modestat_6_final_time:
      action: set
      float: current_player.battletime
  player_health{value > 50}:
    red_width:
      action: set
      int: 0
    green_width:
      action: set
      int: (current_player.health - 50) / 50 * 298
  player_health{value < 50}:
    red_width:
      action: set
      int: (50 - current_player.health) / 50 * 298
    green_width:
      action: set
      int: 0
  player_health{value == 50}:
    red_width:
      action: set
      int: 0
    green_width:
      action: set
      int: 0

timers:
  battlecounter:
    start_value: 0
    tick_interval: .1s
    direction: up
    start_running: no
    control_events:
      - event: start_david_timer
        action: start
      - event: story_is_about_to_end
        action: pause
        value: 0
      - event: global_timer_pause
        action: pause
      - event: global_timer_unpause
        action: start

  battletimer:
    start_value: 0 #50
#    end_value: 0
    tick_interval: 1s
    direction: up # down
    start_running: no
    control_events:
      - event: start_david_timer
        action: start
#      - event: shotgrouppopbumpers_hit
#        action: add
#        value: 5
      - event: story_is_about_to_end
        action: pause
        value: 0
      - event: global_timer_pause
        action: pause
      - event: global_timer_unpause
        action: start

widget_player:
  story_intro_complete:
    david_and_goliath_widget:
      slide: scoring_slide
    green_bar_widget:
      slide: scoring_slide
    red_bar_widget:
      slide: scoring_slide
    health_shell_blackout_widget:
      slide: scoring_slide
    health_shell_widget:
      slide: scoring_slide
    health_shell_centerline:
      slide: scoring_slide
  story_is_about_to_end:
    dsavid_and_goliath_widget:
      action: remove
    health_shell_widget:
      action: remove
    health_shell_blackout_widget:
      action: remove
    health_shell_centerline:
      action: remove
    green_bar_widget:
      action: remove
    red_bar_widget:
      action: remove

widgets:
  david_and_goliath_widget:
    - type: image
      image: david_goliath
      z: 19
  health_shell_widget:
    - type: rectangle
      y: center - 197
      z: 20
      width: 600
      height: 20
      corner_radius: 3
      corner_segments: 3
      color: BBD8F0
  health_shell_blackout_widget:
    - type: rectangle
      y: center - 197
      z: 21
      width: 596
      height: 16
      corner_radius: 3
      corner_segments: 3
      color: 000000
  green_bar_widget:
    - type: rectangle
      y: center - 197
      z: 22
      anchor_x: left
      anchor_y: center
      width: 0
      height: 16
      corner_radius: 3
      corner_segments: 3
      color: 00FF00
      animations:
        player_green_width:
          - property: width
            value: (value)
            duration: 250ms
  red_bar_widget:
    - type: rectangle
      y: center - 197
      z: 22
      anchor_x: right
      anchor_y: center
      width: 0
      height: 16
      corner_radius: 3
      corner_segments: 3
      color: FF0000
      animations:
        player_red_width:
          - property: width
            value: (value)
            duration: 250ms
  health_shell_centerline:
    - type: rectangle
      y: center - 197
      z: 23
      width: 6
      height: 23
      color: 323D4A

sound_player:
    mode_story06_started:
      overture:
          action: stop
          fade_out: 0
    mode_06_end_video:
      hotterandheavier:
          action: play
          loops: -1
          mode_end_action: stop