#config_version=5
event_player:
   story_is_about_to_begin:
     - mode_03_setintro_01|2s
     - mode_03_setintro_02|2s
     - mode_03_setintro_03|2s
     - mode_03_setintro2_02|7s
     - mode_03_setintro3_02|7s
     - mode_03_start_video
     # 14.708s
     - mode_03_end_video|15.5s
     - story_intro_complete|12.5s
   mode_03_setintro_01:
     set_infoboard_line_text:
        linenbr: 1
        text: "SHOOTING GALLERY"
        pts: none
        secs: none
        cycle: "star"
        delayms: 25
   mode_03_setintro_02:
     set_infoboard_line_text:
        linenbr: 2
        text: "V.I.N.CENT'S MY NAME -- "
        pts: none
        secs: none
        cycle: "star"
        delayms: 25
   mode_03_setintro_03:
     set_infoboard_line_text:
        linenbr: 3
        text: "SHARPSHOOTING'S MY GAME!  TRY ME!"
        pts: none
        secs: none
        cycle: "star"
        delayms: 25
   mode_03_setintro2_02:
     set_infoboard_line_text:
        linenbr: 2
        text: "HIT AT LEAST 3 LIT TARGETS IN 60S"
        pts: none
        secs: none
        cycle: "star"
        delayms: 25
   mode_03_setintro3_02:
     set_infoboard_line_text:
        linenbr: 3
        text: "TO DEFEAT CAPTAIN S.T.A.R."
        pts: none
        secs: none
        cycle: "star"
        delayms: 25
   story_intro_complete:
     - mode_03_setinfo_01
     - mode_03_setinfo_02
     - mode_03_setinfo_03
   mode_03_setinfo_01:
     set_infoboard_line_text:
        linenbr: 1
        text: "SHOOTING GALLERY"
        pts: none
        secs: none
        cycle: "instant"
        delayms: 0
   player_modestat_3_scoring:
     set_infoboard_line_text:
        linenbr: 1
        text: "SHOOTING GALLERY"
        pts: modestat_3_scoring
        secs: none
        cycle: "instant"
        delayms: 0
   mode_03_setinfo_02:
     set_infoboard_line_text:
        linenbr: 2
        text: "TARGETS HIT"
        pts: none
        secs: none
        cycle: "instant"
        delayms: 0
   player_gallery_targets_hit:
     set_infoboard_line_text:
        linenbr: 2
        text: "TARGETS HIT"
        pts: gallery_targets_hit
        secs: none
        cycle: "instant"
        delayms: 0
   mode_03_setinfo_03:
     set_infoboard_line_text:
        linenbr: 3
        text: "TIME REMAINING"
        pts: none
        secs: none
        cycle: "instant"
        delayms: 0
   player_gallery_timer_remaining:
     set_infoboard_line_text:
        linenbr: 3
        text: "TIME REMAINING"
        pts: none
        secs: gallery_timer_remaining
        cycle: "instant"
        delayms: 0
