#config_version=5

mode:
   start_events: selector_untitled_mode_3_selected
   stop_events: story_is_completed
   priority: 900
   file_log: full

# All Story Modes --
#     Issue a scoop_eject after any introduction activities
# Modes that end with a Scoop Hit --
#     Issue a scoop eject after any outro-activities
# TEMP UNTIL REAL MODE PUT INTO PLACE

# Success/Failure
# By default, success = not losing ball, failure = losing ball
# If your mode has a different ruleset, change when the events
# story_is_completed_successful / acheivement_story##_successful
# story_is_completed_unsuccessful / acheivement_story##_unsuccessful
# are issued.

queue_relay_player:
  ball_ending:
    post: story_is_about_to_fail
    wait_for: story_outro_fail_complete

event_player:
   mode_story03_started:
     - story_is_about_to_begin
     - mode_using_targets_started # always add this if your mode makes use of the drop targets
   story_intro_complete:
     - scoop_eject
   timer_yttimer03_complete:
     - story_is_about_to_end
   story_outro_complete:
     - story_is_completed_successful
     - acheivement_story03_successful
     - mode_using_targets_ended # always add this if your mode makes use of the drop targets
#    Only used when scoop hits end the mode
#    - scoop_eject
   story_outro_fail_complete:
     - story_is_completed_unsuccessful
     - acheivement_story03_unsuccessful
   story_is_completed_successful:
    - story_is_completed
   story_is_completed_unsuccessful:
    - story_is_completed

#  Base intro / outro shows
show_player:
   story_is_about_to_begin:
      story_03_intro:
         events_when_completed: story_intro_complete
         loops: 0
      drop_target_blackout_show:
         priority: 400
   story_is_about_to_fail:
      story_03_fail_outro:
         events_when_completed: story_outro_fail_complete
         loops: 0
   story_is_about_to_end:
      story_03_outro:
         events_when_completed: story_outro_complete
         loops: 0
   gallery_light_change{lightname=="l_dropRight0" and colorval=="red"):
      gallery_flasher_show:
         speed: 10
         priority: 401
         loops: -1
         show_tokens:
           ln: l_dropRight0
           cv: FF0000
   gallery_light_change{lightname==l_dropRight1" and colorval=="red"):
      gallery_flasher_show:
         speed: 10
         priority: 401
         loops: -1
         show_tokens:
           ln: l_dropRight1
           cv: FF0000
   gallery_light_change{lightname=="l_dropRight2" and colorval=="red"):
      gallery_flasher_show:
         speed: 10
         priority: 401
         loops: -1
         show_tokens:
           ln: l_dropRight2
           cv: FF0000
   gallery_light_change{lightname=="l_dropRight3" and colorval=="red"):
      gallery_flasher_show:
         speed: 10
         priority: 401
         loops: -1
         show_tokens:
           ln: l_dropRight3
           cv: FF0000
   gallery_light_change{lightname=="l_dropLeft0" and colorval=="red"):
      gallery_flasher_show:
         speed: 10
         priority: 401
         loops: -1
         show_tokens:
           ln: l_dropLeft0
           cv: FF0000
   gallery_light_change{lightname=="l_dropLeft1" and colorval=="red"):
      gallery_flasher_show:
         speed: 10
         priority: 401
         loops: -1
         show_tokens:
           ln: l_dropLeft1
           cv: FF0000
   gallery_light_change{lightname=="l_dropLeft2" and colorval=="red"):
      gallery_flasher_show:
         speed: 10
         priority: 401
         loops: -1
         show_tokens:
           ln: l_dropLeft2
           cv: FF0000
   gallery_light_change{lightname=="l_dropLeft3" and colorval=="red"):
      gallery_flasher_show:
         speed: 10
         priority: 401
         loops: -1
         show_tokens:
           ln: l_dropLeft3
           cv: FF0000
shows:
   story_03_intro:
     - time: 0
       slides: story_03_intro_slide
       duration: 3
   story_03_fail_outro:
     - time: 0
       slides: story_03_outro_fail_slide
       duration: 3
   story_03_outro:
     - time: 0
       slides: story_03_outro_slide
       duration: 3

slides:
   story_03_intro_slide:
    widgets:
      - type: text
        text: STORY 03 BEGIN SHOW
        color: red
        font_size: 100
        font_name: ocr-a-tribute-bold
   story_03_outro_fail_slide:
      - type: text
        text: YOU ARE TEH SUCK
        color: red
        font_size: 100
        font_name: ocr-a-tribute-bold
   story_03_outro_slide:
    widgets:
      - type: text
        text: STORY 03 END SHOW
        color: red
        font_size: 100
        font_name: ocr-a-tribute-bold

# The below is mode specific data

variable_player:
   mode_story03_started:
     temp_ythurryup_value:
       action: set
       int: 100000
   timer_yttimer03_tick:
     temp_ythurryup_value: -300
   s_sTargetYellowL_active:
     score: current_player.temp_ythurryup_value|block
   s_sTargetYellowR_active:
     score: current_player.temp_ythurryup_value|block

timers:
   gallery_timer:
     max_value: 600
     start_value: 600
     end_value: 0
     tick_interval: 500ms
     direction: down
     start_running: no
     control_events:
      - event: story_intro_complete
        action: start