#config_version=5

config:
  - story03-scoring.yaml
  - infoboard.yaml

mode:
  start_events: ready_to_start_mode_3
  stop_events: story_is_completed
  priority: 900
  file_log: full

# All Story Modes --
#     Issue a scoop_eject after any introduction activities
# Modes that end with a Scoop Hit --
#     Issue a scoop eject after any outro-activities
# TEMP UNTIL REAL MODE PUT INTO PLACE

# Success/Failure
# By default, success = not losing ball, failure = losing ball
# If your mode has a different ruleset, change when the events
# story_is_completed_successful / acheivement_story##_successful
# story_is_completed_unsuccessful / acheivement_story##_unsuccessful
# are issued.

queue_relay_player:
  ball_ending:
    post: story_is_about_to_fail
    wait_for: story_outro_fail_complete

event_player:
  mode_story03_started:
    - story_is_about_to_begin
    - information_board_start
    - mode_using_targets_started # always add this if your mode makes use of the drop targets
    # Reset all drop targets
    - drops_left_reset
    - drops_right_reset
    - drop_left_center_reset
    - drop_right_center_reset
#  story_intro_complete:
#    - scoop_eject
#    - global_timer_unpause
  story_outro_complete:
    - story_is_completed_successful
    - acheivement_story03_successful
    - mode_using_targets_ended # always add this if your mode makes use of the drop targets
#    Only used when scoop hits end the mode
#    - scoop_eject
  story_is_about_to_fail:
    - information_board_end
  story_is_about_to_end:
     - information_board_end
  story_outro_fail_complete:
    - story_is_completed_unsuccessful
    - acheivement_story03_unsuccessful
  story_is_completed_successful:
    - story_is_completed
  story_is_completed_unsuccessful:
    - story_is_completed
  shot_dt_r0_flashing_red_hit:
    - gallery_target_hit
    - drops_right_reset
  shot_dt_r1_flashing_red_hit:
    - gallery_target_hit
    - drops_right_reset
  shot_dt_r2_flashing_red_hit:
    - gallery_target_hit
    - drops_right_reset
  shot_dt_r3_flashing_red_hit:
    - gallery_target_hit
    - drops_right_reset
  shot_dt_l0_flashing_red_hit:
    - gallery_target_hit
    - drops_left_reset
  shot_dt_l1_flashing_red_hit:
    - gallery_target_hit
    - drops_left_reset
  shot_dt_l2_flashing_red_hit:
    - gallery_target_hit
    - drops_left_reset
  shot_dt_l3_flashing_red_hit:
    - gallery_target_hit
    - drops_left_reset
  shot_dt_cr_flashing_red_hit:
    - gallery_target_hit
    - drop_right_center_reset
  shot_dt_cl_flashing_red_hit:
    - gallery_target_hit
    - drop_left_center_reset
  shot_dt_r0_flashing_green_hit:
    - gallery_target_hit
    - drops_right_reset
  shot_dt_r1_flashing_green_hit:
    - gallery_target_hit
    - drops_right_reset
  shot_dt_r2_flashing_green_hit:
    - gallery_target_hit
    - drops_right_reset
  shot_dt_r3_flashing_green_hit:
    - gallery_target_hit
    - drops_right_reset
  shot_dt_l0_flashing_green_hit:
    - gallery_target_hit
    - drops_left_reset
  shot_dt_l1_flashing_green_hit:
    - gallery_target_hit
    - drops_left_reset
  shot_dt_l2_flashing_green_hit:
    - gallery_target_hit
    - drops_left_reset
  shot_dt_l3_flashing_green_hit:
    - gallery_target_hit
    - drops_left_reset
  shot_dt_cr_flashing_green_hit:
    - gallery_target_hit
    - drop_right_center_reset
  shot_dt_cl_flashing_green_hit:
    - gallery_target_hit
    - drop_left_center_reset
  shot_dt_r0_flashing_blue_hit:
    - gallery_target_hit
    - drops_right_reset
  shot_dt_r1_flashing_blue_hit:
    - gallery_target_hit
    - drops_right_reset
  shot_dt_r2_flashing_blue_hit:
    - gallery_target_hit
    - drops_right_reset
  shot_dt_r3_flashing_blue_hit:
    - gallery_target_hit
    - drops_right_reset
  shot_dt_l0_flashing_blue_hit:
    - gallery_target_hit
    - drops_left_reset
  shot_dt_l1_flashing_blue_hit:
    - gallery_target_hit
    - drops_left_reset
  shot_dt_l2_flashing_blue_hit:
    - gallery_target_hit
    - drops_left_reset
  shot_dt_l3_flashing_blue_hit:
    - gallery_target_hit
    - drops_left_reset
  shot_dt_cr_flashing_blue_hit:
    - gallery_target_hit
    - drop_right_center_reset
  shot_dt_cl_flashing_blue_hit:
    - gallery_target_hit
    - drop_left_center_reset
  shot_dt_r0_unlit_hit:
    - gallery_unlit_target_hit
    - drops_right_reset
  shot_dt_r1_unlit_hit:
    - gallery_unlit_target_hit
    - drops_right_reset
  shot_dt_r2_unlit_hit:
    - gallery_unlit_target_hit
    - drops_right_reset
  shot_dt_r3_unlit_hit:
    - gallery_unlit_target_hit
    - drops_right_reset
  shot_dt_l0_unlit_hit:
    - gallery_unlit_target_hit
    - drops_left_reset
  shot_dt_l1_unlit_hit:
    - gallery_unlit_target_hit
    - drops_left_reset
  shot_dt_l2_unlit_hit:
    - gallery_unlit_target_hit
    - drops_left_reset
  shot_dt_l3_unlit_hit:
    - gallery_unlit_target_hit
    - drops_left_reset
  shot_dt_cr_unlit_hit:
    - gallery_unlit_target_hit
    - drop_right_center_reset
  shot_dt_cl_unlit_hit:
    - gallery_unlit_target_hit
    - drop_left_center_reset
# Character Collect
  player_gallery_targets_hit{value==5}:
    - random_character_collect

shots:
  shot_dt_l0:
    switch: s_dTargetL0
    show_tokens:
      light: l_dropLeft0
    profile: shot_profile_gallery_targets
    advance_events: gallery_light_0_change
    reset_events: gallery_light_0_off
  shot_dt_l1:
    switch: s_dTargetL1
    show_tokens:
      light: l_dropLeft1
    profile: shot_profile_gallery_targets
    advance_events: gallery_light_1_change
    reset_events: gallery_light_1_off
  shot_dt_l2:
    switch: s_dTargetL2
    show_tokens:
      light: l_dropLeft2
    profile: shot_profile_gallery_targets
    advance_events: gallery_light_2_change
    reset_events: gallery_light_2_off
  shot_dt_l3:
    switch: s_dTargetL3
    show_tokens:
      light: l_dropLeft3
    profile: shot_profile_gallery_targets
    advance_events: gallery_light_3_change
    reset_events: gallery_light_3_off
  shot_dt_r0:
    switch: s_dTargetR0
    show_tokens:
      light: l_dropRight0
    profile: shot_profile_gallery_targets
    advance_events: gallery_light_4_change
    reset_events: gallery_light_4_off
  shot_dt_r1:
    switch: s_dTargetR1
    show_tokens:
      light: l_dropRight1
    profile: shot_profile_gallery_targets
    advance_events: gallery_light_5_change
    reset_events: gallery_light_5_off
  shot_dt_r2:
    switch: s_dTargetR2
    show_tokens:
      light: l_dropRight2
    profile: shot_profile_gallery_targets
    advance_events: gallery_light_6_change
    reset_events: gallery_light_6_off
  shot_dt_r3:
    switch: s_dTargetR3
    show_tokens:
      light: l_dropRight3
    profile: shot_profile_gallery_targets
    advance_events: gallery_light_7_change
    reset_events: gallery_light_7_off
  shot_dt_cr:
    switch: s_dtargetcr
    show_tokens:
      light: l_dropCenterRight
    profile: shot_profile_gallery_targets
    advance_events: gallery_light_8_change
    reset_events: gallery_light_8_off
  shot_dt_cl:
    switch: s_dtargetcl
    show_tokens:
      light: l_dropCenterLeft
    profile: shot_profile_gallery_targets
    advance_events: gallery_light_9_change
    reset_events: gallery_light_9_off

shot_profiles:
  shot_profile_gallery_targets:
    block: true
    advance_on_hit: false
    show_when_disabled: false
    states:
      - name: unlit
        show: gallery_flasher_off_show
        priority: 901
      - name: flashing_red
        show: gallery_flasher_red_show
        priority: 901
        speed: 10
      - name: flashing_green
        show: gallery_flasher_green_show
        priority: 901
        speed: 10
      - name: flashing_blue
        show: gallery_flasher_blue_show
        priority: 901
        speed: 10

#  Base intro / outro shows
show_player:
  story_is_about_to_begin:
#    story_03_intro:
#      events_when_completed: story_intro_complete
#      loops: 0
    drop_target_blackout_show:
      priority: 900
    giDim:
      loops: -1
      priority: 900
  scoop_eject_sequence:
    scoop_eject_sound_show:
      priority: 950
      loops: 0
      events_when_completed: scoop_eject, global_timer_unpause
    scoop_eject_light_show:
      priority: 950
      loops: 0
  story_is_about_to_fail:
    story_03_fail_outro:
      events_when_completed: story_outro_fail_complete
      loops: 0
  story_is_about_to_end:
    story_03_outro:
      events_when_completed: story_outro_complete
      loops: 0


# The below is mode specific data

variable_player:
  mode_story03_started:
    gallery_targets_hit:
      action: set
      int: 0
  gallery_target_hit:
    gallery_targets_hit: 1
  story_is_about_to_end:
    modestat_3_final_hits:
      action: set
      int: (current_player.gallery_targets_hit)
  timer_gallery_timer_display_tick:
    gallery_timer_remaining:
      action: set
      float: (ticks_remaining) * .1

timers:
  gallery_timer:
    max_value: 6
    start_value: 6
    end_value: 0
    tick_interval: 10s
    direction: down
    start_running: no
    control_events:
      - event: story_intro_complete
        action: start
      - event: local_timer_pause
        action: pause
      - event: local_timer_unpause
        action: start
  gallery_timer_display:
    max_value: 600
    start_value: 600
    end_value: 0
    tick_interval: .1s
    direction: down
    start_running: no
    control_events:
      - event: story_intro_complete
        action: start
      - event: local_timer_pause
        action: pause
      - event: local_timer_unpause
        action: start

sound_player:
    gallery_target_hit: gallerylaser_hit
    gallery_unlit_target_hit: gallerylaser
    mode_story03_started:
      overture:
          action: stop
          fade_out: 0
    mode_03_end_video:
      bobandvincent:
        action: play
        loops: -1
        mode_end_action: stop


